### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by MarcosBL** [Laravel-Backpack/Base#102]
Trying Install on Laravel 5.4 as per https://laravel-backpack.readme.io/docs/install-on-laravel-54

The step 

`` php artisan migrate #generates users table (using Laravel's default migrations) ``

fails trying to create the **users table index on email** with error

`` [Illuminate\Database\QueryException] SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`)) ``

I think it's related to field encoding, as you define *utf8mb4_unicode_ci* in

```` create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci ````

Due the extended charset, it overflows max InnoDB default install default key length (767, Ubuntu 16.04) .

You can, of course, reconfigure MySQL server innodb_page_size to 32k (> MySQL 5.7) to avoid that (starting server from scratch!), but doesn't seems intuitive, and email field emoji support doesn't seem needed.

Traced that back to `config/database.php` and changed to `ut8_unicode_ci` but I really think the index creation should specify a different encoding for that index so you can complete the installation process.

**Comment by OwenMelbz** [comment]
Short and sweet, read the laravel docs :) it explains how to fix.

https://laravel.com/docs/master/migrations#creating-indexes

**Comment by MarcosBL** [comment]
Sometimes myself being this stupid even hurts... thank you very much OwenMelbz
