### ISSUE TITLE
Envoyer and Forge Removing Images with deployments

### ISSUE THREAD

**Issue by imcodingideas** [Laravel-Backpack/Base#103]
Hello,

We are using Envoyer and Forge for server management and deployment. This is getting saved to storage/app/public/uploads/event_images 

in the /home/forge/default we have a storage folder. 

```
public function setFeaturedImageAttribute($value)
    {
        $attribute_name = "featured_image";
        $disk = "uploads";
        $destination_path = "event_images";

        // if a base64 was sent, store it in the db
        if (starts_with($value, 'data:image'))
        {
            // 0. Make the image
            $image = \Image::make($value);
            // 1. Generate a filename.
            $filename = md5($value.time()).'.jpg';
            // 2. Store the image on disk.
            \Storage::disk($disk)->put($destination_path.'/'.$filename, $image->stream());
            // 3. Save the path to the database
            $this->attributes[$attribute_name] = $disk.'/'.$destination_path.'/'.$filename;
        }

    }
```

**Comment by OwenMelbz** [comment]
Hi,

I don't mean to sound rude or dismissive, however this is a laravel disk issue rather than anything to do with backpack.

Taylor Otwell specifically replies to paying customer emails, you should contact him via the support asking how to persist storage folders across deployments.

**Comment by OwenMelbz** [comment]
P.s.

Don't mention backpack, it will confuse the situation. Your using nothing more but a native laravel accessor and an image facade.

**Comment by imcodingideas** [comment]
Thank you Owen. Your reply was perfect. You mentioned where to go and how
to explain it. Thumbs up.

**Comment by tabacitu** [comment]
Hi @imcodingideas , 

I'm very curious to find out what the problem was, even though it was not Backpack-related. I also use Forge and was planning on using Envoyer in the future. When you find out what the problem was, could you please tell us too? :-)

Cheers!

**Comment by OwenMelbz** [comment]
I'm not sure what the official answer will be, but I think your just meant to use an absolute path in your disk configs to define the storage path outside of your application. E.g

/home/forge/storage
/home/forge/deployment1/
/home/forge/deployment2/

That way the storage folder never changes so your files persist across
