### ISSUE TITLE
Similar route name will make menu items <li> class "active" at the same time

### ISSUE THREAD

**Issue by ghost** [Laravel-Backpack/Base#104]
If the route name is similar (../service & ../service-category), the side bar menu `<li>` are added `"active"` class together for "Service" and "Service Category" Sidebar menu.

``` javascript
// Set active state on menu element
var current_url = "{{ url(Route::current()->getUri()) }}";
$("ul.sidebar-menu li a").each(function() {
    if ($(this).attr('href').startsWith(current_url) || current_url.startsWith($(this).attr('href'))) {
        $(this).parents('li').addClass('active');
    }
});
```

The above code in the `layout.blade.php` need to be reviewed.

when the current_url is "`../../service`" or "`../../service-category`", the startWith function will give true when "Service" / “Service Category” menu is clicked.

**Comment by MarcosBL** [comment]
Just pinging @kidd86 to see if you want to try my PR https://github.com/Laravel-Backpack/Base/pull/115
