### ISSUE TITLE
Apply Multi Lists per View

### ISSUE THREAD

**Issue by CHOMNANP** [Laravel-Backpack/Base#109]
I would like to create a view with more than one list. Is it possible to use Base View?

- View Management
  - Tab1: List View 1
  - Tab2: List View 2
  - Tab3: List View 3
...

Thanks.

**Comment by tabacitu** [comment]
Hi @CHOMNANP ,

It's not a built-in feature, but of course, it's possible. Starting with CRUD 3.2 you can [use a custom view for your CRUD operation](https://laravel-backpack.readme.io/docs/crud-full-api#section-sometimes-used) a lot easier:
```
$this->crud->setListView('your-view');
```

This way, you can use your own view. You can have any number of tabs, or anything else there. Start from the original ```list.blade.php``` and do your thing.

Hope it helps.
Cheers!
