### ISSUE TITLE
Content-Length mismatch with laravel 5.4

### ISSUE THREAD

**Issue by delower186** [Laravel-Backpack/Base#123]
I am trying to install it on laravel 5.4 fresh installation but when I run  the following error shows:

> composer require backpack/base

> Content-Length mismatch
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

**Comment by tabacitu** [comment]
Hi @delower186 ,

I trust it was a packagist unavailability issue and you've been able to install backpack since them? If not, please reopen the issue.

Cheers!

**Comment by h4km** [comment]
I have a same problem too. but I installed laravel 5.2

**Comment by delower186** [comment]
Hi @tabacitu ,
I could install it with the process of fresh installation instruction but not on existing project ):

**Comment by mrkalmdn** [comment]
Try updating composer.

**Comment by chenyangguang** [comment]
I have the the same problem in composer update. 
 `Composer version 1.4.1 2017-03-10 09:29:45`
 Using  laravel5.4 .( My os is ubuntu14.04.)

**Comment by tabacitu** [comment]
Hi @chenyangguang ,

Thanks for posting. Could you please copy-paste the entire composer process&message, help us figure out what might be going on?

Cheers!

**Comment by chenyangguang** [comment]
Hemm, It works well now after  I updated my os from ubuntu14.04 to ubuntu16.04. @tabacitu , Thank you for  you following.
