### ISSUE TITLE
Overriding LoginController

### ISSUE THREAD

**Issue by mwei0210** [Laravel-Backpack/Base#124]
Hi, so I am using my own LoginController instead of the original one, by:

- adding app\Http\Controllers\Auth\LoginController.php and extending it to Backpack\Base\app\Http\Controllers\Auth\LoginController
- setting 'setup_auth_routes' => false

It works well in local xampp environment whereas break down in ubuntu server. The server copy does not use the controller i made, instead it uses the original controller in vendor. Anyone has any idea why this happens or what I missed out?

**Comment by OwenMelbz** [comment]
Hi, GitHub issues is for package bugs, not general support. For that you should be using stackoverflow.

For that reason I'll have to close this as it's not a package bug.

This is also highly unlikely to be a backpack problem, more of a general user error/laravel issue. As it's not something anybody but yourself would be familiar with there's not much we can do except suggest you debug your application properly by stepping through it. Check your namespaces, check everything is uploaded, make sure all classes are imported etc.
