### ISSUE TITLE
Create Backpack\Installer for all packages

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#13]
**PROPOSAL** [up for debate]
**Package name:** backpack/base (included there)
**Syntax:** php artisan backpack:install (then follow on-screen instructions)

For that to happen seamlessly, we need a way to install packages without user input. There is no package to do that in Laravel 5, but there were a few good ones in Laravel 4: [rtablada/package-installer](https://github.com/rtablada/package-installer) and [terion-name/package-installer](https://github.com/terion-name/package-installer).

So creating backpack/installer implies creating **a general Laravel 5 package installer package**.
**Package name:** backpack/unpacker or tabacitu/unpacker 
**Syntax:** 
- php artisan unpacker:install backpack/crud
- php artisan unpacker:register-service Backpack\CRUD\CrudServiceProvider
- php artisan unpacker:register-alias CRUD Backpack\CRUD\CrudServiceProvider

**Main functionality:**
- upon the unpacker:install command, parse the provides.json and do whatever is necessary to install the package;
- in addition to what the old packages did, have the [provides.json](https://github.com/rtablada/package-installer) also contain a "scripts" array with "post-install-cmd", "pre-install-cmd" so scripts can be run upon installation;
- APIs (you can call them in your packages): 
  - parse an X file and insert Y the next line after Z;
  - register providers;
  - register aliases;

---

After everything is said and done, the following process will be the official Backpack installation process:
1) Install Laravel
2) Install Backpack/Unpacker
3) php artisan unpacker:install backpack/base (installs Backpack/Base)
4) php artisan backpack:install (starts the installation wizard; user needs to follow on-screen instructions and choose which backpack packages to install, choose configurations/options etc.)

**Comment by tabacitu** [comment]
Backpack\Base installation wizard will have the following steps:
Stage I: Packages
1) Do you want to install Backpack\CRUD? (Y/N)
2) Do you want to install Backpack\Generators? (Y/N)
3) Do you want to install Backpack\LangFileManager? (Y/N)
4) Do you want to install Backpack\BackupManager? (Y/N)
5) Do you want to install Backpack\LogManager? (Y/N)
Stage II: Ready-built CRUDs
6) Do you want to install Backpack\SettingsManager? (Y/N)
7) Do you want to install Backpack\PageManager? (Y/N)
8) Do you want to install Backpack\MenuManager? (Y/N)
9) Do you want to install Backpack\NewsManager? (Y/N)

**Comment by OwenMelbz** [comment]
Maybe a silly question, but why not include a generator in backpack base?

Would that not be easier for the user than having to install something, to install something else?

**Comment by tabacitu** [comment]
Thanks for bringing that up! 

I've considered it and dismissed it, because the Generators package is only needed in the development environment, not test or production. And it's bad practice to autoload a service provider if you're not going to use it in production. But I've just realised we can have both:
- Backpack\Base can require Backpack\Generators;
- but Backpack\Base can register Backpack\Generators [only if the environment is "local"](https://github.com/laracasts/Laravel-5-Generators-Extended#usage); 
Basically Generators and Installer can come pre-installed in Backpack\Base;

We can then do the same to Backpack\Installer. That way, both Installer and Generators can be kept in isolated, single-purpose github repositories, with their own issues, fixes and versioning, but they will be available to the developer as soon as he installs Backpack/Base.

This can be implemented right away with Backpack/Generators and will [reduce the steps needed to install a complete Backpack system by 2 steps](https://laravel-backpack.readme.io/docs/installation-on-laravel-53#4-install-backpackgenerators-optional). If you can't find a fault with this idea, I'll go ahead and create an issue for it, so we'll do it sooner rather than later - I'm very eager to reduce the installation steps, I consider that a big turnoff in Backpack right now.

Cheers and again - thanks for bringing this up.

**Comment by OwenMelbz** [comment]
That seems pretty good then, just to clarify then;

Would the composer.json contain requirements to both extra packages? eg.

```json
"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "backpack/base": "^0.7.0",
        "backpack/crud": "^3.1"
    },
    "require-dev": {
        "backpack/generators": "^1.1",
        "backpack/installer": "^1.1"
    },
```

If the above is the case, then if you were to release a crud/base update, that also required a generator/installer update, would the users have to know to update both of the installers/generators as well as the base/crud package? Or is it possible to force an update of the generators/installers as well?

**Comment by tabacitu** [comment]
Damn. I remembered. Actually, it would be something like this:

```json
"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "backpack/base": "^0.7.0",
        "backpack/crud": "^3.1",
        "backpack/generators": "^1.1",
        "backpack/installer": "^1.1"
    },
```
That's because [composer won't install require-dev from packages](http://stackoverflow.com/questions/21154216/composer-wont-install-require-dev-packages), only the require-dev from the main composer.json file. 

So generators and installer would be in the /vendor/ folder on the test&production servers too, not just local. But they wouldn't be registered (no autoload, not loaded in the service provider because the environment is not "local").

Hmm... I don't know... Needs more pondering...

**Comment by OwenMelbz** [comment]
Maybe a yeoman recipe is the way forward or a global installer package similar to Laravel/composer ?

**Comment by tabacitu** [comment]
Ok so I'll be slimming down the proposals in the next few days, to make sure we keep focused on what's important for the future of Backpack.

The end goal for Backpack is for it to **provide the solid, flexible base for people to build admin panels on**. It's what Backpack\Base and Backpack\CRUD already do, though it could use more work on the _solid_ part right now. We write _the core_, and every functionality or use case is then treated by a separate package. We've released quite a few, and in the past 6 months there have been 6+ packages that use Backpack that way. So it looks like we got the ball rolling.

I think we should make it easy for people to install compatible packages, but a better approach would be for each package to have its own installer, rather than having "_one installer to rule them all_". We might, of course, create a package that does the heavy lifting and each compatible package requires it, but I don't see an installer like detailed above being viable anymore. The most obvious reason is that I foresee many packages that do the same thing, from different providers. For example, an alternative package to LogManager is almost ready. So people should install the package they want, not the package the installer wants. This makes a lot more sense if things evolve in the direction it seems they are - a package marketplace.

That's my train of though, what do you think, do you agree?

**Comment by OwenMelbz** [comment]
I think we should probably lean on the new auto package discovery to do a lot of things.

However I think before any plan would be decided - we need to write down exactly what steps are needed to get it "working" to be able to see what's worth automating?

You could then theoretically just have like a `php artisan backpack:install $addon` which just looks for a "install" method on the service provider, and runs it - letting the developer writing the package installing - I would hope there would be barely anything anyway right?
