### ISSUE TITLE
Separate routes files for each Backpack package

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#130]
What if:
- we create a new folder inside the project, ```routes\backpack\```;
- each Backpack package would take a look inside that folder before registering its routes. If the file exists, it uses loads the routes file; otherwise it loads the routes the old-fashioned way;

So when completely overwritten, the routes folder would look like this:
- routes
  - backpack
    - base.php
    - crud.php
    - logmanager.php
    - backupmanager.php
    - pagemanager.php
    - settings.php
    - menucrud.php
    - newscrud.php
  - api.php
  - console.php
  - web.php

I think this would:
- be a familiar way to change package routes (very similar to the config folder);
- make it a lot easier for developers to overwrite the classes inside the Backpack packages;
- clean up the ```web.php``` routes file;
- allow us to automatically insert routes when generating CRUDs (we'd just insert a new ```CRUD::resource()``` inside the ```routes\backpack\crud.php``` file);

What do you think? Good/bad idea?

**Comment by OwenMelbz** [comment]
Sure :)

**Comment by AbbyJanke** [comment]
I did something similar to this myself. but because I am limiting what gets put in there as it is, I actually just made an `routes\admin.php` with all the routes then loaded it within `App\Providers\RouteServiceProvider.php`

**Comment by MarcosBL** [comment]
+1 to this!

**Comment by lloy0076** [comment]
https://github.com/Laravel-Backpack/Base/issues/131

...may be related...

**Comment by tabacitu** [comment]
BOOM! Done.
