### ISSUE TITLE
Remove Frontend registration

### ISSUE THREAD

**Issue by eyemiru** [Laravel-Backpack/Base#133]
Hi guys,

how can I remove only frontend registration? Not only view/template but completely.
This includes "forgot password" function as well.

Thanks

**Comment by tabacitu** [comment]
Hi @eyemiru ,

You'll find a config option in your ```/config/backpack/base.php```:
```php
    /*
    |--------------------------------------------------------------------------
    | Registration Open
    |--------------------------------------------------------------------------
    |
    | Choose wether new users are allowed to register.
    | This will show up the Register button in the menu and allow access to the
    | Register functions in AuthController.
    |
    */

    'registration_open' => env('APP_ENV')=='local'?true:false,
```

As for disabling the "forgot password" functionality - I recommend against that. Your admins WILL forget their passwords, and they WILL bug you to change it :-) But if you want that, just register the "forgot password" routes again in your routes file, and send them to an error page. Something like this should work:

```php
Route::post('admin/password/email', 'CustomController@disabledFeature');
Route::post('admin/password/reset', 'CustomController@disabledFeature');
Route::get('admin/password/reset', 'CustomController@disabledFeature');
Route::get('admin/password/reset/{token}', 'CustomController@disabledFeature');
```

Cheers!

**Comment by eyemiru** [comment]
Hi @tabacitu, thanks much! :)

**Comment by zachweix** [comment]
@tabacitu I have a website that I just put into production and the registration link is indeed gone, but if I go to `/admin/register` I can still register a user. That seems like a security issue. Is there a way to completely block that in production?
