### ISSUE TITLE
How to add extra auth password create route?

### ISSUE THREAD

**Issue by octoxan** [Laravel-Backpack/Base#139]
With Laravel's default auth I was able to just do this...

```
Route::get('password/create/{token}', 'Auth\ResetPasswordController@showResetForm')->name('Create Password');
```

to basically duplicate the password reset page as a "Create Password" page since my application requires users to be created by an admin, and them they're emailed a password create link.

Can't for the life of me figure out how to duplicate this for the backpack auth routes?

**Comment by lloy0076** [comment]
Try `php artisan route:list` and look for passport maybe?

I think you might be looking for:

```
36 |        | GET|HEAD                       | admin/password/reset                                        | password.request                       | App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm
 37 |        | POST                           | admin/password/reset                                        |                                        | App\Http\Controllers\Auth\ResetPasswordController@reset
```

...one of them.
