### ISSUE TITLE
Using closures in routes breaks route caching 

### ISSUE THREAD

**Issue by thijsvdanker** [Laravel-Backpack/base#14]
Using a closure for a route, as done in the login redirect: https://github.com/Laravel-Backpack/base/blob/master/src/app/Http/routes.php#L16

Breaks the possibility to compile the routes using `php artisan route:cache`.

```
[LogicException]                                                  
  Unable to prepare route [login] for serialization. Uses Closure.
```

A fix for this would be to create a controller for it that does the redirect.

**Comment by tabacitu** [comment]
I wasn't aware that happened. 
Thanks, that was a quick fix!

**Comment by thijsvdanker** [comment]
Thanks!
