### ISSUE TITLE
How to protect routes?

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/Base#140]
As a default, all users can access all admin routes. 

This is too simple, in the real world, only certain roles should be able to manage users. 

Here https://github.com/Laravel-Backpack/Base/issues/39 @chellman suggests creating a middleware that checks for a pattern in the route "admin/*"

`public function handle($request, Closure $next) { if ($request->is('admin/*')) { if (! $request->user()->hasRole('admin')) { return redirect('404'); } } return $next($request); }`

But that feels unnatural. 

Is there a way of overwriting the Admin Middleware?

`backpack2\vendor\backpack\base\src\app\Http\Middleware\Admin.php`

Or is there any other way of protecting routes with built-in permission manager?

**Comment by eduardoarandah** [comment]
I solved it with a middleware to check admin routes, like this:

Create a Middleware 

`app\Http\Middleware\AdminPermissionMiddleware.php`

```
<?php

namespace App\Http\Middleware;

use Closure;
use Auth;

class AdminPermissionMiddleware
{
    public function handle($request, Closure $next)
    {     
        //dashboard
        if ($request->is('admin/dashboard*') && !$request->user()->can('admin-dashboard')){
            abort(403);
        } 

        //articles
        if (($request->is('admin/article*')
            || $request->is('admin/category*')
            || $request->is('admin/tag*'))
            && !$request->user()->can('admin-article')){
            abort(403);
        }             

        //pages
        if ($request->is('admin/page*') && !$request->user()->can('admin-page')){
            abort(403);
        }

        //menu
        if ($request->is('admin/menu-item*') && !$request->user()->can('admin-menu')){
            abort(403);
        }   

        //users
        if (($request->is('admin/user*') 
            ||$request->is('admin/role*') 
            ||$request->is('admin/permission*') )
            && !$request->user()->can('admin-user')){
            abort(403);
        }   
        
        //backups
        if ($request->is('admin/backup*') && !$request->user()->can('admin-backup')){
            abort(403);
        }        
          
        //files
        if ($request->is('admin/elfinder*') && !$request->user()->can('admin-file')){
            abort(403);
        }      

        //log
        //don't use admin/log* because would match admin/login admin/logout
        if (($request->is('admin/log')
            || $request->is('admin/log/*'))
            && !$request->user()->can('admin-log')){
            abort(403);
        }   
        
        //setting             
        if ($request->is('admin/setting*') && !$request->user()->can('admin-setting')){
            abort(403);
        }   
                          
                    
        return $next($request);
    }
}

```

Then, in **app\Http\Kernel.php** add the middleware to web

    protected $middlewareGroups = [
        'web' => [
           ...
            //backpack admin:
            \App\Http\Middleware\AdminPermissionMiddleware::class,
        ],

    ];

Then create all the permissions in admin/permission

- admin-dashboard
- admin-article
- admin-page
- admin-menu
- admin-user
- admin-backup
- admin-file
- admin-log
- admin-setting

(optional) Create a role called "admin", **this role will have full access**

For admin, we will not check any permission, always return true. For this, add this code to 
app\Providers\AuthServiceProvider.php

```
public function boot()
    {
        $this->registerPolicies();

        //admin can do anything
        Gate::before(function ($user) {
            if ($user->hasRole("admin")) {
                return true;
            }
        });
    }
```

Finally, modify your sidebar so the forbidden actions don't appear, using the `@can` directive

Examples: 

          @can('admin-dashboard')
          <li><a href="{{ url(config('backpack.base.route_prefix').'/dashboard') }}"><i class="fa fa-dashboard"></i> <span>{{ trans('backpack::base.dashboard') }}</span></a></li>
          @endcan

          @can('admin-page')
          <li><a href="{{ url(config('backpack.base.route_prefix').'/page') }}"><i class="fa fa-file-o"></i> <span>Pages</span></a></li>
          @endcan

**Comment by tabacitu** [comment]
Hi @eduardoarandah ,

Glad you figured a way, and thanks for sharing it with everybody. I myself prefer to have a ```PermissionMiddleware``` and ```RoleMiddleware```, like [in these gist](https://gist.github.com/tabacitu/acd7929cc9f60d104da1df4c39f0dad2). For most projects, I just use the RoleMiddleware - no need for granular access. In more complex projects, I use the PermissionMiddleware. 

Inside the sidebar, I use [laravel-permission's blade directives](https://github.com/spatie/laravel-permission#using-blade-directives) ```@hasrole('superadmin')``` or just ```$user->can('edit articles');```. 

In the routes I make sure all admin routes are placed under one of these middlewares, usually in a route group:

```php
// Admin Interface Routes
Route::group(['prefix' => config('backpack.base.route_prefix', 'admin'), 'middleware' => ['role:superadmin'], 'namespace' => 'Admin'], function () {
    Route::get('dashboard', '\Backpack\Base\app\Http\Controllers\AdminController@dashboard');
    Route::get('/', '\Backpack\Base\app\Http\Controllers\AdminController@redirect');
    Route::get('logout', '\Backpack\Base\app\Http\Controllers\Auth\LoginController@logout');
    // other routes
});
```
It's not better than your way - it's just different :-) I find it simpler. Maybe it helps someone.

Cheers!

**Comment by tabacitu** [comment]
PS. Thanks A LOT for sharing you solution with the community. Cheers to you! :-)

**Comment by o15a3d4l11s2** [comment]
@tabacitu I have tried restricting the whole admin area for everyone except admins by adding

```
protected function mapAdminRoutes()
{
    Route::prefix('admin')
        ->middleware(['web', 'role:admin'])
        ->prefix(config('backpack.base.route_prefix', 'admin'))
        ->namespace($this->namespace.'\Admin')
        ->group(base_path('routes/admin.php'));
}
```

in `RouteServiceProvider.php`, but this logic works only for the additional (custom) routes that I have added in the admin area. Dashboard, base backpack routes, etc. are still accessible by everyone. Am I doing something wrong?

I saw that there are changes coming regarding the routes and access to the admin area, but I suppose it will take some time until they are released.

P.S. Thanks to the whole team for the great job!

**Comment by tabacitu** [comment]
@o15a3d4l11s2 you should be able to completely replace the Base routes by creating this file: ```routes/backpack/base.php```. You can make the same modifs there too, based on the routes file from Base.

Yes, the update has this covered :-) You'll be able to change the Admin middleware to anything you'd like. Hope we get to launch it by the end of the week. 

Cheers!

**Comment by eduardoarandah** [comment]
@o15a3d4l11s2 

Hi! Protecting routes was solved, maybe this issue should be removed to avoid confusion. 

The proper way of protecting routes is copying them to your routes and adding your middleware as you wish, examples: 

```
->middleware(['web', 'role:admin'])
->middleware(['web', 'can:edit-settings'])
```

Example commands to copy routes:

base: 
`cp vendor/backpack/base/src/routes/backpack/base.php routes/backpack/base.php`

crud:
edit permissions in config/elfinder.php

permissionmanager:
`cp vendor/backpack/permissionmanager/src/routes/backpack/permissionmanager.php routes/backpack/permissionmanager.php `

backupmanager
`cp vendor/backpack/backupmanager/src/routes/backpack/backupmanager.php routes/backpack/backupmanager.php`

and so on
