### ISSUE TITLE
recaptcha at logon

### ISSUE THREAD

**Issue by physio** [Laravel-Backpack/Base#142]
good morning, sorry for my english,
i would like to implement google recaptcha into backpack logon form. i know that i must to override the AuthController for add a request validation. where i can find the request file? 

reguards

**Comment by tabacitu** [comment]
Hi @physio ,

There's no request file, Laravel does its validation for auth inside ```AuthenticatesUsers::validateLogin()```. So just overwrite that method in your ```LoginController```.

Hope it helps.

Cheers!
