### ISSUE TITLE
Custom button in line stack not getting correct entry

### ISSUE THREAD

**Issue by osvc96** [Laravel-Backpack/Base#144]
Hello,

I have a custom button view, which I call in a crud controller like this:
![image](https://cloud.githubusercontent.com/assets/17503695/26308627/3fdaec7e-3eb7-11e7-9577-5f11e9a65258.png)

If I understand correctly, I should be able to get a specific database entry if it's in the line stack.
In the blade file, I try to get the entry's ID like this:
![image](https://cloud.githubusercontent.com/assets/17503695/26308694/787be54c-3eb7-11e7-9108-7d8c821c99b3.png)

The button itself is called with no issues.
However, when I try to use it, no matter on which entry, the ID it gets is always the last entry's ID (not necessarily the bottom row, but the last entry that was created). Any idea of what is happening here?

**Comment by lloy0076** [comment]
I was just recently using this functionality and it works for me.

What if you put `{{ $entry }}` after the `export</button>`? Do you see the entry you expect?

**Comment by tabacitu** [comment]
Also tested this and can confirm it's working properly, so I'll close the issue. 

@osvc96  - isn't it possible that your ```generateReport()``` needs you to pass the id as a parameter? To see if it's a PHP or a JS problem, do as @lloy0076 said and dump the id in the button label - just to make sure. My bet is on JS.

Cheers!
