### ISSUE TITLE
addColumn relationship (bug?)

### ISSUE THREAD

**Issue by abix5** [Laravel-Backpack/Base#145]
**DB** 
**patches ->** id,name,runame
**modules ->** id, module_id,salt,desc,path

App\Model\Patch 
```
    public function modules(){
        return $this->belongsTo(Module::class);
    }
```

App\Model\Module
```
    public function patches(){
        return $this->hasMany(Patch::class);
    }
```

////// it's WORK //////
```
$this->crud->addField([  // Select
            'label' => trans('patch.module_id'),
            'type' => 'select2',
            'name' => 'module_id', // the db column for the foreign key
            'entity' => 'modules', // the method that defines the relationship in your Model
            'attribute' => 'runame', // foreign key attribute that is shown to user
            'model' => "App\Models\Module" // foreign key model
        ]);
```

debugbar query -> select * from `patches` where `patches`.`id` = '1' limit 1
/////////

**/////// Don't WORK ///////**
```
$this->crud->addColumn([  // Select
            'label' => trans('patch.module_id'),
            'type' => 'select',
            'name' => 'module_id', // the db column for the foreign key
            'entity' => 'modules', // the method that defines the relationship in your Model
            'attribute' => 'runame', // foreign key attribute that is shown to user
            'model' => "App\Models\Module" // foreign key model
        ]);
```

debugbar query -> select * from `modules` where `modules`.`id` in ('0')
///////////

What I'm doing wrong? Why ID sent = 0

**Comment by tabacitu** [comment]
Hi @abix5,

What was your issue amd solution? Could be useful for others that have the same problem and search.

Thanks, cheers!

**Comment by abix5** [comment]
Hi. I have a problem with the display of columns (CRUD). I want to display not the id module, and to display the name.
![screenshot at 23 10-20-17](https://cloud.githubusercontent.com/assets/6427182/26342643/89ce77e8-3fa1-11e7-828b-867dc0797b87.png)

**Comment by lloy0076** [comment]
@tabacitu @abix5 - working with @abix5 in the gitter channel it turned out that Laravel was "guessing" the wrong relationship IDs.

Advised @abix5 to "always" specify relationship IDs even if Laravel usually gets them right.

(It was selecting the ID of the foreign table RATHER THAN the foreign key column)

**Comment by tabacitu** [comment]
Sounds like pretty good collaboration right there :-) Very glad to hear that.
I'll close the issue.
