### ISSUE TITLE
Where can I control after registration

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/Base#146]
When I register a user, it automatically logged in and shows the dashboard. 

I don't want a user to log in automatically. I added `Auth::logout()` in app/HttpControllers/Auth/RegisterController.php but a new user is still logged in.

**Comment by lloy0076** [comment]
Automatically logging in is a Laravel default - Backpack doesn't really suggest changing Laravel's default behaviour apart from suggesting a new e-mail template to send the user to the Backpack based reset route.

You could try overriding the `public function authenticate(Request $request) {}` and log them back out there.

**Comment by shinokada** [comment]
Is it `Illuminate\Broadcasting\BroadcastController`? I could not find any other.

**Comment by lloy0076** [comment]
You want to override the `authenticated(Request $request)` method.

See maybe https://blog.damirmiladinov.com/laravel/laravel-5.2-email-verification-with-activation-code.html?
