### ISSUE TITLE
Upgrading backpack packages

### ISSUE THREAD

**Issue by alexkb** [Laravel-Backpack/Base#147]
I recently upgraded Laravel to 5.4 and followed the very well written [Laravel 5.3 to 5.4 upgrade guide](https://laravel.com/docs/5.4/upgrade).

My question is, when upgrading Backpack (Base, Crud, etc), what commands are required as it seems the commands to publishing the backpack configs and templates won't work unless you remove them again. I'm wondering if there any other steps involved as it doesn't seem trivial to me.

**Comment by lloy0076** [comment]
```
λ php artisan help vendor:publish
Usage:
  vendor:publish [options]

Options:
      --force                Overwrite any existing files.
      --provider[=PROVIDER]  The service provider that has assets you want to publish.
      --tag[=TAG]            One or many tags that have assets you want to publish. (multiple values allowed)
  -h, --help                 Display this help message
  -q, --quiet                Do not output any message
  -V, --version              Display this application version
      --ansi                 Force ANSI output
      --no-ansi              Disable ANSI output
  -n, --no-interaction       Do not ask any interactive question
      --env[=ENV]            The environment the command should run under
  -v|vv|vvv, --verbose       Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Publish any publishable assets from vendor packages
```

You can FORCE override the templates (and configuration files etc).

However if you have changed stuff then you'll need to take some sort of steps to keep your changes (or merge them).
