### ISSUE TITLE
Cannot use asset into base.php configuration file

### ISSUE THREAD

**Issue by hubertokf** [Laravel-Backpack/Base#150]
When I try to usei asset() function into base.php, artisan stops working giving this message

[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null
  given, called in .../vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on l
  ine 64

I'm trying to insert image on logo_lg.

**Comment by tabacitu** [comment]
Hi @hubertokf - I don't think you can do that in Laravel. I bet the helpers (like ```asset()```) are loaded long after the configs. I think your best bet is to do that change in your ```resources/views/backpack/base/layout.blade.php```.

Hope it helps. Cheers!

**Comment by AurelDragut** [comment]
I just made a test on this and 
```
'logo_lg'   => '<img src="'.asset('img/photo.jpg').'" style="width:100%" />',
```
seems to be working

**Comment by hubertokf** [comment]
@AurelDragut Yes, it works, but have you tested artisan commands?

**Comment by AurelDragut** [comment]
Oh, my bad, missed the part with the artisan thing. Yeah, i get the same error.
