### ISSUE TITLE
Command line scaffolder generating empty modal

### ISSUE THREAD

**Issue by jkirkby91-2** [Laravel-Backpack/Base#153]
Following your guide on how to 'do it all fast' with the command line

php artisan make:migration:schema create_tags_table --schema="name:string:unique" --model=0
php artisan migrate
php artisan backpack:crud tag
 CRUD::resource('tag', 'TagCrudController');

When i do this all the files generated have none of the attributes ive added.

Using the latest versions of all

**Comment by tabacitu** [comment]
Hi @jkirkby91-2 ,

Yup, you need to add the attributes manually right now. Fully-prewritten generated models are planned, but might take some time to develop.

Cheers!
