### ISSUE TITLE
Object doesn't support property or method 'startsWith' - From our beloved IE

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/Base#154]
Found this in IE11, all other FF, Chrome and even Edge are fine.

![2017-06-09 001609](https://user-images.githubusercontent.com/26375917/26961766-79cbc298-4d0b-11e7-9947-76ed1c2b34fb.png)

![2017-06-09 001608](https://user-images.githubusercontent.com/26375917/26961769-7dc1dec8-4d0b-11e7-9258-f02784fc82c9.png)

**Comment by tabacitu** [comment]
Pfff... Microsoft, huh? Looks like [IE11 does NOT support ES6 yet](https://stackoverflow.com/questions/30867172/code-not-running-in-ie-11-works-fine-in-chrome). 

Does this fix it for you?

```
if (!String.prototype.startsWith) {
  String.prototype.startsWith = function(searchString, position) {
    position = position || 0;
    return this.indexOf(searchString, position) === position;
  };
}
```

**Comment by MickaelTH** [comment]
Thanks for looking at this.

Yes, we should go back in time and avoid having microsoft released IE 1.0. But we are where we are...

How can I test this snippet? (which files it supposes to be saved to)

**Comment by MickaelTH** [comment]
I cannot reproduce the issue - weird. The code was inchanged:

`// Set active state on menu element
var current_url = "{{ Request::url() }}";
$("ul.sidebar-menu li a").each(function() {
  if ($(this).attr('href').startsWith(current_url) || current_url.startsWith($(this).attr('href')))
  {
    $(this).parents('li').addClass('active');
  }
});`

But now IE 11 is not showing the issue, maybe they did an update recently. Closing the issue thank you.

**Comment by tabacitu** [comment]
Don't you just love bugs that fix themselves? :-)
