### ISSUE TITLE
Simple filter activated by tab script

### ISSUE THREAD

**Issue by plantravels** [Laravel-Backpack/Base#155]
I have declared a simple filter on one of my lists and I noticed that it is active by default.
After much headache :) I found the following code which seems to make my filter active (on display only).

```javascript
//layout.blade.php:135
activeTab && activeTab.tab('show');
```
Details:

```javascript
        "backpack/base": "^0.7.19",
        "backpack/crud": "^3.2.12",
```

```javascript
        //add the filter
        $this->crud->addFilter([ // watch list filter
            'type' => 'simple',
            'name' => 'watch',
            'label'=> 'Watch List'
            ],
            false,
            function() {
                $this->crud->addClause('watch');
            }
        );
```

When the list page is first loaded:

<img width="543" alt="screen shot 2017-06-09 at 3 57 29 pm" src="https://user-images.githubusercontent.com/21236010/26971832-98a80796-4d2c-11e7-82ea-68a8945056e5.png">

Problem Script:

```javascript
        {{-- Enable deep link to tab --}}
        var activeTab = $('[href="' + location.hash.replace("#", "#tab_") + '"]');
        activeTab && activeTab.tab('show');
        $('.nav-tabs a').on('shown.bs.tab', function (e) {
            location.hash = e.target.hash.replace("#tab_", "#");
        });
```

**Comment by parabellumKoval** [comment]
I also just found this error.
Adding `location.hash && activeTab && activeTab.tab('show');` solved this issue.

**Comment by tabacitu** [comment]
Hi guys,

I see this has been fixed for a while now: https://github.com/Laravel-Backpack/Base/blob/master/src/resources/views/layout.blade.php#L161

Just that the issue hasn't been closed. Closing it now. Thanks for the bug report, really appreciate you providing the solution.

Cheers!
