### ISSUE TITLE
dashboard customization 

### ISSUE THREAD

**Issue by warisarain** [Laravel-Backpack/Base#157]
Hi there, 
I just wanted to add some icon on to the dashboard home page which is blank, 
I tried to add it in dashboard.blade.php file but not displaying.
how can I do this? 
I was readying some post that add new dashboard controller but I already using laravelbackpack CRUD so if I am adding new one I might lost them. Please help me to do this
Thanks

**Comment by lloy0076** [comment]
On the assumption you've followed the [instructions](https://laravel-backpack.readme.io/docs/install-on-laravel-54#section-2-install-backpackbase} that state:

```
php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider" #publishes configs, langs, views and AdminLTE files
```

The file to edit is in:

```
resources/views/vendor/backpack/base/dashboard.blade.php
```

The file, for me, currently looks like:

```
  1 @extends('backpack::layout')
  2
  3 @section('header')
  4     <section class="content-header">
  5       <h1>
  6         {{ trans('backpack::base.dashboard') }}<small>{{ trans('backpack::base.first_page_you_see') }}</small>
  7       </h1>
  8       <ol class="breadcrumb">
  9         <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
 10         <li class="active">{{ trans('backpack::base.dashboard') }}</li>
 11       </ol>
 12     </section>
 13 @endsection
 14
 15
 16 @section('content')
 17     <div class="row">
 18         <div class="col-md-12">
 19             <div class="box box-default">
 20                 <div class="box-header with-border">
 21                     <div class="box-title">{{ trans('backpack::base.login_status') }}</div>
 22                 </div>
 23
 24                 <div class="box-body">{{ trans('backpack::base.logged_in') }}</div>
 25             </div>
 26         </div>
 27     </div>
 28 @endsection
```

(without the line numbers).

Editing that file *should* work, however if it doesn't:

1. Make sure you've tried `php artisan clear:cache`
2. Use some other browser to test and/or ensure you've cleared the cache in your browser upon refresh
    * IE and MS Edge, as far as I can tell, cache pages using their own bizarre algorithms rather than anything sensible

**Comment by warisarain** [comment]
Oh Wao! Thank you Sir @lloy0076  
I just cleared cache, and remove from browser too.

Thank you once again

**Comment by lloy0076** [comment]
I assume this was fixed; if not please feel free to re-open it :)

**Comment by warisarain** [comment]
fixed sir thanks @lloy0076

**Comment by gsc89** [comment]
@lloy0076 

I found this file pretty quick but my question is how can you pass variables to this view file where is it called from?

**Comment by sokvebolkol** [comment]
Hi there, 
My problem is that I can't return to my view!
I just want to replace default view in backpackers. I have created file named dashboard.blade.php by following @lloy0076 instructed. 
I don't want to push data from AdminController . I want to create own view and do what I want.

Here is my AdminController:
-----------------------
<?php

namespace Backpack\CRUD\app\Http\Controllers;

use Illuminate\Routing\Controller;

class AdminController extends Controller
{
    protected $data = []; // the information we send to the view

    /**
     * Create a new controller instance.
     */
    public function __construct()
    {
        $this->middleware(backpack_middleware());
    }

    /**
     * Show the admin dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function dashboard()
    {
        $this->data['title'] = trans('backpack::base.dashboard'); // set the page title
        return view(backpack_view('dashboard'), $this->data);// I want to return my own view
    }

    /**
     * Redirect to the dashboard.
     *
     * @return \Illuminate\Routing\Redirector|\Illuminate\Http\RedirectResponse
     */
    public function redirect()
    {
        // The '/admin' route is not to be used as a page, because it breaks the menu's active state.
        return redirect(backpack_url('dashboard'));
    }
}
