### ISSUE TITLE
Entrust

### ISSUE THREAD

**Issue by packytagliaferro** [Laravel-Backpack/Base#158]
I have a current website using Entrust for roles/permissions. As opposed to building my own custom admin I was going to buy backpack but can I use Entrust with it? Basically so users sign in and see the web app but a user with a role of admin can login into the backpack admin panel????

thanks

**Comment by lloy0076** [comment]
You can create any middleware to protect Backpack (or any other) routes; given you don't specify which package you are using, I can't be more specific than that.

You might see:

* https://github.com/zizaco/entrust#middleware

**Comment by AbbyJanke** [comment]
There is also one already mixed into backpack if you wanted (https://github.com/Laravel-Backpack/PermissionManager)

It uses `spatie/laravel-permission`
