### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by bouffekai** [Laravel-Backpack/Base#162]
Hello,

How can I redirect the user to my website reset password view/controller instead of my backpack panel reset password view ? (I'm on Laravel 5.3) 
<myurl>/password/reset/<token> **instead of** <myurl>/admin/dashboard/password/resest/<token>

If it's not possible, how can I redirect to another view after resetting my password successfully ?

Thank you in advance for your help !

Jérémy

**Comment by lloy0076** [comment]
Override the `showResetForm` in `app/Http/Controllers/Auth/ResetPasswordController.php` if it's there (this is for L5.4 but I think 5.3 is similar).

**Comment by bouffekai** [comment]
I tried :  

`public function showResetForm(Request $request, $token = null)
    {
        return view('/profile')->with(
            ['token' => $token]
        );
    }`

But it doesn't work...It still redirect to /admin/dashboard
Any idea ? (/profile is not in admin)

**Comment by bouffekai** [comment]
Anyone ?

**Comment by tabacitu** [comment]
Hi @bouffekai ,

Remember to also point your reset password route to YOUR controller, instead of the Backpack one. I bet that's what was missing ;-)

Cheers!
