### ISSUE TITLE
ldap authentication

### ISSUE THREAD

**Issue by bahman2216** [Laravel-Backpack/Base#167]
Im using [adldap](https://github.com/Adldap2/Adldap2-Laravel) package to authenticate users via LDAP server.
I logged in via:
`Adldap::auth()->attempt($username, $password)`

It returns true but when visit **/admin/dashboard** it redirects to login page again.

Need any change for middllware or something else?

**Comment by tabacitu** [comment]
Hi @bahman2216 ,

Yes, Backpack\Base uses the "admin" middleware, which is an extension of Auth. Adldap probably has its own middleware, so make sure you use that one. You'll notice AdminController uses the "admin" middleware, so you'll probably need to [overwrite the base routes](https://github.com/Laravel-Backpack/Base#overwriting-functionality) and direct to your own AdminController.

Cheers!
