### ISSUE TITLE
Security issue / data leakage of usernames

### ISSUE THREAD

**Issue by kruisdraad** [Laravel-Backpack/Base#168]
File views/vendor/backpack/base/inc/sidebar.blade.php
snippet:
`<img src="https://placehold.it/160x160/00a65a/ffffff/&text={{ mb_substr(Auth::user()->name, 0, 1) }}" class="img-circle" alt="User Image">`

All good and fine, but this leaks all the names of people to Placehold. in my opinion both a security as privacy issue.

**Comment by victorlap** [comment]
You mean it leaks there initial? Because it is only one letter that is send to Placehold..

**Comment by tabacitu** [comment]
Hi @kruisdraad ,

As @victorlap mentions, it's only one letter, so I don't think we need to worry about this. Not a leakage. In any case, this is "fixed" in [the upcoming version](https://github.com/Laravel-Backpack/Base/pull/137), where we pick up the gravatar if it exists. Don't know if we'll keep the gravatar feature, though :-)

Cheers!
