### ISSUE TITLE
[Feature] Ability to create/use different HTML themes

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#174]
**Epiphany:** Backpack uses the views in ```resources/views/vendor/backpack/base/``` just because that's what's mapped to the ```backpack``` namespace.

So I imagine a theme system where you can:
- install a new theme as a composer package
  - that package would be a fork of the original ```Backpack\Base``` or ```Backpack\Theme``` and either use AdminLTE to start with, or provide support for the AdminLTE HTML blocks (and Bootstrap), so that every other package does NOT need modified views; it should guarantee everything will still look pretty;
- change the ```backpack``` namespace mapping; either in the ServiceProvider or in a config file;
- done, your project will look all different;

This should allow massive customizations to the ones who prefer their panel to look a certain way, but have so far done it for each project; they'd be able to create a theme and re-use it; and others to use it aswell.

Any feedback? Has anybody else been hit by this problem, is it a real issue or is it just a "_nice to have_"?

**Comment by lloy0076** [comment]
That's not changing the theme - that's a wholesale "make your own sidebar, include files, layouts etc etc".

**Comment by tabacitu** [comment]
@lloy0076 - well it could (and should) look completely different.

For example, I have projects where I've used the [Pages theme](http://pages.revox.io/). Or [Inspinia](https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S). Or others. And I would prefer to build something re-usable whenever I do, so everybody else could use them. And I would LOVE to have others build "themes", that I could use in my next projects, without having to code them myself :-)

**Comment by lloy0076** [comment]
@tabacitu - I don't necessarily disagree with what you are saying but I am more commenting on the resources to fix bugs, make new features, enhance current features ... or allow people to change the look and feel.

Consider me the Devil's Advocate asking whether it is worth spending a lot of resources on and wondering just how much it might change or how many bugs/enhancements won't get fixed instead (i.e. the opportunity cost).

**Comment by monocidar** [comment]
@tabacitu - It would be perfect if you'd publish Backpack with Pages theme and Backpack with Inspinia theme as different options to AdminLTE.

**Comment by ricardov03** [comment]
Hi everyone, and thanks a lot @tabacitu for this iniciative. I'm brand new on Backpack but I really like it. I can't wait to make a contribution for the project. About this feature, can I use other front-end framework for my solution. I'm usually use [UIKit](https://getuikit.com/) from [YOOtheme](http://yootheme.com/) instead Bootstrap for my projects. I would like to recreated an alternative UIKit backend version that can be changed from the administration. Can this help like an alternative theme?

**Comment by lloy0076** [comment]
@ricardov03 - you'll find that the base admin theme (the three AdminLTE) is heavily oriented towards bootstrap. In addition, the pre-built fields all assume the base theme and hence bootstrap.

It might be possible to do what you mention depending on the changes that @tabacitu intends to make - technically, one could rearchitect the whole thing to use a "view" strategy and have one or two officially supported strategies.

That said, having more than one supported UI toolkit may or almost *certainly* will involve more issues/bugs and oddities; Backpack would need to carefully choose which themes were officially supported and also manage the expectations of those using themes/things not officially supported.

**Comment by ricardov03** [comment]
@lloy0076 Thanks so much for your observations. I'm understand that you are viewing everything from a global perspective that give the best for the project.

I agree that Backpack need to be carefully in the UI toolkit selection from the maintenance perspective, and for this reason I understand now that UIKit it's not a good choise, maybe right now, for the project.

I'm still learning about the Backpack structure. I'm starting a personal project with it for be ready to apport. I'm really new on collaboration, so I hope you have patience to me.

**Comment by tabacitu** [comment]
@lloy0076 , thanks a lot for being the devil's advocate on this one. I think you're totally right. Providing theme support at this stage would just be inviting more front-end bugs and issues. So until we rewrite the fields, columns and everything, theming should NOT be a priority.

One middle ground I do see now is providing alternative HTML themes, that all start from AdminLTE. This would change the look&feel, but not the code. So win-win. I'll think more about that and get back to you. But in the meantime, thanks for keeping me in check - themes are NOT a requested feature, NOT important, and NOT urgent :-) So let's drop this until the next major Backpack version.

Cheers!

**Comment by tabacitu** [comment]
@ricardov03 it doesn't look like we'll be supporting anything other than Bootstrap in the near future, unfortunately. We might do that when themes roll around, but not now - there's just too much front-end to carry in two/three different flavours. Hope you understand. Cheers!

**Comment by ricardov03** [comment]
@tabacitu Thanks so much for take the time to respond. I'm completely agree with you. I'm trying to strong my knowledge on Backpack to help in other issues. Regards!
