### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#175]
This might be a good starting point: https://github.com/dwightwatson/laravel-auth-tests

After all, that's 90% of what base does.

**Comment by bloggervista** [comment]
Yes we can use them easily in this package . Just need to do around 10-15 minutes work.

**Comment by ankitjain28may** [comment]
I would like to work on this issue and we can use [Laravel/dusk](https://github.com/laravel/dusk). If no one is working on this issue, can you please assign this to me.

**Comment by lloy0076** [comment]
@ankitjain28may - feel free to take a fork of this and work on it - for the life of me I cannot figure out how I might be able to assign this to you.

@tabacitu - are you able to help out here?

**Comment by tabacitu** [comment]
Totally agree. @ankitjain28may - consider yourself assigned. I'm afraid GitHub won't let me actually do it :-)
