### ISSUE TITLE
Laravel 5.5 Installation - composer require backpack/crud bug

### ISSUE THREAD

**Issue by ahinkle** [Laravel-Backpack/Base#178]
Followed the guide at https://laravel-backpack.readme.io/v3.0/docs/install-on-laravel-55.

I get the following error when I try: `composer require backpack/crud`

Error:

```
> @php artisan package:discover


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Foundation\Application::bindShared()


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

```

**Comment by shadowbane** [comment]
If you look at the logs, you will see that this is because of incompatibility with laravelcollective/html packages. I tried using dev-master, but it's not compatible with illuminate/view and other packages. I think it's best to wait for latest release from laravelcollective/html.

[laravelcollective/html Issue #411](https://github.com/LaravelCollective/html/issues/411)

**Comment by tabacitu** [comment]
Hi @ahinkle , @shadowbane .

That's odd - [it installs for me just fine](https://cl.ly/0v0w3S420S2I)... Does anybody else get this error?

**Comment by shadowbane** [comment]
Ah, I should've posted it in Laravel-Backpack/CRUD..

anyways, it's the same with [this one](https://github.com/Laravel-Backpack/CRUD/issues/907)

**Comment by djgoulart** [comment]
@tabacitu I have the same error here. This occurred when I tried to install the crud package.

**Comment by lloy0076** [comment]
I've installed a number of times where 2 < N < 10 and not seen this yet.

**Comment by tabacitu** [comment]
I've just installed Backpack on L5.5 again, so I can't find a way to replicate your problems. This should mean everything's fine and it's user error, so I'll close this issue, even if we keep talking here.

@djgoulart , @shadowbane , could any of you guys please provide your ```composer.json``` and a screenshot of the output when your run ```composer install```? This should help us understand what's going on.

Cheers!

**Comment by mandahylla** [comment]
Hello @tabacitu,
i'm try to install backpack on laravel 5.4 but I'm stuck at this step : 3. Install Backpack\CRUD
when i run on terminal "php composer.phar require backpack/crud" i got this error : 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - backpack/crud 3.4.4 requires backpack/base ^0.9.0 -> satisfiable by backpack/base[0.9.0, 0.9.1, 0.9.2] but these conflict with your requirements or minimum-stability.
    - backpack/crud 3.4.3 requires backpack/base ^0.9.0 -> satisfiable by backpack/base[0.9.0, 0.9.1, 0.9.2] but these conflict with your requirements or minimum-stability.
    - backpack/crud 3.4.2 requires backpack/base ^0.9.0 -> satisfiable by backpack/base[0.9.0, 0.9.1, 0.9.2] but these conflict with your requirements or minimum-stability.
    - backpack/crud 3.4.1 requires backpack/base ^0.9.0 -> satisfiable by backpack/base[0.9.0, 0.9.1, 0.9.2] but these conflict with your requirements or minimum-stability.
    - backpack/crud 3.4.0 requires backpack/base ^0.9.0 -> satisfiable by backpack/base[0.9.0, 0.9.1, 0.9.2] but these conflict with your requirements or minimum-stability.
    - Installation request for backpack/crud ^3.4 -> satisfiable by backpack/crud[3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4].
Help please
