### ISSUE TITLE
Button color with other skin

### ISSUE THREAD

**Issue by welcoMattic** [Laravel-Backpack/base#18]
When I change the AdminLTE skin (I set it to blue), the header is set to the good color, but all buttons still purple.

![screenshot](https://i.imgur.com/DyqJz6h.png)

**Comment by tabacitu** [comment]
You're right. Thanks!

**Comment by tabacitu** [comment]
You might want to republish your assets, or just see the modifications here and do them in your published backpack.base.css if you've already modified it.

**Comment by danielbidala** [comment]
Hi @tabacitu 

Sorry but I have the same issue and not understand what to do exactly. 

I republished my assets with `php artisan backpack:base:install` after I deleted `adminlte` and `backpack` folder in my `public/vendor` folder.

Or do I have to modify my backpack.base.css manually?
