### ISSUE TITLE
Languages not loading in Homestead

### ISSUE THREAD

**Issue by TheWildHorse** [Laravel-Backpack/Base#180]
Hey,
I just installed the backpack Base and CRUD modules but the language for the base is not loaded. CRUD publishes its languages to the lang directory, but the base file is not pushed (because of the symlink approach that was taken in april?).

Anyways, when I load the login page all I get are the lang string names and no actual translation. Using base@0.7.25.

**Comment by PortStone** [comment]
For me it doesn't publish lang files. 

php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider" #publishes configs, langs, views and AdminLTE files
Copied Directory [\vendor\backpack\base\src\config] To [\config]
Copied Directory [\vendor\backpack\base\src\resources\views] To [\resources\view
s\vendor\backpack\base]
Copied Directory [\vendor\backpack\base\src\resources\error_views] To [\resource
s\views\errors]
Copied Directory [\vendor\backpack\base\src\public] To [\public\vendor\backpack]

Copied Directory [\vendor\almasaeed2010\adminlte] To [\public\vendor\adminlte]
Publishing complete.

But I've got resources/lang/vendor/backpack/en and so on. But without base,php. 

I am using XAMPP

**Comment by lloy0076** [comment]
If this is still an issue, pleas reopen.
