### ISSUE TITLE
Laravel 5.5: Class active does not exist

### ISSUE THREAD

**Issue by bladegh** [Laravel-Backpack/Base#186]
Hello, 

everytime I want to register a new User or want to login this error appears.

It says, that in vendor\laravel\framework\src\Illuminate\Container\Container.php the class is missing, but I don't know what should be in that class so that i declare it myself.

**Comment by tabacitu** [comment]
Hi @bladegh ,

Doesn't sounds like a Backpack issue - must be something from the customizations.

Cheers!
