### ISSUE TITLE
These toggle tabs doesn't work when i close all the tabs

### ISSUE THREAD

**Issue by ankitjain28may** [Laravel-Backpack/Base#187]
As shown below, i close all the tabs, now they are not getting open on click.

![image](https://user-images.githubusercontent.com/14014254/30680063-3a24a3ec-9ebb-11e7-9627-9853e0d50a3a.png)

**Comment by lloy0076** [comment]
Do you have ny logs from the dev tools (or `storage/log/laravel.log` but I think this is most likely to show up in the dev tools)?

**Comment by pxpm** [comment]
@lloy0076  I think he's talking about tabs on docs page.

**Comment by lloy0076** [comment]
Unable to reproduce. Please reopen if needed.

**Comment by yaim** [comment]
This issue is about the product introduction website (backpackforlaravel.com), not the product itself.
(seems mr.accordions.activatePanel in script.js is buggy)
@tabacitu close issue?

**Comment by tabacitu** [comment]
Yup, thank you @yaim . But thank you @ankitjain28may for reporting, it's since been fixed. Cheers!
