### ISSUE TITLE
Can't remove the middleware from a route

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/Base#193]
I don't know if I am maybe wrong but I can't remove the middleware 'admin' from a custom route:

In the _MonsterCrudController_ I wrote __construct() method
```
public function __construct()
{
    parent::__construct();
    $this->middleware('admin', ['except' => ['myMethodInTheMonsterCrudController']]);
}
```

and in admin.php route file I have
```
Route::get('monster/{id}/accept', 'MonsterCrudController@myMethodInTheMonsterCrudController');
```

I'm using Laravel 5.5, but I used to do always like above and has always worked, there's something that override this?

**Comment by tabacitu** [comment]
Hi @EmanueleCoppola ,

I believe the change has come in Laravel 5.4 - the time the middleware is run has changed in Laravel, so you can no longer do that in ```__construct()```. You should, however, be able to do that in the ```setup()``` method.

Cheers!

**Comment by AdolphYu** [comment]
Where do you use setup

**Comment by tabacitu** [comment]
@AdolphYu in your EntityCrudController, where "Entity" is whatever model you're building a CRUD for.
