### ISSUE TITLE
Activate or Deactivate User

### ISSUE THREAD

**Issue by CHOMNANP** [Laravel-Backpack/Base#194]
Backpack is very nice tool. I love using it.

Anyway, is there any activate or deactivate user account in Backpack?
If I would like to create a new function to deactivate account, I do need to modify "Login" as well.
Any recommendation how can I achieve on "Activate/Deactive User" with Laravel Backpack?

Thanks,
Punleu

**Comment by lloy0076** [comment]
Laravel Backpack has very little opinion on authentication and what opinion it does is mainly cosmetic.

You'd want to figure out:

1. How you'd do what you want to do in a plain Laravel application;
2. How to integrate that with Backpack.

https://laravel.com/docs/5.5/authentication will help with (1) - the Backpack integration is fairly simple once you've done (1).
