### ISSUE TITLE
Contributing to the Docs

### ISSUE THREAD

**Issue by voidstate** [Laravel-Backpack/Base#195]
The docs for column types don't mention any of the following:

- date
- datetime

I had to dig into the source to see they were available. I also looked for somewhere to contribute a PR with them added but couldn't see a repo for the docs.

Can someone add a reference to these?

Thanks

**Comment by lloy0076** [comment]
@voidstate - the docs live at `readme.io` at the moment (as you probably know) and that isn't backed by a repository system, although I'm assured if one has access to the docs, it's all versioned, easily accessible and so forth.

We've started a discussion on how best to facilitate others to contribute to them and hopefully we'll have something soon.

**Comment by tabacitu** [comment]
Hi @voidstate ,

Thanks for the heads-up. I just added those two columns to the docs. readme.io does provide a way for anyone to edit (see top-right Suggest Edit button), but in the future we plan to migrate the docs to a github repo, to make it even easier to edit.

Cheers!

![screen shot 2017-12-02 at 09 30 43](https://user-images.githubusercontent.com/1032474/33513038-d0381092-d743-11e7-8d4a-aff745910b87.png)
