### ISSUE TITLE
Alerts system

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/base#2]
Decide upon an use an alert system, so bubble notifications can be triggered in any BackPack package, both from PHP and from JS.

**Comment by dobromir-hristov** [comment]
I used jqNoty with Laracasts/Flash plugin. Works like a charm.

**Comment by tabacitu** [comment]
@dobromir-hristov , https://github.com/laracasts/flash looks great and I love Jeffrey Way, but I do see one problem with it: it provides no way to trigger alerts on the same controller/page (without flash session storage, just plain session).

So it handles:
```
Flash::error('no way');
return Redirect::home();
```

But it can't do:
```
Flash::error("Missing subscriber info. Still showing page.")->currentPage();
return view("page");
```

I did find myself using that in Dick, so I'd like Backpack to have it too. Is there any way to do that in Flash and I missed it?
