### ISSUE TITLE
Bugs for fresh install backpack base ^=^

### ISSUE THREAD

**Issue by MDEvo** [Laravel-Backpack/Base#200]
# Bug report

On fresh install Laravel 5.5 when run 

`composer require backpack/base`

will throw this error:
```
  [ReflectionException]
  Class Backpack\Base\Backpack\Base\app\Console\Commands\Install does not exist
```

There is repetition:

> Backpack\Base\Backpack\Base\app\Console\Commands\Install should be Backpack\Base\app\Console\Commands\Install

**Comment by MDEvo** [comment]
Solved by changing:

> protected $commands = [
>         \Backpack\Base\app\Console\Commands\Install::class,
> ];

 on BaseServiceProvider.php

**Comment by fhusquinet** [comment]
Same issue with Laravel 5.5, looks like the command has the namespace automatically prepending to it throwing the exception.

**Comment by xcerx** [comment]
@fhusquinet you can work around by fix Backpack\Base\BaseServiceProvider.php

from ...
```php
protected $commands = [
        Backpack\Base\app\Console\Commands\Install::class,
    ];
```

to ...
```php
protected $commands = [
        app\Console\Commands\Install::class,
    ];
```

**Comment by lloy0076** [comment]
@tabacitu There's various iterations of this floating about - you have any idea of what these are?

**Comment by tabacitu** [comment]
Hi guys, this has been fixed in a matter of hours, but I didn't get to see this issue too. I've just tested the installation of the current version and it works fine, so I'll close the issue.

Please reopen the issue if you're still having this problem.

Cheers!
