### ISSUE TITLE
Registration controller override

### ISSUE THREAD

**Issue by ftorresws** [Laravel-Backpack/Base#205]
How can we add a field to the registration process? I added the field to the form, the database and our User model. But, I haven't found how to override the Backpack RegisterController to include the new field. So, when I register a user, the field isn't inserted into the database.

How can I override the Backpack RegisterController? Maybe there's a better way to do this. I need the user to have address and phone number fields during registration.

Thanks for your help.

**Comment by lloy0076** [comment]
You'd have to override the default registration controller to do this in any case AND it's no different than doing this for any other Laravel application; you'd need to:

1. Find the relevant views and publish them (IIRC they should be in `resources/vendor/backpack/` somewhere and named obviously, i.e. have 'registration'  in their name;
2. Adjust them;
3. Configure backpack to not intercept the auth and such.

I tend to take the registration and logic back from Backpack most of the time unless I really do need something as simle as Laravel's default registration.

**Comment by ftorresws** [comment]
Thank you. I'll follow that approach.
