### ISSUE TITLE
Error in documentation "Upgrading CRUD 3.2 to 3.3"

### ISSUE THREAD

**Issue by cerelli** [Laravel-Backpack/Base#211]
There is an error in the documentation in the "Upgrading CRUD 3.2 to 3.3" page:
`make the following changes to your resources/views/backpack/base/sidebar.blade.php;`
`resources/views/backpack/base/sidebar.blade.php` not exist.
Is `resources/views/backpack/base/inc/sidebar.blade.php` ?

**Comment by tabacitu** [comment]
Yes @cerelli , thank you, I've just updated the docs accordingly. Cheers!
