### ISSUE TITLE
Install command does not publish /public/adminlte files

### ISSUE THREAD

**Issue by RamiMustaklem** [Laravel-Backpack/Base#216]
`php artisan backpack:base:install` 

says it is publishing AdminLTE files but it does not:
`### publishing configs, langs, views and AdminLTE files
OUT > Publishing complete.`

I fixed it with:
`php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider"`

**Comment by lloy0076** [comment]
Verified.

**Comment by axelzuzek** [comment]
Same problem here. 
php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider"
fixed it.

**Comment by tabacitu** [comment]
Thank you for the bug report, @RamiMustaklem , @lloy0076 , @axelzuzek . I had no idea - worked fine on the server configs I tested (all MacOS though).

Just merged @seandowney 's PR, so it's fixed now. It'll be available with a ```composer update``` by the end of the day.

Cheers!

**Comment by MohammedAlzard** [comment]
run this
 php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider"
