### ISSUE TITLE
Backpack without styling!!

### ISSUE THREAD

**Issue by OmarAlesharie** [Laravel-Backpack/Base#219]
![backpack no css](https://user-images.githubusercontent.com/30577507/32988765-d1692528-cd1b-11e7-9b1b-a274178a6952.jpg)

Hello everyone, I'm trying to start with backpack with latest release of Laravel 5.5.21

but I don't understand why the application does not use any styling!!!

**Comment by lloy0076** [comment]
See #217,

**Comment by OmarAlesharie** [comment]
@lloy0076 
Kindly I used 
composer require backpack/generators --dev
then reinstall, still the same problem
and try with new laravel project:
composer require backpack/generators --dev and install the base
and it didn't solve the problem

**Comment by tabacitu** [comment]
@OmarAlesharie - looks like a misconfigured Laravel install to me, due to localhost server. Pretty sure the URLs for the assets are wrong.
