### ISSUE TITLE
Problem fresh install

### ISSUE THREAD

**Issue by xdasty** [Laravel-Backpack/Base#221]
# Bug report
The requested URL /admin was not found on this server.

### What I did:
I installed Laravel and BackpackBase 
I try to access mydomain/admin

### What I expected to happen:
I should go to the login page

### What happened:
The requested URL /admin was not found on this server.

### Backpack, Laravel, PHP, DB version:

"require": {
        "php": ">=7.0.0",
        "backpack/base": "^0.8.2",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.0",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "backpack/generators": "^1.1",
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "laracasts/generators": "dev-master",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    },

**Comment by tabacitu** [comment]
Hi @xdasty ,

Just tested it myself and it seems to work fine. It must mean it's been a server configuration issue - non-backpack. Did you make sure the app is working without Backpack first? If ```mydomain``` doesn't work, neither will ```mydomain/admin```.

Hope it helps.
Cheers!

**Comment by xdasty** [comment]
I try to reinstall everything, I'll make a video, maybe I'm wrong.
