### ISSUE TITLE
Publishing Adminlte assets not working in not default base_path

### ISSUE THREAD

**Issue by yoramdelangen** [Laravel-Backpack/Base#222]
I have an installation containing 2 different base_paths/app_paths. Instead of the default `app/` I have `backend/app/` and `frontend/app/` (so the base path will be set to `backend/` and `frontend/`. Both base_paths are booted correctly. But because the base path is different and one level deeper then the usual it causes problems with publishing the adminlte assets (because it is using the `base_path()` function).

Easly to reproduce is setting the base_path to `backend/app` and running the command:
`php artisan vendor:publish --tag=adminlte`

Fixed it for now temporary by removing the `base_path()` function and calculate the path from current directory. In this way its more accurate thats in the vendor directory instead of the `base_path()` function.

Code for pull request to fix:
```
// calculate the path from current directory to get the vendor path
$vendorPath = __DIR__.'/../../..';

// publish public AdminLTE assets
$this->publishes([$vendorPath.'/almasaeed2010/adminlte' => public_path('vendor/adminlte')], 'adminlte');

// publish public Gravatar assets
$this->publishes([$vendorPath.'/creativeorange/gravatar/config' => config_path()], 'gravatar');
```

Latest Backpack, Laravel 5.5.21, PHP 7.1.8

**Comment by tabacitu** [comment]
Closing this - I believe this fixes it https://github.com/Laravel-Backpack/Base/pull/223 - someone was very kind to submit a PR for it :-)

Thanks, cheers!
