### ISSUE TITLE
Running a middleware on the Dashboard

### ISSUE THREAD

**Issue by xJoeyv** [Laravel-Backpack/Base#231]
# Bug report

### What I did:
Defining a middleware and add this to the route group.

### What I expected to happen:
Is that the middleware works on does his job

### What happened:
I don't really know but it seems like the middleware doesn't work on the group

### What I've already tried to fix it:
Other middlewares, check the source-code and use multiple ways of defining a middlware to a route / route group.

### Backpack, Laravel, PHP, DB version:
Laravel 5.5.*
Laravel Backpack 0.8.3
PHP 7.2.0

**Comment by lloy0076** [comment]
Thanks for filing the **question** but given the response, I'm going to assume it is not a bug and/or something wrong witht he middleware you've written.

**Comment by xJoeyv** [comment]
@lloy0076 What is this for way of handling issues?
"Ask it on stackoverflow" I would love to have support from the developer or someone in charge or with knowledge about this package. it has nothing todo with my Middleware since it works on other routes fine. Except on this package...

What is the issue and why does the package now allow me to add a MW on the route group?

**Comment by lloy0076** [comment]
It is eminently reasonable to assume that someone could write some middleware that works on other packages except Backpack but it has something to do with this package.

You'd probably need to provide a gist of the code (or something close enough to the code if you can't give out the source code) so that whoever was answering the question might have a better chance of seeing what could be the issue.

All **I** know at the moment is that you think it has something to do with the Backpack code base (it could, I suppose), that it is some sort of middleware that does its job. You'll find me in slack quite often but there's also the gitter community which tends to be a little more active.

**Comment by xJoeyv** [comment]
While the middleware did not work so for I put in the actual code I just abort with a 403 and put that on the Group route copied from the install guide..

**Comment by alashow** [comment]
Maybe backpack is overriding your routes (if `config.backpack.base.setup_dashboard_routes = true`), and that's why your middleware isn't registering?

**Comment by alashow** [comment]
Nope, just checked, it doesn't override it even if `setup_dashboard_routes = true`, and custom route for the dashboard is set.

Can you provide your code where you define your route for the dashboard?

**Comment by xJoeyv** [comment]
I do not define anything custom. And yea I have been playing with that option but It didnt do anything.
This was a route group I had made during install cause that was required where I changed clearly the middlware on...

```
Route::group(['prefix' => 'admin', 'middleware' => 'admin.view', 'namespace' => 'Admin'], function () {
    CRUD::resource('article', 'ArticleCrudController');
    CRUD::resource('category', 'CategoryCrudController');
});
```

and the middleware it self isn't intresting is now only a abort to check if it is working

**Comment by lloy0076** [comment]
It would help to see the code.

**Comment by xJoeyv** [comment]
@lloy0076 Wich code? Middleware is as I said only...

```abort(403);```
In the mw made via ```php artisan make:middleware```

That because I wanted to test if it works... And it doesn't cause if it does I should not be able to access the admin page.

**Comment by lloy0076** [comment]
I assume that the middleware you're talking about is `admin.view`.

Figure out how to copy and paste it and paste it here.

**Comment by xJoeyv** [comment]
@lloy0076 
Yea that is the MW im talking about. Else I wouldn't have made sense for my self even...
```
<?php

namespace App\Http\Middleware;

use Closure;

class AdminView
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        \Log::info('Page Request');
        if(true) {
            return abort(403);
        }
        return $next($request);
    }
}
```
The MW worked on other routes except this Route Group from Backpack. Is there a way to change priorities or something? Or edit some code for a temp fix.

**Comment by lloy0076** [comment]
```
Route::group(['prefix' => 'admin', 'middleware' => 'admin.view', 'namespace' => 'Admin'], function () {
    CRUD::resource('article', 'ArticleCrudController');
    CRUD::resource('category', 'CategoryCrudController');

    // What happens if you goto this one?
    Route::any('/testme', function () { return response('testme'); });
});

**Comment by lloy0076** [comment]
route/web.php:

```
Route::get('/',
    function () {
        return view('welcome');
    });

Route::group(
    [
        'prefix' => 'admin',
        'middleware' => 'admin.view',
        'namespace' => 'Admin',
    ],
    function () {
        CRUD::resource('test', 'TestCrudController');
        Route::any('/hello',
            function () {
                return response('hello');
            });
    });
```

app\Http\Middleware\AdminView.php

```
<?php

namespace App\Http\Middleware;

use Closure;

class AdminView
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        return abort(403);
        return $next($request);
    }
}
```

```
backpack/base                         0.8.5                Laravel Backpack's base package, which offers admin authentication and a blank admin panel using AdminLTE
backpack/crud                         dev-master 6145daf   Quickly build an admin interface for your Eloquent models, using Laravel 5. Build a CMS in a matter of minutes.
````

And I get a 403 forbidden.

**WORKS FOR ME**

Please provide more information as there is not sufficient information to indicate this is any type of issue with Backpack.

**Comment by tabacitu** [comment]
Hi @xJoeyv ,

I also tried it and it works for me too. This really doesn't sound like a Backpack issue - I bet it's a Laravel misconfiguration. When you figure out what was the problem, please consider posting your solution here too. It might help other people who run into the same issue (or even yourself, later on).

Cheers!

**Comment by xJoeyv** [comment]
Hi @tabacitu ,

I sure will Imma take a look later this week, on work days Im to busy to work on my Project. Ill post what I did around weekends. Thanks for your support and the community to look into the issue and let me use backpack.

Cheers!
