### ISSUE TITLE
Install but not working

### ISSUE THREAD

**Issue by Gjonni** [Laravel-Backpack/Base#235]
# Bug report
I installed Laravel  + Backpack correctly but /admin not working.
Laravel working correctly /public
### What I did:
Nothing but /admin not open
### What I expected to happen:
Nothing
### What happened:
The requested URL /project/admin was not found on this server.

### Backpack, Laravel, PHP, DB version:
Backpack 3.3
Laravel 5.5.48
PHP 7.0.22-0ubuntu0.16.04.1
mysql  Ver 14.14 Distrib 5.7.20

**Comment by lloy0076** [comment]
When you say `/public` works, what precisely do you mean?

**Comment by Gjonni** [comment]
Hello,
Maybe I did something wrong:
1) installed laravel
2) opened "project/public" and viewed laravel logo, page etc
3) installed backpack but nothing changed on "project/admin"
 (project/admin was not found on this server)

**Comment by tabacitu** [comment]
Hi @Gjonni ,

I've checked, double-checked and triple-checked :-) So... not a bug. If you've successfully installed Backpack, there's no way it doesn't register the admin route. 

What I suspect might have happened - you might have changed the admin prefix to something else, in ```config/backpack/base.php``` line 54:

```php
    // The prefix used in all base routes (the 'admin' in admin/dashboard)
    'route_prefix' => 'admin',
```

If you change that to ```something-else``` you'll then need to log in at ```yourapp/something-else``` instead of ```yourapp/admin```.

Hope it helps.
Cheers!

**Comment by misiekch** [comment]
To every person who got stuck here. The Backpack is not a problem. When using Ubuntu, the problem may be related to the configuration of the Apache server. Further information below.

[https://stackoverflow.com/questions/24784606/laravel-routes-not-working-apache-configuration-only-allows-for-public-index-ph](https://stackoverflow.com/questions/24784606/laravel-routes-not-working-apache-configuration-only-allows-for-public-index-ph)

**Comment by EmmanuelCervettiIESSUD** [comment]
There is a kind of regression though, because it was no need to have this Apache configuration some time ago. It worked on a relative path (for exemple public/ ) out of the box. Now the virtualhost need to be set on public with allow override.
