### ISSUE TITLE
Backpack installation failed

### ISSUE THREAD

**Issue by soliduskodas** [Laravel-Backpack/Base#241]
Hi,

I'm trying to install Backpack base using this comand: php artisan backpack:base:install

After few seconds I receive this error: http://prntscr.com/i9jgr2

I tried to install backpack/generators manually but the problem persist after this.

I'm using MacOS and MAMP. 

Thanks.

**Comment by lloy0076** [comment]
The screenshot (please try to attach files or use backticks in the future for textual feedback) indicates that the Symfony process class cannot find the `composer` binary.

I'd be looking at that first.

**Comment by Balakrrissh** [comment]
try to use sudo before php artisan if you are using linux or mac.

**Comment by tabacitu** [comment]
Hi @soliduskodas ,

Sounds to me like you don't have ```composer``` registered as a global command. This makes sense for some systems, but on localhost it is generally a good idea to [register it globally](https://gist.github.com/kkirsche/5710272), will save you some trouble. If you can't do that, you can install composer in your project alone, and use Backpack's [manual installation process](https://laravel-backpack.readme.io/docs/frequently-asked-questions#section-how-do-i-manually-install-base), but with ```php composer.phar``` anywhere it says ```composer```.

This is standard operating procedure in the Laravel world. If you can't use ```composer``` to install Backpack, I'm pretty sure you haven't installed Laravel correctly either. So you should take another look at that too.

Hope it helps.
Cheers!
