### ISSUE TITLE
PNotify Styling Seems Wrong

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/Base#242]
In [this file](https://github.com/Laravel-Backpack/Base/blob/master/src/resources/views/inc/alerts.blade.php) we see:

```
    PNotify.prototype.options.styling = "bootstrap3";
    PNotify.prototype.options.styling = "fontawesome";
```

That seems...odd.

One of those shold be something not `styling` - possibly `icons`?

@tabacitu

**Comment by tabacitu** [comment]
At first I thought so too - I was planning on changing ```styling``` to ```icons```, but apparently ```icons``` doesn't work. Not with ```fontawesome```, ```fontawesome4``` or ```fontawesome5```. No error, just uses glyphicons instead.

However, ```styling = fontawesome``` works like a charm. Styling seems to be applied over the existing style, so basically we say "use bootstrap", then "use fontawesome" which just overwrites the icons. Like CSS. So we get the result we need.
![screen recording 2018-02-12 at 11 24 am](https://user-images.githubusercontent.com/1032474/36090119-bb3b5884-0fe7-11e8-8738-ea1e9a449c30.gif)


I say _if it ain't broke don't fix it_ :-)
