### ISSUE TITLE
Laravel 5.6 Update

### ISSUE THREAD

**Issue by jsiebach** [Laravel-Backpack/Base#244]
Laravel 5.6 has released today! It seems like a fairly minor update to Laravel, I imagine there will not be a lot of changes to Backpack to accommodate the update. 

https://laravel.com/docs/5.6/upgrade

**Comment by tabacitu** [comment]
Working on this right now! :-) 

But if the past teaches us anything... while we'll be supporting L5.6 today, our dependencies might not. We're submitting PRs, but it might take a few days for their developers to test, merge and tag them.

Let's keep this open until it's settled.
Cheers!

**Comment by tabacitu** [comment]
Quick update: PR that adds support here https://github.com/Laravel-Backpack/Base/pull/245

**Comment by tabacitu** [comment]
Done. Base 0.8.9 and CRUD 3.3.8 add full L5.6 support. Please let me know if you find anything off. Cheers!
