### ISSUE TITLE
login outside app and rewrite URL

### ISSUE THREAD

**Issue by snakom23** [Laravel-Backpack/Base#247]
i have this code for check login outside laravel

`require __DIR__.'/../../r/vendor/autoload.php'; $app = require_once __DIR__.'/../../r/bootstrap/app.php'; $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class); $response = $kernel->handle( $request = Illuminate\Http\Request::capture() ); define('userlogged',Auth::check()); if(userlogged > 0){ echo 'logged';}
`
it's work perfectly

i have reqrite url in .htaccess`

`Options +FollowSymLinks RewriteEngine on RewriteRule ^testing$ /test.php [L]`

the problem is when go in page through https://mydomain.fake/test.php the script show me logged, but when go on url rewriting: https://mydomain.fake/testing, the script not show me logged. The problem is not read if logged when go in url rewriting.

**Comment by lloy0076** [comment]
This seems to be a generic Laravel issue - Laracast's Slack #questions channel might be the best place to ask these if you prefer an interactive answer.
