### ISSUE TITLE
Error in FAQ

### ISSUE THREAD

**Issue by Rattone** [Laravel-Backpack/Base#248]
https://laravel-backpack.readme.io/docs/frequently-asked-questions#section-use-separate-loginregister-forms-for-users-and-admins

This page explains how to have two separate logins, one for users and the other for admin. The problem is that: the explanation is false, it is not enough to do what is described.
This is because the Backpack authentication system overwrites the Laravel authentication route names.
This way user login points to admin login (/admin/login instead of /login)...

**Comment by lloy0076** [comment]
@tabacitu The docs here are most likely wrong as pointed out.

**Comment by tabacitu** [comment]
Ouch. 

Thank you @Rattone - sounds like you should be right. The **route URLs** may be different, but the **route names** are the same. Thanks for speaking out, we'll see what we can do about this - if it's not too late to change the route names to something else.

Cheers!

**Comment by tabacitu** [comment]
Looks to me like the route names have been customized. [They've been prefixed with ```backpack``` for a while now](https://github.com/Laravel-Backpack/Base/blob/master/src/routes/backpack/base.php#L23-L36). @Rattone are you sure you're running the latest Backpack\Base?

**Comment by Rattone** [comment]
@tabacitu Thank you for your work and your help!

Yes, I am still in version 3.1. I apologize for not checking the version mentioned in the link I reported.

This new feature was introduced in version 3.3, right? Version 3.3 is only compatible with Laravel 5.5?

I'm using Laravel 5.4 and I can't update, is there a way to have different routes for user / admin without update Backpack / Laravel?

Can I modify the file "Base/src/routes/backpack/base.php" like that of version 3.3? It's enough?

**Comment by tabacitu** [comment]
Hi @Rattone ,

Yes, 3.3 is compatible with Laravel 5.5.
You should be able to replace all Base route using [this procedure](https://laravel-backpack.readme.io/v3.3/docs/frequently-asked-questions#section-customizing-the-auth-controllers).

Hope it helps. Cheers!

**Comment by tabacitu** [comment]
PS. Heavily recommend upgrading Laravel. You will _need_ to do it at some point. Even though we all dread upgrading, we all know it's what we _should_ be doing it :-) [Laravel Shift](https://laravelshift.com/) could help.
