### ISSUE TITLE
Laravel backpack

### ISSUE THREAD

**Issue by cdomingo-ictdu** [Laravel-Backpack/Base#249]
Hi everyone,

I'm trying to install Backpack base using this comand: php artisan backpack:base:install

After few seconds I receive this error: 
![image](https://user-images.githubusercontent.com/35245768/36653815-f3292a26-1af2-11e8-895a-b720398871ff.png)

I tried to install backpack/generators manually but the problem is still the same.

**Comment by iMokhles** [comment]
put  your own database info inside .env file

**Comment by cdomingo-ictdu** [comment]
It still gives the same error even if I configure the .env file and puts my database info

**Comment by lloy0076** [comment]
The install command uses exactly the same credentials as Laravel would/does.

I suspect that `php artisan migrate:status` would also have similar problems.

This is almost certainly not a bug.
