### ISSUE TITLE
Instructions on modifying/extending the AuthController

### ISSUE THREAD

**Issue by codydh** [Laravel-Backpack/Base#25]
This is currently listed as a TODO. I need to do this so I thought I would submit it as an issue.

**Comment by tabacitu** [comment]
You're totally right. If I'm not mistaken, it's just a matter of:
1. Creating a new AuthController that extends Backpack\Base\...\AuthController.
2. Rewriting the auth routes in your routes file so that they go to your controller, not the one in BackPack.

On mobile now, be back soon with code. Cheers!

**Comment by codydh** [comment]
This seems sensible. However, it appears that the routes in base take precedence over anything in `app/Http/routes.php`, so it seems impossible. I could be mistaken!

**Comment by c1t1zen** [comment]
the same i did make my own route in app\http\route.php to call App\Http\Controllers\Admin\Auth\AuthController
but never routing

**Comment by tabacitu** [comment]
Damn... What order did you place your service providers in? Backpack\Base should be AFTER RouteServiceProvider:

Here's mine:
```php

    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class, // <---- this

        /*
        * Backpack Service Providers...
        */
        Backpack\Base\BaseServiceProvider::class, // <---- before this
        Prologue\Alerts\AlertsServiceProvider::class,
        Backpack\CRUD\CrudServiceProvider::class,
        Collective\Html\HtmlServiceProvider::class,
        Barryvdh\Elfinder\ElfinderServiceProvider::class,
        Spatie\Backup\BackupServiceProvider::class,
        Backpack\BackupManager\BackupManagerServiceProvider::class,
        Backpack\LogManager\LogManagerServiceProvider::class,
        Backpack\Settings\SettingsServiceProvider::class,
        Cviebrock\EloquentSluggable\SluggableServiceProvider::class,
        Backpack\PageManager\PageManagerServiceProvider::class,
        Backpack\MenuCRUD\MenuCRUDServiceProvider::class,
        Backpack\NewsCRUD\NewsCRUDServiceProvider::class,

        /*
        * Other Service Providers...
        */

    ],
```

Was this the problem?

**Comment by codydh** [comment]
This is how I have my app.php config set up. It's possible I'm not overriding the routes properly if there's a special way to do that, but so far no luck.

**Comment by tabacitu** [comment]
Starting with ```Backpack\Base v0.6.12``` there are 3 extra config options in your ```config\backpack\base.php```:
```php
    // The prefix used in all base routes (the 'admin' in admin/dashboard)
    'route_prefix' => 'admin',

    // Set this to false if you would like to use your own AuthController and PasswordController
    // (you then need to setup your auth routes manually in your routes.php file)
    'setup_auth_routes' => true,

    // Set this to false if you would like to skip adding the dashboard routes
    // (you then need to overwrite the login route on your AuthController)
    'setup_dashboard_routes' => true,
```

For overwriting the AuthController the quickest way I see would be to:

1. Disable the auth routes in Base, by setting the ```setup_auth_routes``` config to ```false```.

2. Create:
  - ```app\Http\Controllers\Auth\AuthController.php``` that extends ```Backpack\Base\app\Http\Controllers\Auth\AuthController```;
  - ```app\Http\Controllers\Auth\PasswordController.php``` that extends ```Backpack\Base\app\Http\Controllers\Auth\PasswordController```;

 Overwrite there anything you wish.

3. Set the auth routes in your ```routes.php``` file so that they use your AuthController:
```php
Route::group(['prefix' => config('backpack.base.route_prefix')], function () {
    // Admin authentication routes
    Route::auth();
});
```

I've tested the process, but I would really like another confirmation that it works before I close this issue and include the process in the documentation. 

Cheers!

**Comment by mpixelz** [comment]
Im trying the method on a new project to see if it works.. 
extending the backpack authcontroller should allow us to still use /admin/ side authentication? no?

after making the changes suggested above... /admin/login and /admin/register pages are gone.. 
am i missing something here?

heres my /app/Http/Controllers/Auth/AuthController.php

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

//use Backpack\Base\app\Http\Controllers\Auth\AuthController;

class AuthController extends Backpack\Base\app\Http\Controllers\Auth\AuthController
{
    //
}
```
ive also added the routes so it should work on the /admin/ side.. no?

**Comment by tabacitu** [comment]
Hi @mpixelz ,

Yes, the login and register routes should still work if setup correctly. I don't think you've published the views from the Base package (your error is "_view auth.login not found_"). Try going through the [installation steps](https://github.com/laravel-backpack/base#install-on-laravel-53) in the Base package again.

Cheers!

**Comment by abrahampe** [comment]
My problem is a little newbie... I would like to add a middleware to the admin route and I can't find where... I really didn't figure out where the routes are declared in the backpack...

**Comment by tabacitu** [comment]
Hi @abrahampe ,

The Backpack routes are always registered in the service provider. So for Base it's [BaseServiceProvider::setupRoutes()](https://github.com/Laravel-Backpack/Base/blob/master/src/BaseServiceProvider.php#L69-L84).

This is the case for all Backpack packages. It's so that, if you need major customizations over the package and are not interested in updates, you can just drag-and-drop contents of the "src" folder over your "app" and change the namespaces, and it's like you coded those yourself. However, for most cases it's recommended you extend the package files.

Cheers!

**Comment by abrahampe** [comment]
@tabacitu thanks! I got it here! I preferred extending the controller and then inserted da middleware in the constructor. I had to rewrite the dashboard method.

**Comment by mirzavu** [comment]
@tabacitu 
I am trying to create admin panel for user whole 'role' column = 'admin'.
I have added the routes and extended controllers as mentioned in your comment. Wrote a 'login' function for authenticating and worked. (But I had to copy all the functions from backpacks AuthController to App/Http/Controller/Admin/AuthController.php to make all work, or else it calls the parent's parent AuthController function.)

Now I tried to create middleware admin to overwrite the backpack admin middleware (for restricting access to dashboard only to users role = admin), but it always called backpack middleware. 

What is the method to be followed here as it is something every admin panel requires to manage and differentiate normal and admin users.

Thanks

**Comment by OwenMelbz** [comment]
@mirzavu are you trying to create an admin panel. For non-admin users?

Also I don't think Backpack has any middleware. In fact Backpack doesn't do anything fancy with authentication except adjusting the password reset flow.

What exactly are you trying to do as it seems you've done quite a lot and not sure why?

From your last paragraph are you trying to say

"How do I stop/separate normal users from admin users so normal users can't access the admin" ?

**Comment by mirzavu** [comment]
Backpack is running backpack/base/src/app/Http/Middleware/Admin.php middleware.
And yes I need to prevent normal users(where role column ='member') and only allow admin users to enter (role='admin').

**Comment by OwenMelbz** [comment]
Ah right, never even noticed that there to be honest!!

The most simple way to do it is to

Run `php artisan make:auth` which will generate a copy of laravels default auth (This is needed for the frontend users)

You'll then add a "Guard" on all front-end users, which can be read about https://laravel.com/docs/5.3/authentication#adding-custom-guards

Then you'll need to add the line following into the laravel generated ForgotPasswordController/LoginController/RegisterController/ResetPasswordController

```php
use Illuminate\Support\Facades\Password;
```

and

```php
public function guard()
{
    return \Auth::guard('public');
}

public function broker()
{
    return Password::broker('public');
}
```

This will tell the application that your frontend users all use a different guard to the backpack admin, so they'll have separate sessions.

Then open up the `config/auth.php` and inside the 'guards' section add a new item under the web/api ones like

```php
'public' => [
    'driver' => 'session',
    'provider' => 'public',
],
```

then inside the 'providers' section add a new one like

```php
'public' => [
    'driver' => 'eloquent',
    'model' => App\User::class,
],
```

This should separate out your users, and allows admins to also have frontend sessions.

On you frontend when checking for the users login instance,  you just have to pass in the guard.

So if you have a hompage that has like "Welcome back Garry" you'd do

```php
@if (Auth::guard('public')->check())
Welcome back {{ Auth::guard('public')->user()->name }}
@else
Please login
```

**Comment by mirzavu** [comment]
Thanks. Here we have a separate gaurd for frontend users. But still i guess the frontend users will be able to login to backend, which is to be restricted. not sure. or do we need separate tables for admin and normal users.

**Comment by OwenMelbz** [comment]
Ah sure, you just need to update the login validation method.

In your LoginController you can add a validation method, which checks the user is an admin before allowing them in. Theres a tutorial about it here https://laravel-news.com/login-validation

**Comment by wiisg** [comment]
Are there now  4 controllers instead of the old Auth & Password controller? I tried extending the 4 controllers and login works but logout would lead to 405 method not allowed. Anyone? Thanks

**Comment by wiisg** [comment]
Route::list shows /logout to be post method instead of get, but isn't it supposed to be get? 

Adding 
```
			Route::get('logout', [
			'uses'=> 'Auth\LoginController@logout',
			'as' => 'auth.logout',
			]);
```
solved it.

**Comment by tabacitu** [comment]
@wiisg , Laravel 5.3 and 5.4's ```Auth::routes()``` only register a POST route for logout, so yes, if you overwrite the AuthController you also need to specify a GET route for logout.

**Comment by michaelGregoire** [comment]
Can I just make a suggestion? Could you change the AuthController to read route_prefix from the backpack.base config? You currently have "admin" hard-coded. It seems kind of silly to not use the config.

`protected $loginPath = 'admin/login';
    // after you've logged in redirect to
    protected $redirectTo = 'admin/dashboard';
    // after you've logged out redirect to
    protected $redirectAfterLogout = 'admin';`

**Comment by lloy0076** [comment]
@tabacitu @codydh - this came up again in gitter today; is the purpose of this ticket to:

1. Keep track of the myriad of similar but not the same issues about the auth issue?
2. Submit some documentation to @tabacitu to put up on the web-site?
3. Something else?

It feels like 3 to me but I'm not sure what this issue is actually tackling?

**Comment by tabacitu** [comment]
Hi guys,

Since there are already two documented solutions for this:
- [the config values](https://laravel-backpack.readme.io/docs/frequently-asked-questions#section-customizing-the-auth-controllers)
- [the base routes file](https://laravel-backpack.readme.io/docs/frequently-asked-questions#section-customizing-the-routes)

I guess this issue is finally ok to be closed :-) Let me know if you don't agree.

Cheers!

**Comment by lvar** [comment]
I spend 3 days trying to figure out how override login and register form on my proyect...the documentation is to poor...from 3.2 version there is nothing documented on backpack website and we are on 2018!!..and if by chance I was not found this github issue....maybe I could spend more days trying to resolve my problem..

Please !!!!!!!!!!!!!!!! document a steap by steap process to do this!...some of us are newbies on backpack.

**Comment by AbbyJanke** [comment]
@ivar please see a previous comment above:

https://github.com/Laravel-Backpack/Base/issues/25#issuecomment-238011374

The steps are still the same.

**Comment by lvar** [comment]
I already extend my RegisterController to Backpack\Base\app\Http\Controllers\Auth\RegisterController ...and I'm getting this error:

"Class 'App\Http\Controllers\Auth\Backpack\Base\app\Http\Controllers\Auth\RegisterController' not found"

**Comment by OwenMelbz** [comment]
🍿

**Comment by AbbyJanke** [comment]
@ivar make sure you added

Use Backpack\Base\app\Http\Controllers\Auth\AuthController; 

To the top of your file.

**Comment by laxsmi** [comment]
> Starting with `Backpack\Base v0.6.12` there are 3 extra config options in your `config\backpack\base.php`:
> 
> ```
>     // The prefix used in all base routes (the 'admin' in admin/dashboard)
>     'route_prefix' => 'admin',
> 
>     // Set this to false if you would like to use your own AuthController and PasswordController
>     // (you then need to setup your auth routes manually in your routes.php file)
>     'setup_auth_routes' => true,
> 
>     // Set this to false if you would like to skip adding the dashboard routes
>     // (you then need to overwrite the login route on your AuthController)
>     'setup_dashboard_routes' => true,
> ```
> 
> For overwriting the AuthController the quickest way I see would be to:
> 
> 1. Disable the auth routes in Base, by setting the `setup_auth_routes` config to `false`.
> 2. Create:
>    
>    * `app\Http\Controllers\Auth\AuthController.php` that extends `Backpack\Base\app\Http\Controllers\Auth\AuthController`;
>    * `app\Http\Controllers\Auth\PasswordController.php` that extends `Backpack\Base\app\Http\Controllers\Auth\PasswordController`;
>    
>    Overwrite there anything you wish.
> 3. Set the auth routes in your `routes.php` file so that they use your AuthController:
> 
> ```
> Route::group(['prefix' => config('backpack.base.route_prefix')], function () {
>     // Admin authentication routes
>     Route::auth();
> });
> ```
> 
> I've tested the process, but I would really like another confirmation that it works before I close this issue and include the process in the documentation.
> 
> Cheers!

Hi @tabacitu, I've followed the steps you mentioned but I get a `Route [backpack.auth.register] not defined.` error... Any idea why this might be?

**Comment by pathaksa** [comment]
is there a solution for this by now?
