### ISSUE TITLE
change the url of login page

### ISSUE THREAD

**Issue by gasparyanyur** [Laravel-Backpack/Base#250]
Hi all. I need to change `/admin/login` to `/` . Is it possible ? also I need to change the blade template of login page. Thanks!

**Comment by tabacitu** [comment]
Sure. Just eliminate the admin prefix in your ```config/backpack/base.php``` file. Hope it helps. Cheers!

**Comment by gasparyanyur** [comment]
Why?? I only need to change the url of login page, nothing else

**Comment by tabacitu** [comment]
Then add a new route that leads there:
```php
Route::get('', 'Backpack\Base\Auth\LoginController@showLoginForm')->name('backpack.auth.login');
```

**Comment by coccoinomane** [comment]
Thanks! 

Just a note: to make that work I had to add the correct namespace:

```php
Route::get('/', '\Backpack\Base\app\Http\Controllers\Auth\LoginController@showLoginForm')->name('backpack.auth.login');
```
