### ISSUE TITLE
An exception is thrown if a route which needs authentication is accessed by an unauthenticated user when using the "auth" middleware (as stated on the documentation)

### ISSUE THREAD

**Issue by santiagotoledo91** [Laravel-Backpack/Base#255]
# Bug report

Default "auth" middleware throws an exception if an unauthenticated user tires to access a protected route, caused by the route name addition on v0.8.9, there is also a documentation typo at https://laravel-backpack.readme.io/docs

> STEP 3. manually add this to your routes.php file (under the admin prefix and **auth** middleware);

### What I did:

Updated to BASE 0.8.9 and tried to access a route that needs authentication

### What I expected to happen:

Redirect to login page

### What happened:

Route with name "login" is not found and an exception is thrown by Laravel

### What I've already tried to fix it:

Use the "admin" middleware instead of the default "auth".

### Backpack, Laravel, PHP, DB version:

Backpack 0.8.9
Laravel 5.5.35
PHP 7.2.2
MariaDB 10.2.12

**Comment by tabacitu** [comment]
Hi @santiagotoledo91 ,

You're totally right - you need to use the ```admin``` middleware, not ```auth```. The ```admin``` middleware makes sure you're redirected to the right spot - that's pretty much all it does different from ```auth```.

Just changed the docs, sorry, this must have been annoying for you.

Thanks. Cheers!
