### ISSUE TITLE
ProcessFailedException on artisan install

### ISSUE THREAD

**Issue by jerauf** [Laravel-Backpack/Base#256]
# Bug report

Symfony\Component\Process\Exception\ProcessFailedException  : The command "composer require backpack/generators --dev" failed.

Exit Code: 127(Command not found)

### What I did:

I ran composer require. This happened when I ran the artisan install command.

**Comment by tabacitu** [comment]
Hi @jerauf ,

When you've installed composer, have you registered it as a global command (maybe in you PATH)? Rephrased: in a regular Laravel project, are you able to run ```composer update```, not ```php composer.phar update``` or something like that?

I suspect that should be your problem - your command line can't find ```composer```. 
Hope it helps. Cheers!
