### ISSUE TITLE
[Feature][0.9.x][To do] Upgrade to AdminLTE 2.4.x

### ISSUE THREAD

**Issue by begnini** [Laravel-Backpack/Base#262]
The last release of AdminLTE 2.3.x has more than one year. I think will be simple to upgrade, only testing if a css or js break.

**Comment by tabacitu** [comment]
Hi @begnini ,

Agreed. This will be done now, in the 0.9.x update.

Cheers!

**Comment by AbbyJanke** [comment]
Psst, looks like this was completed here: 5d68bfa closing.

**Comment by tabacitu** [comment]
Right :-) Thank you @AbbyJanke !
