### ISSUE TITLE
Custom ns for models / parent User Model

### ISSUE THREAD

**Issue by mgralikowski** [Laravel-Backpack/Base#265]
# Bug report

It's a common case when we set another namespace for models (for me its App/Models).

### What I did: 

Installed new backpack.

### What I expected to happen:

To have ability to set own Models.

### What happened:

"Class 'App\User' not found"

### What I've already tried to fix it:

Make a copy of model but is ugly fix.. 
I can also set 
   'user_model_fqn' => \App\Models\User::class,
but i think then i lost some functionality shipped with backpack, am i wrong? 

### Backpack, Laravel, PHP, DB version:

0.9, L5.5

**Comment by tabacitu** [comment]
Hi @mgralikowski ,

Changing ```user_model_fqn``` in the config file should be a complete fix - no functionality lost. Let me know if you encounter any issues afterwards - you shouldn't.

Cheers!
