### ISSUE TITLE
Datatables assets 404 after php artisan backpack:install

### ISSUE THREAD

**Issue by scottgrayson** [Laravel-Backpack/Base#269]
# Bug report

### What I did:
steps 7-9 of upgrade guide
https://laravel-backpack.readme.io/docs/upgrading-crud-33-to-34

### What I expected to happen:
Views that worked with 3.3 should work in 3.4 when `mandatory` steps are completed

### What happened:
the following assets respond with 404 because they are not present in `public/vendor/adminlte/plugins`:
- datatables/dataTables.bootsrap.js
- jquery.dataTables.js
- dataTables.bootstrap.css

### What I've already tried to fix it:
I am planning to copy them over manually, but this should be automatic

### Backpack, Laravel, PHP, DB version:
Laravel 5.6
Backpack 3.4
PHP 7.1
MySql 5.7

**Comment by scottgrayson** [comment]
looks like Admin LTE 2.3 had these plugins
https://github.com/almasaeed2010/AdminLTE/tree/v2.3.11/plugins
While 2.4 has fewer
https://github.com/almasaeed2010/AdminLTE/tree/v2.4.3/plugins

**Comment by scottgrayson** [comment]
I only had to run php artisan view:clear

The adminlte components are now in `bower-components` folder. The old views referenced `plugins` folder

**Comment by tabacitu** [comment]
Thank you @scottgrayson , I'll add ```php artisan view:clear``` to the upgrade guide, so others don't face your issues. Thanks a lot for sharing your solution. Cheers!
