### ISSUE TITLE
Display the list of internal links in the panel menu

### ISSUE THREAD

**Issue by xdasty** [Laravel-Backpack/Base#270]
# Bug report

### What I did:

project\resources\views\vendor\backpack\base\inc\sidebar_content.blade.php
------------------------------------------------------------------------

@menu
------------------------------------------------------------------------

project\app\Providers\AppServiceProvider.php
------------------------------------------------------------------------
public function register()
    {
        $this->app->afterResolving('blade.compiler', function (BladeCompiler $bladeCompiler) {
            $bladeCompiler->directive('menu', function () {
                return '< ? php var_dump(MenuItem::where("type","internal_link")->get()); ? >';
            });

        });
    }
------------------------------------------------------------------------

### What I expected to happen:

I would like to display the list of internal links in the panel menu
internal links point to modules created with crud

### What happened:

Class 'MenuItem' not found 

### Backpack, Laravel, PHP, DB version:
PHP Version 7.2.1
Laravel Framework 5.6.13
backpack/base 0.9.1
backpack/crud 3.4.2
backpack/generators 1.1.13
backpack/menucrud 1.0.13

It would be interesting to create blade directives to display both a frontend and a backend menu

**Comment by tabacitu** [comment]
Hi @xdasty ,

I don't think we can qualify this as a bug, since it's not a Backpack feature - it's you custom code. So I'll close this, since [it's more appropriate for StackOverflow](https://stackoverflow.com/questions/tagged/backpack-for-laravel) than Github. 

That being said, it looks to me like you need to ``` use App\Models\MenuItem;``` in AppServiceProvider.

Cheers!
