### ISSUE TITLE
routes/backpack/custom.php needs to have the 'web' middleware included

### ISSUE THREAD

**Issue by rgf207** [Laravel-Backpack/Base#271]
# Bug report

### What I did:
Following the upgrade guide on step 3, I copied all of my backpack routes from routes/web.php to routes/backpack/custom.php

> Starting with Backpack\Base 0.9.0, we have a new place for you to store your admin routes: routes/backpack/custom.php. That's where CRUD::resource() routes are generated automatically, when you generate a new CRUD. To future-proof your application, you can publish that file using php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider" --tag=custom_routes, then manually move your existing admin routes there (from your routes/web.php).

### What I expected to happen:
I expect to remain authenticated when browsing to /admin/any_route 

### What happened:
browsing to any route within routes/backpack/custom.php triggers the 'guest' middleware and redirects to /home
### What I've already tried to fix it:

modified the Route::group syntax in routes/backpack/custom.php to include web middleware

```
...
'middleware => ['web', config('backpack.base.middleware_key','admin')]
...
```

### Backpack, Laravel, PHP, DB version:
Backpack: 0.9.1
Laravel: 5.5.39

This is addressed in PR #268

**Comment by tabacitu** [comment]
Just merged the PR #268 . Thanks a lot @rgf207 !
