### ISSUE TITLE
404 on Select2 After Upgrade to 3.4

### ISSUE THREAD

**Issue by simplusgroup** [Laravel-Backpack/Base#273]
# Bug report

### What I did:
Upgraded from 3.3 to 3.4; did follow upgrade steps including deleting the adminlte and backpack directories under vendor, and then recreated them using Backpack:base:install. 

### What I expected to happen:
It would work.

### What happened:
Getting 404s on my select2 field assets. 
Screenshot: https://www.dropbox.com/s/7sgub2fts3k9iqy/Screenshot%202018-04-02%2022.40.36.png?dl=0

### What I've already tried to fix it:
Checking routes, going through the update procedure again, checking all my backpack modified files.

### Backpack, Laravel, PHP, DB version:
Latest on all

**Comment by tabacitu** [comment]
@simplusgroup - I see you've closed the issue, but for others that stumble upon this, what was the problem? ```php artisan cache:clear``` or did you have custom select2 fields?

**Comment by simplusgroup** [comment]
@tabacitu Thanks for the fast response! composer.lock was preventing my adminlte from updating to the latest version... so many of the resources were broken. But, easy fix once I figured that out!
