### ISSUE TITLE
AdminLTE assets not found, after publishing with webpack

### ISSUE THREAD

**Issue by mamarmite** [Laravel-Backpack/Base#274]
# Bug report
Some of AdminLTE assets in layout are not found when generated with Webpack. Some path were added with bower_components and other path.

### What I did:
- Upgraded from BP/Base 0.8.x to 0.9.x and BP/CRUD 3.3.x to 3,4,x
- Followed the upgrade step mandatory and suggested on [Backpack upgrade guide](https://laravel-backpack.readme.io/docs/upgrading-crud-33-to-34)
- Published the assets with webpack
- Open the dashboard
- Some of the assets where not found, JQuery, jQuery UI elements, 

### What I expected to happen:
Front-end assets loaded

### What happened:
Assets not found.

### What I've already tried to fix it:
Scripts tags in layout.blade.php : 
```
    <!-- jQuery 2.2.3 -->
    <script src="{{ asset('vendor/adminlte') }}/plugins/jQuery/jquery-2.2.3.min.js"></script>
    {{-- <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset('vendor/adminlte') }}/plugins/jQuery/jQuery-2.2.3.min.js"><\/script>')</script> --}}
    <!-- Bootstrap 3.3.7 -->
    <script src="{{ asset('vendor/adminlte') }}/bootstrap/js/bootstrap.min.js"></script>
    <script src="{{ asset('vendor/adminlte') }}/plugins/pace/pace.min.js"></script>
    <script src="{{ asset('vendor/adminlte') }}/plugins/jQueryUI/jquery-ui.min.js"></script>
    {{-- <script src="{{ asset('vendor/adminlte') }}/plugins/fastclick/lib/fastclick.js"></script> --}}
    <script src="{{ asset('vendor/adminlte') }}/dist/js/app.min.js"></script>
```

CSS tags : 
```
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/') }}/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="{{ asset('vendor/adminlte/') }}/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('vendor/adminlte/') }}/dist/css/skins/_all-skins.min.css">

    <link rel="stylesheet" href="{{ asset('vendor/adminlte/') }}/plugins/pace/pace.min.css">
    <link rel="stylesheet" href="{{ asset('vendor/backpack/pnotify/pnotify.custom.min.css') }}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- BackPack Base CSS -->
    <link rel="stylesheet" href="{{ asset('vendor/backpack/backpack.base.css') }}?v=2">
    <link rel="stylesheet" href="{{ asset('vendor/backpack/overlays/backpack.bold.css') }}">
```

### Backpack, Laravel, PHP, DB version:
- BP/Base : 0.9.2
- BP/CRUD : 3.4.4, 
- Laravel 5.6.15
- Php 7.2
- DB Mysql 5.7.x
- On Apache Ubuntu.

**Comment by mamarmite** [comment]
This has a lot of chance that I'm wrong in my update and publish process. Is this issue is only a 14 inches between the chair and the screen ? :o

**Comment by OliverZiegler** [comment]
What du you mean by publishing assets via webpack? 
Currently all assets will get published to your `public/vendor` folder if you go through the upgrade guide step by step. 
Please make sure you *delete* the mentioned files and folders before executing the install command, otherwise the new assets will not be published.

**Comment by mamarmite** [comment]
I assumed, i mean without exploring the code, that the command `php artisan backpack:base:install` publish the assets with webpack. 

The published command, export all the AdminLTE to public/vendor/adminlte/plugins/* and in Backpack/CRUD (I may have add this issue in Backpack ?), the fields use bower_compoenents/ paths. 

In exemple : https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/fields/date_picker.blade.php

**Comment by OliverZiegler** [comment]
Did you delete the `public/vendor/backpack` and `public/vendor/adminlte` folders before executing the install commands?
If so the files under `public/vendor/adminlte/bower_components` are getting published correctly.
I just tried and worked like it should... 🤔 

You could try deleting the two folders and execute **both** install commands again...

**Comment by mamarmite** [comment]
I deleted it before the rebuild. I'll redo the process. Thanks for the feedback @OliverZiegler , always welcomme. I assume I'm wrong, so I'll close this issue.
