### ISSUE TITLE
avatar_type - Custom method on the User model

### ISSUE THREAD

**Issue by dividy** [Laravel-Backpack/Base#275]
# Bug report

Hello!

I am having problems setting a custom function for the avatar.

Maybe i'm doing it wrong?

Thanks in advance!

### What I did:

**Modified base.php :**
'avatar_type' => 'avatar_url',

**Added the function to the User model :**
public function avatar_url()
{        
   return $this->avatar;
}

### What I expected to happen:

I expected the function to return the image url from the user model

### What happened:

ErrorException thrown with message "App\User::getAvatar must return a relationship instance. (View: C:\wamp64\www\pharma\resources\views\vendor\backpack\base\inc\sidebar_user_panel.blade.php) (View: C:\wamp64\www\pharma\resources\views\vendor\backpack\base\inc\sidebar_user_panel.blade.php) (View: C:\wamp64\www\pharma\resources\views\vendor\backpack\base\inc\sidebar_user_panel.blade.php) (View: C:\wamp64\www\pharma\resources\views\vendor\backpack\base\inc\sidebar_user_panel.blade.php)"

Stacktrace:
#95 ErrorException in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php:410
#94 {main} in C:\wamp64\www\pharma\public\index.php:0
#93 ErrorException in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php:410
#92 {main} in C:\wamp64\www\pharma\public\index.php:0
#91 ErrorException in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php:410
#90 {main} in C:\wamp64\www\pharma\public\index.php:0
#89 ErrorException in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php:410
#88 {main} in C:\wamp64\www\pharma\public\index.php:0
#87 LogicException in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php:410
#86 Illuminate\Database\Eloquent\Model:getRelationshipFromMethod in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php:393
#85 Illuminate\Database\Eloquent\Model:getRelationValue in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php:323
#84 Illuminate\Database\Eloquent\Model:getAttribute in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1375
#83 Illuminate\Database\Eloquent\Model:__get in C:\wamp64\www\pharma\vendor\backpack\base\src\helpers.php:74
#82 backpack_avatar_url in C:\wamp64\www\pharma\storage\framework\views\e182c0d42352f1de007221fe1cad725d1be3bd8b.php:4
#81 include in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:43
#80 Illuminate\View\Engines\PhpEngine:evaluatePath in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php:59
#79 Illuminate\View\Engines\CompilerEngine:get in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:137
#78 Illuminate\View\View:getContents in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:120
#77 Illuminate\View\View:renderContents in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:85
#76 Illuminate\View\View:render in C:\wamp64\www\pharma\storage\framework\views\af911575b02e11e1371c0d35d7dbd7aad9b0d991.php:7
#75 include in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:43
#74 Illuminate\View\Engines\PhpEngine:evaluatePath in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php:59
#73 Illuminate\View\Engines\CompilerEngine:get in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:137
#72 Illuminate\View\View:getContents in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:120
#71 Illuminate\View\View:renderContents in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:85
#70 Illuminate\View\View:render in C:\wamp64\www\pharma\storage\framework\views\90fa5ed7bc758f26ab0f9d40be002b1da14ae7ef.php:88
#69 include in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:43
#68 Illuminate\View\Engines\PhpEngine:evaluatePath in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php:59
#67 Illuminate\View\Engines\CompilerEngine:get in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:137
#66 Illuminate\View\View:getContents in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:120
#65 Illuminate\View\View:renderContents in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:85
#64 Illuminate\View\View:render in C:\wamp64\www\pharma\storage\framework\views\626ca05927098ca5bdded349b6de4ba2259223ee.php:73
#63 include in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:43
#62 Illuminate\View\Engines\PhpEngine:evaluatePath in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php:59
#61 Illuminate\View\Engines\CompilerEngine:get in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:137
#60 Illuminate\View\View:getContents in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:120
#59 Illuminate\View\View:renderContents in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\View.php:85
#58 Illuminate\View\View:render in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Http\Response.php:42
#57 Illuminate\Http\Response:setContent in C:\wamp64\www\pharma\vendor\symfony\http-foundation\Response.php:200
#56 Symfony\Component\HttpFoundation\Response:__construct in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Router.php:724
#55 Illuminate\Routing\Router:toResponse in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Router.php:698
#54 Illuminate\Routing\Router:prepareResponse in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Router.php:658
#53 Illuminate\Routing\Router:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#52 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\backpack\crud\src\app\Http\Controllers\CrudController.php:45
#51 Backpack\CRUD\app\Http\Controllers\CrudController:Backpack\CRUD\app\Http\Controllers\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:131
#50 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\backpack\base\src\app\Http\Middleware\CheckIfAdmin.php:27
#48 Backpack\Base\app\Http\Middleware\CheckIfAdmin:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
#45 Illuminate\Routing\Middleware\SubstituteBindings:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:67
#42 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
#39 Illuminate\View\Middleware\ShareErrorsFromSession:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:63
#36 Illuminate\Session\Middleware\StartSession:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
#33 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:59
#30 Illuminate\Cookie\Middleware\EncryptCookies:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
#27 Illuminate\Pipeline\Pipeline:then in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Router.php:660
#26 Illuminate\Routing\Router:runRouteWithinStack in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Router.php:635
#25 Illuminate\Routing\Router:runRoute in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Router.php:601
#24 Illuminate\Routing\Router:dispatchToRoute in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Router.php:590
#23 Illuminate\Routing\Router:dispatch in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
#22 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#21 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php:65
#20 Barryvdh\Debugbar\Middleware\InjectDebugbar:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\fideloper\proxy\src\TrustProxies.php:56
#17 Fideloper\Proxy\TrustProxies:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in C:\wamp64\www\pharma\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in C:\wamp64\www\pharma\public\index.php:55

### Backpack, Laravel, PHP, DB version:

Backpack 3.4,
Laravel 5.5,
PHP 7.0.10,
MySQL 5.7.14

**Comment by cannect** [comment]
It looks like the error is saying that it is not called as a function like: `App\User::getAvatar()` but as a variable `App\User::getAvatar`.

**Comment by dividy** [comment]
Yes bro, thanks for answering, but i already had a look at that and found that out myself too :-)

In fact,i just figured out how to make it work 👍

> function backpack_avatar_url($user)
>     {
>         switch (config('backpack.base.avatar_type')) {
>             case 'gravatar':
> // CHANGES HERE... 
>                 return Gravatar::fallback('https://placehold.it/160x160/00a65a/ffffff/&text='.$user->name[0])->get($user->email); 
>                 break;
>  
>             case 'placehold':
>                 return 'https://placehold.it/160x160/00a65a/ffffff/&text='.$user->name[0];
>                 break;
>  
>             default:
>                 **return $user->{config('backpack.base.avatar_type')};**
>                 break;
>         }
>     }

**In base.php :** 

> 'avatar_type' => 'AvatarUrl',

**and then on my model :** 

>     public function getAvatarUrlAttribute()
>     {        
>         return $this->avatar;
>     }

This still seems like a workaround to me but it works ! :)

Thanks again for answering.

Have a nice day!

**Comment by cannect** [comment]
Great catch @dividy ! Is this documented somewhere?

**Comment by tabacitu** [comment]
Good colab here @dividy and @cannect ! Thanks for sharing with the community. Cheers!

PS. This feature is documented inside the ```config/backpack/base.php``` file. Let me know if you don't think it's enough.
```php
    // What kind of avatar will you like to show to the user?
    // Default: gravatar (automatically use the gravatar for his email)
    // Other options:
    // - placehold (generic image with his first letter)
    // - example_method_name (specify the method on the User model that returns the URL)
    'avatar_type' => 'gravatar',
```

**Comment by tabacitu** [comment]
Ouch. Now I understand what you were saying, @dividy - sorry for being so dumb. The description is deceiving - it was asking you to specify **a method**, but it was actually calling **an attribute**. 

I've just merged a PR and made both options available, to provide backwards-compatibility. **If a method with that name exists on that model, it will load it. Otherwise it will fall back to the accessor,** like it was before. This way, @dividy 's and others apps won't break because of this.

Thanks, cheers!
