### ISSUE TITLE
checkLicenseCodeExists breaks Redis Cache

### ISSUE THREAD

**Issue by InkedCurtis** [Laravel-Backpack/Base#284]
# Bug report

### What I did:
Set `APP_ENV` from `local` to `production`
### What I expected to happen:
No errors.
### What happened:
Redis cache failing due to the `checkLicenseCodeExists` being run on `register()` rather than `boot()` which prevents the class from being initiated

Copy of my StackTrace: https://gist.github.com/InkedCurtis/e3f7ff073818900817c9e5fdedf5463a
### What I've already tried to fix it:
Commented out the function return & I'm no longer receiving the error.

**Comment by InkedCurtis** [comment]
Appears this is due to it not being licensed.

**Comment by tabacitu** [comment]
Thank you @InkedCurtis . Made sure this error doesn't show up in the latest version, a standard bubble notification is shown asking to purchase a license. Thanks, cheers!
