### ISSUE TITLE
WIndows authentication

### ISSUE THREAD

**Issue by gaiapuffo** [Laravel-Backpack/Base#285]
Hi,

I want to add windows authentication in this way for example

```
if ($request->server('AUTH_USER') && ($user = User::where('username', $request->server('AUTH_USER'))->first()))
        {
            $this->auth->login($user);
        }
```
In backpack I don't find the file where I can change the default behaviour of login, can you give me some instructions?

**Comment by AbbyJanke** [comment]
Hello @gaiapuffo there is no built in way to do this Backpack uses the default Laravel Authentication system. There are however 2 options after searching around really quick:

1) Create a custom authentication middleware:
https://gist.github.com/AbbyJanke/864c376d8626de5791909cf31ead140d

Once created you will need to update the `middleware_class` within the `config/backpack/base.php` file.

To do that you would still need to have a user within the database that it can login to.


2) My recommended solution which is much cleaner and will likely avoid bigger issues in the end is this windows auth package:

https://github.com/jakub-klapka/laravel-windows-auth/tree/master

Based on the instructions from it all you would have to do is update the new `ad_auth.php` file and then update the `auth.php` to set the authentication driver to windows.
