### ISSUE TITLE
autocomplete="off" on authentication forms

### ISSUE THREAD

**Issue by seandowney** [Laravel-Backpack/Base#286]
# Suggestion

### What I expected to happen:
Not to see my previous login details when logging in or registering. This is a security measure to prevent people from seeing logins of previous people who used the machine.

### What happened:
I can see the email addresses of previous accounts who logged in on my machine.

### What I've already tried to fix it:
Adding ``autocomplete="off" `` to the forms will fix it.

### Backpack, Laravel, PHP, DB version:
* "php": ">=7.0.0",
* "backpack/crud": "^3.4",
* "laravel/framework": "5.5.*",

What do you think?

**Comment by seandowney** [comment]
This is mainly to stop the email addresses being remembered in the field on the browser even if you don't have autofills turned on.

**Comment by AbbyJanke** [comment]
Which browser are you using? I've tested in Chrome, Firefox and Safari and do not have this issue with it remembering what email addresses have been previously used.

You could use `attributes` when adding a field.

**Example**
```php
$this->crud->addField([
     // MANDATORY
    'name'  => 'email',
    'label' => 'E-Mail Address',
    'type'  => 'email',
    'attributes' => [
       'placeholder' => 'Some text when empty',
       'class' => 'form-control some-class'
     ],
]);
```

That works for custom fields as for the login ones, you could overwrite the default views with backpack and add it.

**Comment by seandowney** [comment]
Thanks @AbbyJanke 

What I mean is this
![image](https://user-images.githubusercontent.com/652616/40538220-fb23575a-6008-11e8-8ca0-bad9adafac98.png)

the names are remembered in the browser without auto fill.

I have already overwritten the default views for my project but just thought it might be good to have it in the code project.

If it's not considered necessary then it's fine to close this.

**Comment by tabacitu** [comment]
Hmm... @seandowney I actually think the autocomplete is very useful. Here's my logic, tell me what you think:
- most devices now have one owner, one user; hell, most of us have more than one personal device (personal smartphone, personal laptop, personal tablet); I haven't even _seen_ netcafes or shared devices... maybe in uni many years ago, but even then, I and quite a few others brought our laptops;
- a lot of people have more than one email address; work, personal, project, etc; I personally have 30+ email addresses, difficult to keep track;
- in my experience, admins are smart people, but they struggle with the simplest things; things like remembering their username; or their password; 
- for myself, and for 99% of admins (I think), the autosuggest is actually useful; I know I'm glad when I open the login page and the user & password are pre-filled by Chrome, or I can use 1Password to login; one less thing to remember, fewer keys to press;

Again - I might be wrong, generalizing my opinion and use case. What do you think?

Cheers!

**Comment by seandowney** [comment]
@tabacitu @AbbyJanke all good, thanks.

It's a personal preference too and depends on the security requirements per project and the views can be overridden per project too so I will close this.

**Comment by EricPaulson** [comment]
I think the main reason this should not be closed is because most CRUDs have user management which requires you to enter dozens or hundreds of different email addresses and passwords when you are creating users. You definitely do not want those to autocomplete, and it's caused a lot of headaches on my project. And having my client and all of their staff turn off autocomplete is obviously not an option. Unless there's another way to do this that I am not aware of, this appears to be a big issue.

**Comment by tabacitu** [comment]
@EricPaulson , do you mean **you would like autocomplete off when Creating / Editing users?** If so, you can totally do that using ```attributes``` like AbbyJanke suggested earlier in this thread: https://github.com/Laravel-Backpack/Base/issues/286#issuecomment-391876878 . So something like this should work to disable autocomplete when creating / editing users, and I agree it would totally be helpful:

```php
$this->crud->addField([
     // MANDATORY
    'name'  => 'email',
    'label' => 'E-Mail Address',
    'type'  => 'email',
    'attributes' => [
       'autocomplete' => 'off',
     ],
]);
```

Sean's request was to disable autocomplete on the login form - which I still think would be better left "on". Please give more detail if you were referring to this situation - I don't see how/why an admin would login with multiple usernames and passwords.

Cheers!

**Comment by ArroWsGM** [comment]
@tabacitu 
according to [this](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Preventing_autofilling_with_autocompletenew-password) for login forms you should use
```
    ...
    'name'  => 'password',
    'label' => 'Password',
    'type'  => 'password',
    'attributes' => [
        'autocomplete' => 'new-password',
     ],
    ...
```
on the password field only, this should work at least for modern chrome and firefox

**Comment by tabacitu** [comment]
Huh - I didn't know about that ```new-password``` thing. Thanks @ArroWsGM , very interesting - I thought it was a typo :-) Changed in my answer above too, in case someone copy-pastes it. Thanks!

**Comment by ArroWsGM** [comment]
@tabacitu 
> Changed in my answer above too
I think this not works on the email field, this attribute works only on password, and removes autocomplete from the entire form.
And it seems to autocomplete=off was fixed in the latest chrome version, but not in firefox
