### ISSUE TITLE
`checkLicenseCodeExists()` caused ` Class cache does not exist` Error

### ISSUE THREAD

**Issue by kiddtang** [Laravel-Backpack/Base#288]
### What I did:
in the `.env`  set `SESSION_DRIVER=redis` & `APP_ENV=staging`

### What I expected to happen:
Run without error

### What happened:
` Class cache does not exist` Error returned

### What I've already tried to fix it:
commented  `$this->checkLicenseCodeExists();` at `BaseServiceProvider.php`

You may refer this issue... i think it is similar situation...
https://laracasts.com/discuss/channels/laravel/class-cache-does-not-exist-error-when-use-redis-session-file-session-is-fine

**Comment by TheDeadCode** [comment]
Same error. Had to comment it.

**Comment by tabacitu** [comment]
Fixed in the latest version, thank you. Also it's been reported that buying and entering the license code fixes it: https://github.com/Laravel-Backpack/Base/issues/284 :-)

Cheers!
