### ISSUE TITLE
How to change or remove the /admin prefix

### ISSUE THREAD

**Issue by rafix** [Laravel-Backpack/Base#29]
Its possible to edit or remove the /admin prefix?

**Comment by tabacitu** [comment]
Hi @rafix ,

I know this might seem obvious to you, but I did NOT think of that :-)
I just pushed a fix for that. Thank you.

Basically, the only routes that use the ```admin``` prefix in Base are the ones defined in [BaseServiceProvider:69-79](https://github.com/Laravel-Backpack/Base/blob/master/src/BaseServiceProvider.php#L69-L79). You can now skip their setup altogether or change the prefix in your [config/backpack/base.php](https://github.com/Laravel-Backpack/Base/blob/master/src/config/backpack/base.php#L53-L63). 

A ```composer update``` will get you Backpack\Base v0.6.9, with this functionality.

Cheers!

**Comment by rafix** [comment]
Hi @tabacitu ,
Thanks for your rapid response development to my Issue :) but when I try to open the /dashboard route still redirect to /admin/login instead of /login.

Cheers!!

**Comment by tabacitu** [comment]
Damn. Right. Fixed in ```0.6.10```. Thank you!

**Comment by tabacitu** [comment]
(I closed the issue so it doesn't show up on my todos anymore, but feel free to continue writing here if you've discovering related problems)

**Comment by packytagliaferro** [comment]
@tabacitu  As of right now if I change `route_prefix` in the config file it works everywhere but the buttons. So Add button will still use `/admin/`  not the new prefix.
