### ISSUE TITLE
Having an option to show Firstname and lastname initials in Placehold option

### ISSUE THREAD

**Issue by nwaughachukwuma** [Laravel-Backpack/Base#290]
Hi @tabacitu is it possible to have both firstname and lastname initials in backpack_avatar placehold type e.g. CN for Chukwuma Nwaugha. This will be useful in apps with teams and members, just a way to further differentiate users by the placehold avatars. Thanks

**Comment by AbbyJanke** [comment]
Hello, as i responded on Gitter earlier you can define custom avatar preferences by editing the config/bacpack/base.php config file. In order to do the desired effect you will need to create a custom function thag uses the placehold.it api to add the desired letters.

**Comment by nwaughachukwuma** [comment]
Awesome! Thanks for the help

**Comment by nwaughachukwuma** [comment]
Hi @AbbyJanke I didn't get back to you on how I solved the problem. I don't know if there's a better way of doing this, but what worked for me was the following:

I went into vendor > backpack > base > src > helpers and changed the function

```
function backpack_avatar_url($user)
    {
        switch (config('backpack.base.avatar_type')) {
            case 'gravatar':
                return Gravatar::fallback('https://placehold.it/160x160/00a65a/ffffff/&text='.$user->name[0])->get($user->email);
                break;

            case 'placehold':
                return 'https://placehold.it/160x160/00a65a/ffffff/&text='.$user->name[0];
                break;

            default:
                return $user->{config('backpack.base.avatar_type')};
                break;
        }
    }
```

to 

```
function backpack_avatar_url($user)
    {
        switch (config('backpack.base.avatar_type')) {
            case 'gravatar':
                return Gravatar::fallback('https://placehold.it/160x160/00a65a/ffffff/&text='.$user->name[0])->get($user->email);
                break;

            case 'placehold':
                return 'https://placehold.it/160x160/00a65a/ffffff/&text='.$user->name[0];
                break;

            default:
                return $user->{config('backpack.base.avatar_type')}();
                break;
        }
    }
```

Take note of the parenthesis in the returned entity in the default switch. Then in my user model, I defined  a custom method that matches the avatar_type defined in config > backpack > base.php. The method returned 'https://placehold.it/160x160/00a65a/ffffff/&text='.$my_custom_variable;

I hope this helps someone else. If this is the right way to do it, then it should be written into the codebase. Thanks

**Comment by tabacitu** [comment]
Hi @nwaughachukwuma ,

Thanks for sharing your solution. But it's a big no-no to change files in the ```vendor``` folder in PHP. They will get overwritten when you do ```composer update```. 

So to anyone else looking for this in 3.4, I'd recommend you:
- make sure your ```User``` model does everything ```BackpackUser``` does (for password recovery);
- create an ```avatar()``` method on your User model that returns what you want;
- make sure Backpack is using _your_ User model in ```config/backpack/base.php```;
- make sure Backpack is using ```avatar``` as an avatar method in ```config/backpack/base.php```;

Hope it helps someone.
Cheers!

**Comment by nwaughachukwuma** [comment]
Hi @tabacitu you are very right that it's a no-no to change files in vendor folder. I tried the steps you mentioned but I got:

> __`App\User::avatar` must return a relationship instance. (View: C:\...\resources\views\layouts\master.blade.php)__

And that's because the method (avatar in your case) is being returned as 

>`$this->avatar`
>instead of 
>`$this->avatar()`

This was traced back to the helper file where the switch statement is returning a default:

```
default:
         return $user->{config('backpack.base.avatar_type')};
         break;
```

This was solved by returning

```
default:
         return $user->{config('backpack.base.avatar_type')}();
         break;
```
with parenthesis at the end.

I had written with the hope that it could be resolved at that level, and not to encourage the practice of making changes in a vendor file.

**Comment by nwaughachukwuma** [comment]
> Hi @tabacitu you are very right that it's a no-no to change files in vendor folder. I tried the steps you mentioned but I got:
> 
> > **`App\User::avatar` must return a relationship instance. (View: C:...\resources\views\layouts\master.blade.php)**
> 
> And that's because the method (avatar in your case) is being returned as
> 
> > `$this->avatar`
> > instead of
> > `$this->avatar()`
> 
> This was traced back to the helper file where the switch statement is returning a default:
> 
> ```
> default:
>          return $user->{config('backpack.base.avatar_type')};
>          break;
> ```
> This was solved by returning
> 
> ```
> default:
>          return $user->{config('backpack.base.avatar_type')}();
>          break;
> ```
> with parenthesis at the end.
> 
> I had written with the hope that it could be resolved at that level, and not to encourage the practice of making changes in a vendor file.

@tabacitu no reply?

**Comment by tabacitu** [comment]
Hi @nwaughachukwuma ,

You're right - there was that problem a while back but I can confirm it's been fixed in this last version, it's now:

```php
    function backpack_avatar_url($user)
    {
        $placeholder = 'https://placehold.it/160x160/00a65a/ffffff/&text='.$user->name[0];

        switch (config('backpack.base.avatar_type')) {
            case 'gravatar':
                if (backpack_users_have_email()) {
                    return Gravatar::fallback('https://placehold.it/160x160/00a65a/ffffff/&text='.$user->name[0])->get($user->email);
                } else {
                    return $placeholder;
                }
                break;

            case 'placehold':
                return $placeholder;
                break;

            default:
                return method_exists($user, config('backpack.base.avatar_type')) ? $user->{config('backpack.base.avatar_type')}() : $user->{config('backpack.base.avatar_type')};
                break;
        }
    }
```

Notice it returns ```avatar()``` if that method exists, otherwise it returns ```avatar```.

**Comment by nwaughachukwuma** [comment]
Awesome. Thanks
