### ISSUE TITLE
[Feature req] Should Base include an interface to manage users?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#291]
@eduardoarandah said on Gitter:

I've been thinking about this:
- Base enable users but doesn't give you a GUI
- PermissionManager give you the GUI for users, BUT gives you roles and permissions, which you may not want

Also, permission manager is harder to install
So, I think users should be part of the base install.
if they exist in database
it must exist a GUI to manage them
also...
permission manager should not be able to manage user data, like name, email and password
it's a different scope

![default-app](https://user-images.githubusercontent.com/1032474/40700286-98d564ee-63e1-11e8-8e90-5e696df3f200.png)
So, that should be the base installation
backpack enables users (always)
and, Admin middleware is all-or-nothing
so, this makes sense
![permissions](https://user-images.githubusercontent.com/1032474/40700302-a52f9fac-63e1-11e8-8812-775a36ae8f05.png)

And this is Permission Manager
(note that users is also an icon there)
Inside permission manager, you can see users but not edit them.
their permissions belong to a separate table.
If the user is installing permission manager, then he surely has the intention to
separate users, (if not, why would he install this?)
So, it makes sense to have another middleware "AdminMiddleware"
installed automatically (like I wrote in [my article](https://medium.com/@eduardoarandah/how-to-configure-permissions-in-laravel-76aa5a975cc3))
In that middleware we can leave commented out the role checking, so the user can use it as a template for his own rules.
I guess that leaves us with ready to use, out-of-the box solutions for each package.
Less tutorials, less questions asked
what do you think? does it make sense to you all?

my point is,
when installing PermissionManager, it makes sense to "publish" an AdminMiddleware to let the user change its logic to something more complex
(just a convenience for newbies who don't know what is a middleware)
(also a convenience to lazy programmers like me)

**Comment by tabacitu** [comment]
I agree a simpler package is necessary. To sum up package needs:

1. some projects need NO user admin
2. some projects need only simple user management (no permissions)
3. some projects need only permissions
4. some projects need only roles
5. some projects need roles & permissions

I think the above cover 99% of all use cases. And:
- 1 is covered by Base
- 3, 4, 5 are covered by PermissionManager (some with a few tweaks/hiding stuff though)
- 2 is not covered at all

I think a better way to cover 2 is to have a separate package, say UserManager. What do you think?

--

My thoughts behind this:
- I'm not a big fan of the idea of NOT letting admins edit name/email/password in PermissionManager (aka managing permissions separately from user data). It would be simpler for us, definitely. But I think it's difficult for the admin. When you need to add a user, you need to first add the user, then go to permisssions and roles and give him permissions and roles... Difficult, and something you need to remember...

**Comment by eduardoarandah** [comment]
You’re right on the edit user info in permission manager, there’s no point in hiding that

A separate package UserManager? Yes. Good idea

**Comment by eduardoarandah** [comment]
@tabacitu I already created the UserManager
however, I can't yet create packages in backpack organization
so, I put it here:

https://github.com/eduardoarandah/UserManager

(The namespace however, is backpack/UserManager)

Tell me if it is to be included in backpack or should I change namespace and upload myself to packagist

**Comment by eduardoarandah** [comment]
UserManager is not on packagist, 
quick reminder on how to use:

1. Create folder: packages/backpack
2. Clone
git clone https://github.com/eduardoarandah/UserManager.git
3. In to your composer.json:

```
"autoload": {        
...
        "psr-4": {
            "App\\": "app/",
            "Backpack\\UserManager\\": "packages/backpack/usermanager/src"
        }
    },
```

4. In config/app.php

` Backpack\UserManager\UserManagerServiceProvider::class,`

5. In sidebar_content.blade.php

`<li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/user') }}"><i class="fa fa-user"></i> <span>Users</span></a></li>`

**Comment by tabacitu** [comment]
Update: [UserManager](https://github.com/eduardoarandah/UserManager) is now on Packagist. Let's test-drive it for a few days, maybe a week, then include it in the official install process.

I think this is a great opportunity to test-drive something I've wanted for a while - decentralizing the Backpack packages ecosystem. Details here: https://github.com/Laravel-Backpack/Base/issues/292

**Comment by tabacitu** [comment]
Since there are two alternative packages to manage users:
- https://github.com/eduardoarandah/UserManager
- https://github.com/Laravel-Backpack/PermissionManager

It's probably best NOT to bloat up the main install, and let developers pick whatever they want.

Both packages are features in the docs, and in [our add-ons section](https://backpackforlaravel.com/addons). So I think it's safe to close this.
