### ISSUE TITLE
Password Reset route is not set

### ISSUE THREAD

**Issue by seandowney** [Laravel-Backpack/Base#296]
# Bug report

### What I did:
When submitting the form to request a password reset link 
![image](https://user-images.githubusercontent.com/652616/42229230-e67b1a6a-7edd-11e8-9378-fc62805f0d0e.png)
 
### What I expected to happen:
I expected to receive an email.

### What happened:
I get an error that the `password.reset` route is not set.

![image](https://user-images.githubusercontent.com/652616/42229000-478c1a6c-7edd-11e8-84ca-cbe55e47f40a.png)

### What I've already tried to fix it:
Since Laravel 5.4 the ResetPassword notification class is using a named route of `password.reset` see https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/Notifications/ResetPassword.php#L49

I believe in https://github.com/Laravel-Backpack/Base/blob/0.9.6/src/routes/backpack/base.php#L35 

`Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('backpack.auth.password.reset.token');` 

should be changed to 

`Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');`

I'm not sure how this affects #117 and #171

### Backpack, Laravel, PHP, DB version:
* Backpack/Base - 0.9.2 (the same applies up to 0.9.6)
* Laravel - 5.4+
* PHP 7.2

**Comment by AbbyJanke** [comment]
I believe this is likely because you are using custom login page from Laravel rather then the backpack login views. The backpack login view defines the password reset as the longer one so you can have multiple logins and not break backpack. See the `login.blade.php` file for backpack here:

https://github.com/Laravel-Backpack/Base/blob/master/src/resources/views/auth/login.blade.php

**Comment by seandowney** [comment]
Well the form appears where I enter the email address but the email with the reset link doesn't get sent.

**Comment by AbbyJanke** [comment]
Have you configured your mail driver in `config/mail.php` correctly? If you are on a local environment you will likely need to set it up correctly.

**Comment by seandowney** [comment]
In Laravel 5.3 the password reset notification used a different method to set the route in the email so it didn't expect the named route.
See https://github.com/laravel/framework/blob/5.3/src/Illuminate/Auth/Notifications/ResetPassword.php#L49

**Comment by AbbyJanke** [comment]
Yes, I am aware of the default laravel login route, but in looking at your screenshot you are using the default laravel auth views, which backpack does not install by default. Backpack has custom views using AdminLTE which have the correct route names and should look like this:

<img width="1420" alt="screen shot 2018-07-03 at 11 01 10 am" src="https://user-images.githubusercontent.com/487798/42236683-6c6512b2-7eb0-11e8-978c-39402f12c1b6.png">

In the end it is a fact you are creating a custom login page rather then using backpack's built in ones.

**Comment by AbbyJanke** [comment]
Okay, sorry I apologize i was confused thinking that it was a view issue not sending the password issue. I did just test it and got the same error. The answer though reviewing the code for Backpack is that we actually both missed a step when installing:

Step 4:
Make sure the reset password emails have the correct reset link by adding these to your User model:
before class name `use Backpack\Base\app\Notifications\ResetPasswordNotification as ResetPasswordNotification;` as a method inside the User class:

```php
  /**
   * Send the password reset notification.
   *
   * @param  string  $token
   * @return void
   */
  public function sendPasswordResetNotification($token)
  {
      $this->notify(new ResetPasswordNotification($token));
```

**Comment by seandowney** [comment]
Ahhh sorry. My bad all along 🙄

Thank you for spending the time to review it and sorry for the wasted time.

**Comment by AbbyJanke** [comment]
no worries, i missed it to clearly. helped me find an issue in my application. Glad we got it all figured out.

**Comment by seandowney** [comment]
Ah I see that in the readme of the Base project but I don't see it in the docs site - https://laravel-backpack.readme.io/docs/install-on-laravel-56

It should probably be added there too. 

Thanks again

**Comment by raoufOu** [comment]
you have only to change APP_URL=http://localhost whith http://your_projet.test/

**Comment by imomer** [comment]
> Okay, sorry I apologize i was confused thinking that it was a view issue not sending the password issue. I did just test it and got the same error. The answer though reviewing the code for Backpack is that we actually both missed a step when installing:
> 
> Step 4:
> Make sure the reset password emails have the correct reset link by adding these to your User model:
> before class name `use Backpack\Base\app\Notifications\ResetPasswordNotification as ResetPasswordNotification;` as a method inside the User class:
> 
> ```
>   /**
>    * Send the password reset notification.
>    *
>    * @param  string  $token
>    * @return void
>    */
>   public function sendPasswordResetNotification($token)
>   {
>       $this->notify(new ResetPasswordNotification($token));
> ```
> 
> https://github.com/Laravel-Backpack/Base/blob/master/src/app/Notifications/ResetPasswordNotification.php
> 
> Corrects that issue. I am abit upset that Taylor decided to hardcode the URL rather then making it a simple variable on the User model.. but thats the fix.

do anyone have a idea on how to override email template of backpack reset password?
