### ISSUE TITLE
Getting `too much recursion` JS error when clearing a filter

### ISSUE THREAD

**Issue by juniorgarcia** [Laravel-Backpack/Base#298]
# Bug report

### What I did:
Filtered my listing using the Backpack's default way

### What I expected to happen:
When a filter was removed, the table would reload with the filters updated.

### What happened:
I've got a `too much recursion` JavaScript error in Safari, Firefox and Chrome.
<details>
<summary>JavaScript stacktrace</summary>

| Function | Location |
| --- | --- |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| r | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:76:8 |
| fa | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:42:464 |
| S | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:31:18 |
| Sb | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:107:151 |
| <anonymous> | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:108:390 |
| iterator | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:99:241 |
| <anonymous> | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:108:356 |
| g/< | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:102:108 |
| dateInput< | http://app.test/admin/agenda:827:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| _trigger | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:7607 |
| clearDates | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:9953 |
| n/< | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:27314 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| n | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:26942 |
| <anonymous> | http://app.test/admin/agenda:841:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| dateInput< | http://app.test/admin/agenda:835:6 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| _trigger | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:7607 |
| clearDates | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:9953 |
| n/< | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:27314 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| n | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:26942 |
| <anonymous> | http://app.test/admin/agenda:841:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| dateInput< | http://app.test/admin/agenda:835:6 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| _trigger | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:7607 |
| clearDates | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:9953 |
| n/< | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:27314 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| n | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:26942 |
| <anonymous> | http://app.test/admin/agenda:841:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| dateInput< | http://app.test/admin/agenda:835:6 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| _trigger | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:7607 |
| clearDates | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:9953 |
| n/< | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:27314 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| n | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:26942 |
| <anonymous> | http://app.test/admin/agenda:841:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| dateInput< | http://app.test/admin/agenda:835:6 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| _trigger | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:7607 |
| clearDates | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:9953 |
| n/< | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:27314 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| n | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:26942 |
| <anonymous> | http://app.test/admin/agenda:841:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| dateInput< | http://app.test/admin/agenda:835:6 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
too much recursion[Learn More] jquery.min.js:2:69549
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| r | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:76:8 |
| fa | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:42:464 |
| S | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:31:18 |
| Sb | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:107:151 |
| <anonymous> | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:108:390 |
| iterator | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:99:241 |
| <anonymous> | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:108:356 |
| g/< | https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js:102:108 |
| dateInput< | http://app.test/admin/agenda:827:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| _trigger | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:7607 |
| clearDates | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:9953 |
| n/< | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:27314 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| n | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:26942 |
| <anonymous> | http://app.test/admin/agenda:841:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| dateInput< | http://app.test/admin/agenda:835:6 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| _trigger | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:7607 |
| clearDates | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:9953 |
| n/< | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:27314 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| n | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:26942 |
| <anonymous> | http://app.test/admin/agenda:841:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| dateInput< | http://app.test/admin/agenda:835:6 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| _trigger | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:7607 |
| clearDates | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:9953 |
| n/< | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:27314 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| n | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:26942 |
| <anonymous> | http://app.test/admin/agenda:841:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| dateInput< | http://app.test/admin/agenda:835:6 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| _trigger | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:7607 |
| clearDates | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:9953 |
| n/< | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:27314 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| n | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:26942 |
| <anonymous> | http://app.test/admin/agenda:841:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| dateInput< | http://app.test/admin/agenda:835:6 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| _trigger | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:7607 |
| clearDates | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:9953 |
| n/< | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:27314 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| n | http://app.test/vendor/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js:7:26942 |
| <anonymous> | http://app.test/admin/agenda:841:5 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:2571 |
| each | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:1238 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70117 |
| dateInput< | http://app.test/admin/agenda:835:6 |
| dispatch | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:41720 |
| add/y.handle | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:39774 |
| trigger | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:69549 |
| trigger/< | http://app.test/vendor/adminlte/bower_components/jquery/dist/jquery.min.js:2:70138 |

</details>

### What I've already tried to fix it:
- Updating packages via `composer update` command;
- Resetting the Crud controller to its initial state (only calling `$this->crud->setFromDb()`) and adding the filters;
- Removing every customization of the fields and columns and try to filter, then remove the filtering after that;
- Removing complex filters except of one whose type is `date` and filters directly from a table column used in the crud;
- Removing `public/vendor/backpack` then re-publishing my packages through `php artisan vendor:publish` command;

### Backpack, Laravel, PHP, DB version:
- backpack/base 0.9.3
- backpack/crud 3.4.11
- Laravel 5.6.26
- PHP 7.2.2
- MySQL 5.7.21

**Comment by tabacitu** [comment]
@juniorgarcia - that's very weird. I just tested it again and it seems to work fine on the latest version. There _was_ a bug with endless recurssion a few months back, but it was on the ```date_range``` filter, and it's been fixed. I also triple-checked all filters when we did that. Then and now - no endless loop for me.

**Can you please double-check that the ```composer update``` has run successfully?** You should _not_ have this issue on CRUD 3.4.21.

**Please delete everything from ```resources/views/vendor/backpack``` that you haven't customized. Especially the ```/crud/filters```** - that's where the bugfixes have happened. Notice I'm talking about _views_ here, not javascript/css files. In general, it's bad practice to publish the views you haven't customized - for every view you publish, you're forfeiting updates to one more file.

**Comment by tabacitu** [comment]
Hi there - since there’s no reply, I’ll assume you’ve gotten to the bottom of this. Let me know if you haven’t, and it’s an issue in the current version - we’ll reopen the issue. Cheers!

**Comment by tabacitu** [comment]
Hi there - since there’s no reply, I’ll assume you’ve gotten to the bottom of this. Let me know if you haven’t, and it’s an issue in the current version - we’ll reopen the issue. Cheers!

**Comment by tabacitu** [comment]
Hi there - since there’s no reply, I’ll assume you’ve gotten to the bottom of this. Let me know if you haven’t, and it’s an issue in the current version - we’ll reopen the issue. Cheers!

**Comment by tabacitu** [comment]
Hi there - since there’s no reply, I’ll assume you’ve gotten to the bottom of this. Let me know if you haven’t, and it’s an issue in the current version - we’ll reopen the issue. Cheers!

**Comment by tabacitu** [comment]
Hi there - since there’s no reply, I’ll assume you’ve gotten to the bottom of this. Let me know if you haven’t, and it’s an issue in the current version - we’ll reopen the issue. Cheers!

**Comment by tabacitu** [comment]
asff

**Comment by tabacitu** [comment]
Closing - hope you got to resolve this. If not, let me know and I'll reopen it. Cheers!
