### ISSUE TITLE
Login page "Remember Me" feature

### ISSUE THREAD

**Issue by BinaryBlock** [Laravel-Backpack/Base#30]
Does the "remember me" feature on the /Base Adminlte login form work?

I tried to do some digging into it... and the column exists in the DB table `Users.remember_token`.

I found in `.../vendor/backpack/base/src/app/Http/Controllers/Auth/AuthController.php` on line 153:
```PHP
Auth::guard($this->getGuard())->login($this->create($request->all()));
```
so I change it to:
```PHP
Auth::guard($this->getGuard())->login($this->create($request->all()), true);
```
because of this https://laravel.com/docs/5.2/authentication#remembering-users

*Did I do the right thing? Or, how should I properly be enabling this feature?*

Thank you in advance.

**Comment by tabacitu** [comment]
Hi @BinaryBlock ,

If you're refering to the "remember me" checkbox on the login screen - are you sure it didn't work in the first place? 'cause it does for me. And I just checked:
- Base's AuthController does NOT overwrite the login function;
- the login view is just a stylized version of Laravel's default;

So it **should** work out of the box. It's Laravel's default functionality.

------

What you've changed on line 153 refers to the auto-login that is done after user registration. And that one... I don't know... I don't think it should be done with "remember me" enabled in the Base package. I think the "remember me" functionality should only be used when the user chose to do so. It's pretty dangerous, leaving an admin logged in.

That being said, if that's what you were looking for, yes - that's the way to do it, with a second boolean parameter. I've done it before the same way and it worked like a charm.

Cheers!
