### ISSUE TITLE
Bugged.. adding php code before php starting tag

### ISSUE THREAD

**Issue by dave7280** [Laravel-Backpack/Base#303]
# Bug report

### What I did:

Follow quick-start. Install backpack + crud + file manager add a sample "tag" crud, all done 1:1 using quickstart guide.

### What I expected to happen:

Quick start should work. I followed guide 1:1 to test this library.

### What happened:

[image](https://user-images.githubusercontent.com/2826463/43617014-cf76beb0-96bf-11e8-9cc5-616a54017ada.png)

This is how this library adds a new resource.........

Also i spent few minutes trying to figure out what is default username and password to panel. Why is this not stated in manual, that you have to register new user?

### What I've already tried to fix it:

Move lines in file

### Backpack, Laravel, PHP, DB version:

5.6 lar, php 7.2,

**Comment by AbbyJanke** [comment]
Several issues I seem.

1) you did not state that you installed https://github.com/Laravel-Backpack/CRUD.

2) you placed your route in the wrong location.. Standard PHP requirements is your code has to be AFTER `<?php`

To make it work with Backpack you have to put it within the group:

```php
<?php

// --------------------------
// Custom Backpack Routes
// --------------------------
// This route file is loaded automatically by Backpack\Base.
// Routes you generate using Backpack\Generators will be placed here.

Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', config('backpack.base.middleware_key', 'admin')],
    'namespace'  => 'App\Http\Controllers\Admin',
], function () { 

Crud::resource('tag', 'TagCrudController');

}); 
```

This will look for it within your `App\Http\Controllers\Admin` folder within your base directory.

**Comment by dave7280** [comment]
The thing is that i didnt put the line manually... 

I didnt even modify routes, just ran quickstart guide. Then noticed that the text

"Crud::resource('tag', 'TagCrudController');" was all over my pages.

Perhaps the script is trying to inject the route definition to the file and fails to detect correct placement?

**Comment by AbbyJanke** [comment]
Oh thats knews ans would have been helpful up fromt you are using the injector commands. I will take a look at it in the morning when i am more away can nit feeling as yucky on the inside

**Comment by tabacitu** [comment]
Hi @dave7280 - thanks for bringing this up and @AbbyJanke for replying. 

It does turn out that the custom route command didn't work on all systems (unix & windows). I've just [pushed a fix for it](https://github.com/Laravel-Backpack/Base/commit/c63ac558583ff42f1801ab35a5f5e07bdd5392c5) - we now take a little more time to discover what the last line of the file is. From my tests, this works on all systems now.

You'll be able to get this update in a few hours with a ```composer update```, after I bundle it with a few more changes.

Thanks. Cheers!
