### ISSUE TITLE
Backpack not using database driver from Admin registration.

### ISSUE THREAD

**Issue by XEQTIONR** [Laravel-Backpack/Base#307]
# Bug report

### What I did:
Using backpack for admin login which is separate from regular user login. Only I am the admin so just using a database driver for admins 
`'admins' => [
          'driver' => 'database',
          'table' => 'admins'
        ],`

### What I expected to happen:
I expected registration to work.
### What happened:
When I try to register as an admin. I get an error and its looking for the default user class.  Please note : LOGIN works. But REGISTRATION doesn't. Below I describe how I was able to register so that I could test login.
### What I've already tried to fix it:
I got around the situation by changing $table property from 'users' to 'admins' which is the name of my table on the BackPackUser class in the vendor files. But, I dont know why it's not using the db driver from the auth.php config file. 
### Backpack, Laravel, PHP, DB version:
Backpack  base v 0.9.6 crud v 3.4.27
Laravel v 5.5.40
PHP v 7.2.8
DB Mysql Server 5.7.23

**Comment by AbbyJanke** [comment]
In the backpack/base.php config file there is a setting called “guard” have you set to your new guard that you setup in the auth config?

**Comment by XEQTIONR** [comment]
in base.php 

`'guard' => 'admin',`

in auth.php

```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],

        'admin' => [
          'driver' => 'session',
          'provider' => 'admins',
        ],
```

```
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Gamer::class,
        ],

        'admins' => [
          'driver' => 'database',
          'table' => 'admins'
          //'model' => Backpack\Base\app\Models\BackpackUser::class,
        ],
    ]
```
