### ISSUE TITLE
Custom "add button" link e redirection with query string

### ISSUE THREAD

**Issue by juniorgarcia** [Laravel-Backpack/Base#309]
I have a listing CRUD page which has an entity ID in the URL to make a filter in that listing, like: `http://myapp.test/admin/entities?related_entity_id=10`

When I add a new `Entity`, I have to pass somehow the URL's related_entity_id parameter value to the create page and use it in a hidden input to make some relationship.

How can I do that?

**Comment by juniorgarcia** [comment]
Guys, looking at the documentation I figures out a way of doing that:

In my `CustomCrudController.php` on the `setup` method, I remove the default `create` button, then add my custom button, which Is a view with the desired link:

```php
public function setup(){
  // ...
  $this->crud->removeButton('create', 'top');
  $this->crud->addButton('top', 'create-price', 'view', 'vendor/backpack/crud/buttons/myCustomButton');
}
```

Then, at my custom button view:

```blade
// resources/views/vendor/backpack/crud/buttons/myCustomButton.blade.php 
@if ($crud->hasAccess('create'))
  <a href="{{ url($crud->route.'/create?product_id=' . $crud->request->product_id) }}"
     class="btn btn-primary ladda-button" data-style="zoom-in">
      <span class="ladda-label">
          <i class="fa fa-plus"></i> {{ trans('backpack::crud.add') }} {{ $crud->entity_name }}
      </span>
  </a>
@endif
```

The problem now is: when I save / update the model, my redirection goes back without a query with a previous filter. Like this:

– My URL is: http://myapp.test/admin/entities?related_entity_id=10
– When I hit "create" button, it becomes: http://myapp.test/admin/create?related_entity_id=10
– When I save / update the entity it redirects to http://myapp.test/admin/entities (without the initial filter, which causes the admin to list all the entries)

Is there a way to controle a redirection to a filtered view?

**Comment by tabacitu** [comment]
@juniorgarcia , you could change ```$this->crud->route```, that's where you're being redirected. So you should be able to do something like ```$this->crud->route = $this->crud->route . '?product_id=' . $crud->request->product_id;``` in your ```create()``` and ```update()``` methods.

Going to close the issue, as it doesn't look like a bug.

Cheers! Hope it helps.
