### ISSUE TITLE
how to set language？

### ISSUE THREAD

**Issue by ryan5217** [Laravel-Backpack/Base#312]
# Bug report

**Comment by tabacitu** [comment]
Backpack uses the default Laravel language. So you just need to change your ```locale``` in ```config/app.php```.

Cheers!

**Comment by vkovic** [comment]
Is there a way to use different locale than one defined in the `app.php` file under `locale` key.

I'm using local website locale for the app (website) and i would like to leave admin to be in english.

Thanks!
