### ISSUE TITLE
Changing dashboard

### ISSUE THREAD

**Issue by denbatte** [Laravel-Backpack/Base#32]
I may be missing something but I have troubles customizing the dashboard.
Is it possible to point the 'admin/dashboard' route to a custom controller?

```
Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin'], function() {
    Route::get('dashboard', 'DashboardController@dashboard');
    Route::get('dash', 'DashboardController@dashboard');
});
```

'dash' works perfectly but 'dashboard' does not.

**Comment by denbatte** [comment]
I just found my own answer.
For future reference:
> You have to make sure the order of the service providers in `config/app.php` is correct. The "RouteServiceProvider" is loaded AFTER the BackPack base one.

**Comment by warisarain** [comment]
Hi,
how to customize admin dashboard? I was reading this post to add custom things to dashboard but I am not getting where to put new path and  dashboardController
please one can help me to do this
Thanks
