### ISSUE TITLE
MultiAuthCommand-BackPack setup backpack panel for any guard in a single click

### ISSUE THREAD

**Issue by iMokhles** [Laravel-Backpack/Base#320]
Hey everyone,

been a while, hope things are going well for the next release.
I created this command to help Backpack users/developers etc to make our lovely Backpack package flexible so rather than accessing Backpack admin panel through a single guard, with this package you can create multiple admin panel for different guards.
the command is really simple to setup and use

* follow my tutorial here [MultiAuthCommand-BackPack](https://github.com/iMokhles/MultiAuthCommand-BackPack)

I wish that we integrate this command officially with base or crud package.

**Comment by tabacitu** [comment]
Hi @iMokhles - sorry for not getting to this sooner. Thanks for creating a backpack package! 

I’m afraid I don’t quite understand what it does though… not from your comment and not from its docs… could you please explain a little further? Thanks!
