### ISSUE TITLE
Can't translate email content for ResetPasswordNotification

### ISSUE THREAD

**Issue by Lysanthius** [Laravel-Backpack/Base#322]
# Bug report

### Backpack, Laravel, PHP, DB version: 

- backpack/base : 0.9.9
- backpack/crud: 3.4.35
- laravel/framework: 5.7.8
- PHP: 7.2.8
- DB: SQL 5.7.23

**Comment by tabacitu** [comment]
Hi @Lysanthius - you’re totally right, thank you for reporting this issue. I’ve just pushed a complete fix to this - ```composer update``` should fix it for you. You might need to update the language file for your desired language, though.

Thanks again.
Cheers!
