### ISSUE TITLE
Laravel 5.7

### ISSUE THREAD

**Issue by JustJeremy** [Laravel-Backpack/Base#331]
When will this be ready for 5.7+?
This is the only package holding me up from going to the latest version of laravel. At least this is the only one it chokes on so far, I don't know if the rest of the backpack stuff will choke or not. It stops on this one.

**Comment by AbbyJanke** [comment]
What issues are you having on 5.7? I am running it with no issues?

**Comment by tabacitu** [comment]
Hi @JustJeremy ,

Actually it’s been working on L5.7 since it was out - [check our composer.json](https://github.com/Laravel-Backpack/Base/blob/master/composer.json#L21).

If you’re not able to upgrade to 5.7, it might be you’re requiring an old version of Backpack/Base and Backpack/CRUD, and might need to [upgrade from CRUD 3.3 to CRUD 3.4](https://backpackforlaravel.com/docs/3.4/upgrade-guide).

**Comment by bilfeldt** [comment]
@tabacitu If [Backpack/Base](https://github.com/Laravel-Backpack/Base) and [Backpack/CRUD](https://github.com/Laravel-Backpack/CRUD) is working with L5.7, then I suggest updating the text three places:

**Documentation**
The requirements section in the documentation says:
> Laravel 5.5 or 5.6
https://backpackforlaravel.com/docs/3.4#requirements

**Github repo for Backpack/Base**
The title of the installation section (and the link itself) is called:
> Install on Laravel 5.6 or 5.5
https://github.com/Laravel-Backpack/Base#install-on-laravel-56-or-55

**Github repo for Backpack/CRUD**
The introduction to the Github repository says:
> Build a custom admin interface for your Eloquent models, using Laravel 5.2 to 5.6
https://github.com/Laravel-Backpack/CRUD

Hope this can be used.

**Comment by tabacitu** [comment]
Just closed the issue since I consider it solved - now I understand it must have been confusing to NOT see 5.7 plastered all over the docs. @JustJeremy , let me know if you don’t think this is the case and still have issues upgrading to 5.7, and we’ll reopen it.

**Comment by gedwu** [comment]
> Just closed the issue since I consider it solved - now I understand it must have been confusing to NOT see 5.7 plastered all over the docs. @JustJeremy , let me know if you don’t think this is the case and still have issues upgrading to 5.7, and we’ll reopen it.

https://backpackforlaravel.com/docs/3.4/installation
"that you have a working installation of Laravel 5.6 (you don't need a fresh install for Backpack, you can use existing projects);"

You should update here also

**Comment by tabacitu** [comment]
Done! Thank you @gedwu !
