### ISSUE TITLE
Compatibility with Laravel 5.3

### ISSUE THREAD

**Issue by mabilbao** [Laravel-Backpack/Base#34]
Hi Guys,

I have problems when I try to install Backpack/Base in my Laravel 5.3.

Laravel 5.2 is mandatory yet:
https://github.com/Laravel-Backpack/Base/blob/master/composer.json#L23

The error message returned by composer install shows that cannot be installed in laravel 5.3:
```
Problem 1
    - Installation request for backpack/base ^0.6.16 -> satisfiable by backpack/base[0.6.16].
    - backpack/base 0.6.16 requires laravel/framework 5.2.* -> satisfiable by laravel/framework[5.2.41, 5.2.x-dev, v5.2.0, v5.2.0-beta1, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.40, v5.2.42, v5.2.43, v5.2.44, v5.2.45, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9] but these conflict with your requirements or minimum-stability.
```

Thanks for the help!

**Comment by tabacitu** [comment]
Hi @mabilbao ,

All Laravel 5.3 compatibility work was on a different branch - that's why it errored. I've just finished the Laravel 5.2 to 5.3 upgrade and it's on master now (try ```Backpack\Base v0.7.0```). It should work well. 

Here's the full composer requirement list for Backpack\Demo, for example:
```json
    "require": {
        "laravel/framework": "5.3.*",
        "backpack/base": "^0.7.0",
        "backpack/crud": "^3.1.0",
        "backpack/backupmanager": "^1.1",
        "backpack/logmanager": "^2.3",
        "backpack/settings": "^2.0",
        "backpack/pagemanager": "^1.1",
        "backpack/MenuCRUD": "^1.0",
        "backpack/newscrud": "^2.1"
    },
```

Let me know if you encounter any issues.

Cheers!

**Comment by wymedia** [comment]
I could install it on 5.3 without issues.

**Comment by mabilbao** [comment]
@tabacitu Thanks! I could install it without issues after the change :)
