### ISSUE TITLE
HasManyThrough bug? field backpack_user_id

### ISSUE THREAD

**Issue by cmarfil** [Laravel-Backpack/Base#344]
Hello, I have found a problem using hasManyThrough with backpack installed.

# Bug report

### What I did:

User Model:

```php
    /**
     * User community member relationship
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    function memberCommunities(){
        return $this->hasManyThrough('App\Community', 'App\CommunityUser');
    }
```

Then from controller:

```php
$myCommunities = Auth::user()->memberCommunities;
```

### What I expected to happen:

Get communities relationship.

### What happened:

`
Illuminate \ Database \ QueryException (42S22)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'community_users.backpack_user_id' in 'field list' (SQL: select `communities`.*, `community_users`.`backpack_user_id` from `communities` inner join `community_users` on `community_users`.`id` = `communities`.`community_user_id` where `community_users`.`deleted_at` is null and `community_users`.`backpack_user_id` = 3 and `communities`.`deleted_at` is null)
`

### Backpack, Laravel, PHP, DB version: 
Backpack ^3.4
Laravel 5.7.*
PHP 7.2

Why eloquent is looking for field "backpack_user_id"?
This field doesn't exists..  I searched inside all project and nothing.

Any ideas?
Thanks!

**Comment by tabacitu** [comment]
What @pxpm said :-)

I'd add that there's _definitely_ no ```backpack_user_id``` in Backpack, we've _never_ use a database column like that. Could be something in _your_ code though.

Sorry I can't be of more help.
Cheers!

PS. Please let me know and we'll reopen this issue if it's indeed a Backpack bug. I'm wrong sometimes :-)
