### ISSUE TITLE
Use separate sessions for admin&user authentication

### ISSUE THREAD

**Issue by Dakaa** [Laravel-Backpack/Base#346]
> That's it. Backpack will now use a separate session for the admin login. You can be logged in with Admin X and User Z at the same time, and log out Admin X without logging out the user too.

This is not true, if you log out `User Z` **FIRST**, it will log out `Admin X` too.

**Comment by tabacitu** [comment]
Hi @Dakaa ,

I just checked, you're right, that _does_ happen with the stock Laravel auth. If you log out ```User Z``` first, Laravel will log out ```Admin X``` too. **However, that's not within our control** (the backpack team). It has to do with how the _user_ authentication is done (not _admin_) - and it could be different from project to project. So there's no bug fix we can push to Backpack to resolve this issue, I'm afraid.

But you _can_ follow the steps below to fix this in your project, if you're using the stock Laravel auth (generated with ```php artisan make:auth```.

Hope it helps.
Cheers!

----

In the stock Laravel auth, the ```logout()``` method deletes the entire session, not only the information about the user. To fix this, in the stock ```app/Http/Controllers/Auth/LoginController.php```, you can:
1. ```use Illuminate\Http\Request;```
2. Overwrite the logout method with exactly the same code, except the line that invalidates the session. At the moment of writing, (Laravel 5.7) the code for you a working logout method, that doesn't delete the entire session, would be:

```php

    /**
     * Log the user out of the application, without deleting the entire session.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function logout(Request $request)
    {
        $this->guard()->logout();

        return $this->loggedOut($request) ?: redirect('/');
    }
```
