### ISSUE TITLE
Class App\Http\Controllers\Admin\AdminController does not exist

### ISSUE THREAD

**Issue by nathanielks** [Laravel-Backpack/Base#36]
The docs reference adding the following code to the routes file:

```php
<?php

// Admin Interface Routes
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function()
{
    Route::get('dashboard', 'Admin\AdminController@index');

    // [...] other routes

    // Dick CRUD: Define the resources for the entities you want to CRUD.
    CRUD::resource('tag', 'Admin\TagCrudController');
});
```

Here's what's weird: _this worked just fine up until a few minutes ago._ I've since had to replace the AdminController line with:

```php
Route::get('dashboard', '\Backpack\Base\app\Http\Controllers\AdminController@dashboard');
```

I don't know what, why, or how, but I can't get it to go back. Just posting this in case others experience it as well. (FWIW I reverted all my changes in git and cleared the route cache just in case. Still nothing).

**Comment by tabacitu** [comment]
Hi @nathanielks ,

Backpack\Base [already has the ```admin/dashboard``` route registered](https://github.com/Laravel-Backpack/Base/blob/master/src/BaseServiceProvider.php#L80). That route _should_ work out of the box.

The code above is in case you need to modify the dashboard (I usually do) - it overwrites the route so it goes to your a custom controller (in this example, ```app/Http/Controllers/Admin/AdminController```). If you don't need to customize the dashboard, you should just be able to remove that route entirely from your routes file and Backpack\Base will forward ```your-app-name/admin/dashboard``` to  ```\Backpack\Base\app\Http\Controllers\AdminController@dashboard```. Does that not work for you?

Cheers!

**Comment by tabacitu** [comment]
P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by Frasaccordi** [comment]
how can we add middleware to route that work out of the box? like user, permission and role that not in routes/web.php. thats route is work but i dont know to middleware it, let say, i want people with operator role is blocked from accessing user crud, role crud, and permission crud page. i cant put that route in middleware group because that routes is not in web.php
