### ISSUE TITLE
Laravel Horizon with backpack guard

### ISSUE THREAD

**Issue by mauxtin** [Laravel-Backpack/Base#365]
I am trying to use Laravel Horizon with the Backpack guard without success till now.

I tried both with a Horizon::auth as well as with the Gate.

```
        Horizon::auth(function ($request) {
            dd(auth(backpack_guard_name())->user(), backpack_user()); // null, null
            
            return app()->environment('local') ||
                Gate::check('viewHorizon', [backpack_user()]);
        });

        Gate::define('viewHorizon', function ($user) {
            dd(backpack_user()); // null
            return backpack_user()->isAdmin();
            return $user->isAdmin();
        });

```

I also removed the web middleware from config/horizon.php and added `admin` (did not change the `middleware_key` in backpack/base.php)
```
    'middleware' => ['admin'],
```

I basically want to allow horizon to be accessible from the backpack admins. I am also using the default CheckIfAdmin class from the basepack tutorial to check for the isAdmin() method on the user.

```
    // The classes for the middleware to check if the visitor is an admin
    // Can be a single class or an array of clases
    'middleware_class' => [
        App\Http\Middleware\CheckIfAdmin::class,
    ],

    // Alias for that middleware
    'middleware_key' => 'admin',
```
Any ideas if this is achievable or if I am missing something here?

**Comment by tabacitu** [comment]
Sorry I can't be of any help @mauxtin - have never tried this myself. Cheers!

**Comment by mpixelz** [comment]
@mauxtin im having the same issue with telescope.. auth()->user, $user, backpack()->user() all returns null.
any fix?

**Comment by tabacitu** [comment]
@mpixelz where are you trying ```backpack_user()``` and it isn't working? In what file? Is it possible that file is loaded before Backpack gets a chance to be booted?

**Comment by mauxtin** [comment]
I don't really remember what was the problem but this is what I currently have and works great.

```
    protected function authorization()
    {
        $this->gate();

        Horizon::auth(function ($request) {
            return app()->environment('local') || (backpack_auth()->check() && backpack_user()->isAdmin());
        });
    }
   protected function gate()
    {
        Gate::define('viewHorizon', function ($user) {
            /** @var User $user */
            return $user->isAdmin();
        });
    }
```

**Comment by mpixelz** [comment]
@tabacitu 
hi
its in `App\Providers\TelescopeServiceProvider` function name is gate
$user variable undefined and if i try to define it using backpack_user() or backpack_auth() it doesn't.

**Comment by mauxtin** [comment]
Can you post your `config/app.php`?

**Comment by imran-concise** [comment]
You can use the gate as normal if you change your default guard to backpack.
`config/auth.php`
```
    'defaults' => [
        'guard' => 'backpack',
        'passwords' => 'users',
    ],
```
