### ISSUE TITLE
Cannot install on Laravel 5.7

### ISSUE THREAD

**Issue by Dalot** [Laravel-Backpack/Base#367]
# Bug report
In the docs it is referred that the package is functional in Laravel 5.7, although I cannot composer require the package
### What I did:
`composer require backpack/crud`
### What I expected to happen:
Some kind of success message by composer
### What happened:
`- backpack/base 1.1.1 requires laravel/framework 5.8.* -> satisfiable by laravel/framework[5.8.x-dev].`
 `- Conclusion: don't install laravel/framework 5.8.x-dev`
### What I've already tried to fix it:
Searched closed and open issues here but did not find anything relevant. I did see that this happened 1 or 2 years ago with version 5.4 and it was resolved. I also do not see anyone reporting any problem on installing at this version so, not sure what I'm doing wrong.
### Backpack, Laravel, PHP, DB version:
- None

EDIT: Typo

**Comment by Dalot** [comment]
I was able to solve this by manually installing backpack base through here https://laravel-backpack.readme.io/docs/frequently-asked-questions#section-how-do-i-manually-install-base

And then manually inserted `"backpack/crud": "3.5.*"` into `composer.json` , then
`composer update`

And finally,
`php artisan backpack:crud:install`

**Comment by tabacitu** [comment]
Thank you for sharing your solution @Dalot ! Indeed, the latest version of Backpack requires Laravel 5.8 - I'll remove the wrong mention of 5.7 etc ASAP.

Cheers!
