### ISSUE TITLE
[Issue]unable to go to dashboard

### ISSUE THREAD

**Issue by LaurencevdWel** [Laravel-Backpack/Base#368]
# Bug report

### What I've already tried to fix it: look at the routes

If I want to log in I get redirected to the login page, I dont know why this happens.

this is what I recieve:
![image](https://user-images.githubusercontent.com/35997008/55788183-1ee02880-5ab8-11e9-958e-fe3bf39759e6.png)

**Comment by pxpm** [comment]
No BP version, no DB Info, no PHP info.

IMO it might be worth follow the login process and do some dd() to check why you are beeing redirected back to login. 

Maybe guards ?

**Comment by LaurencevdWel** [comment]
I already found the issue, there was something wrong in my database
