### ISSUE TITLE
add Dashboard

### ISSUE THREAD

**Issue by guillermohaad** [Laravel-Backpack/Base#37]
someone can tell me how to add Dashboard on the homepage from queries to the database? I attach an example:

![dashboard](https://cloud.githubusercontent.com/assets/12921805/18556154/23148e10-7b30-11e6-825a-24f1f0c7c7f1.png)

**Comment by tabacitu** [comment]
Hi @guillermohaad ,

You can customize the existing blank dashboard by creating a new route in your project. That would overwrite the existing route in the package. So you'd have:
```php
Route::get('/dashboard', 'DashboardController@index');
```
and then handle everything in this new controller, ```DashboardController```.

If the view you use ```@extends("backpack::layout")``` you will keep the menu and overall look of the rest of the admin panel. Take a look at the [dashboard.blade.php](https://github.com/Laravel-Backpack/Base/blob/master/src/resources/views/dashboard.blade.php) to get an idea. You could then use the [AdminLTE dashboard](https://almsaeedstudio.com/themes/AdminLTE/index2.html) elements, which are already loaded in your project.

--

Please note you might need to place ```App\Providers\RouteServiceProvider::class,``` after ```Backpack\Base\BaseServiceProvider::class,``` in your ```config/app.php``` in order for the route to be overwritten.

Cheers!

**Comment by guillermohaad** [comment]
thanks friend @tabacitu for his teachings

**Comment by yoshkin** [comment]
@tabacitu
After all steps in FAQ https://laravel-backpack.readme.io/docs/frequently-asked-questions
I get "Cannot redeclare class App\Http\Controllers\DashboardController"

Why ?

**Comment by digzit** [comment]
UPDATE i fixed it:
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
