### ISSUE TITLE
Gutenberg support?

### ISSUE THREAD

**Issue by coccoinomane** [Laravel-Backpack/Base#370]
Hello!

I was wondering if there’s any plan to add Gutenberg to the list of supported editors?

Laravel Nova is considering it => https://github.com/tightenco/nova-package-development/issues/40

There are already APIs to bind Gutenberg to Laravel => Laraberg => https://github.com/VanOns/laraberg

See also => https://wptavern.com/laraberg-a-gutenberg-implementation-for-laravel-is-now-in-beta

Thank you!
Guido

**Comment by ikkebra** [comment]
It is being considered for the next version: https://github.com/Laravel-Backpack/CRUD/issues/1872
