### ISSUE TITLE
Not Auth with Socialite

### ISSUE THREAD

**Issue by lbottoni** [Laravel-Backpack/Base#373]
# Bug report

### i want auth my user in panel from social:

	namespace App\Http\Controllers\Auth;
	
	use Illuminate\Http\Request;
	use App\Http\Controllers\Controller;
	use Illuminate\Support\Str;
	use Laravel\Socialite\Facades\Socialite;
	use Illuminate\Support\Facades\Auth;
	use Illuminate\Support\Facades\DB;
	use App\Models\BackpackUser;
	use Illuminate\Support\Facades\Hash;
	
	//class AuthController extends Controller
	//{
	//    //
	//}
	class AuthController extends Controller
		{
		protected $redirectTo = '/admin/dashboard';
	
		/**
		 * Redirect the user to the GitHub authentication page.
		 * https://ilmiocampionato.localhost/admin/auth/facebook
		 *	Some methods which were generated with the app
		 *	socialite
		 * https://laravel.com/docs/5.8/socialite#installation
		 *_ Redirect the user to the OAuth Provider.
		 *
		 * @return \Illuminate\Http\Response
		 */
		public function redirectToProvider($provider)
			{
				return Socialite::driver($provider)->redirect();
			}
	
		/**
		 * _ Obtain the user information from provider.  Check if the user already exists in our
		 * _ database by looking up their provider_id in the database.
		 * _ If the user exists, log them in. Otherwise, create a new user then log them in. After that
		 * _ redirect them to the authenticated users homepage.
		 * _
		 * _ @return Response
		 * _/
		 * public function handleProviderCallback($provider)
		 * {
		 * $user = Socialite::driver($provider)->user();
		 *
		 * $authUser = $this->findOrCreateUser($user, $provider);
		 * Auth::login($authUser, true);
		 * return redirect($this->redirectTo);
		 * }
		 *
		 * /**
		 * _ If a user has registered before using social auth, return the user
		 * _ else, create a new user object.
		 * controlla che esiste lo user con i dati ricevuti
		 *
		 * _ @param  $user Socialite user object (oggetto ritornato dall'auth di fb, g+,etc...
		 * _ @param $provider Social auth provider (facebook,googleplus,etc...)
		 * _ @return  User
		 */
		public function findOrCreateUser($userProvider, $provider)
			{
				//verifico se esiste l'utente come email
				$UserModel=BackpackUser::where("email",$userProvider->getEmail())->first();
				if(!$UserModel)
					{
					//l'utente non ha mai fatto accesso al sito
					#◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙
					#					USER NUOVO CON DATI FACEBOOK
					#◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙
					try
						{
						$UserModel = BackpackUser::create(['name' => $userProvider->getName(),
												   'email' => $userProvider->getEmail(),
												   'provider' => $provider,
												   'provider_id' => $userProvider->getId(),
												   'avatar' => $userProvider->getAvatar(),
												   'avatar_original' => $userProvider->getAvatar(),
												   'avatar_original' => $userProvider->avatar_original,
												   "email_verified_at"=>now()->timestamp,//verifica fatta in quanto arriva dai social
												   'remember_token' => $userProvider->token,
												   "password" => Hash::make(Str::random(8)),
												   "user_type" => "player"
						]);
						$UserModel->markEmailAsVerified();
						$UserModel->assignRole('player');
						} catch (\Exception $e)
						{
						//dd($e);
						DB::rollback();
						throw $e;
						}
					DB::commit();
					return $UserModel;
					}
				else
					{
				//l'utente è già registrato e potrebbe essere registrato come:
					// local || tramite provider (google, fb, etc..)
				//non aveva social auth ma esisteva nel db, quindi gli registro le info del provider
				# ◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙ USER ESISTENTE◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙◙
				DB::beginTransaction();
				try
					{
					$UserModel->provider = $provider;
					$UserModel->provider_id = $userProvider->getId();
					$UserModel->remember_token = (@$userProvider->user["token"]===null)?$userProvider->token:$userProvider->user["token"];
	
					//controllo se tutti i dati anagrafici esistono già
					if (!$UserModel->name)
						{
						$UserModel->name = $userProvider->getName();
						}
					if (!$UserModel->avatar || $UserModel->avatar===config("voyager.user.default_avatar"))
						{
						$UserModel->avatar = $userProvider->getAvatar();
						}
	
					$UserModel->save();
					} catch (\Exception  $e)
					{
					//dd("QueryException", $e);
					DB::rollback();
					throw $e;
					}
				DB::commit();
				return $UserModel;
				}
			}
		public function handleProviderCallback($provider/*, $provider*/)
			{
				$provider = trim(strtolower($provider));
				try
					{
					$userProvider=Socialite::driver($provider)->stateless()->user();
					//$userProvider = Socialite::driver($provider)->user();
	
					} catch (\Exception $e)
					{
					throw $e;
					}
				//controllo che esiste l'id del provider in base al provider stesso
				$UserModel = $this->findOrCreateUser($userProvider, $provider);
				Auth::login($UserModel);
				backpack_auth();
	//			return redirect("/mt/home");
				return redirect(backpack_url('dashboard'));
			}
		/**
		 * Get the guard to be used during logout.
		 *
		 * @return \Illuminate\Contracts\Auth\StatefulGuard
		 */
		protected function guard()
			{
				return backpack_auth();
			}
	
		}

### What I've already tried to fix it:
- change it in config/auth.php the Model User in BackpackUser
- in AuthController used Auth::login($UserModel); with or wothout backpack_auth();

**Comment by tabacitu** [comment]
Sorry @lbottoni - I have to close this. We keep Github for _bugs only_. We don't have a support forum but people regularly help out on StackOverflow using the ```backpack-for-laravel``` tag. https://stackoverflow.com/questions/tagged/backpack-for-laravel

I'll give it a shot though: Sounds to me like you haven't used the Backpack guard. If you create a different auth process than the one Backpack provides, make sure you also use the Backpack guard. Otherwise ```backpack_user()``` and ```backpack_auth()``` helpers won't work. Check out the LoginController in Base - take inspiration from there. It loads the proper guard.

Hope it helps.
Cheers!

**Comment by lbottoni** [comment]
solution: backpack_auth()->login($UserModel);

**Comment by lbottoni** [comment]
in documentation is complicate understand it (myabe fot me) that backpack_auth is it a alias of Auth 

sorry, i'm young in laravel
