### ISSUE TITLE
4.0 Changes

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#378]
Changes needed in Base:
- [x] themes
- [x] asset pipeline in php OR laravel mix file
- [x] new default theme, that uses Bootstrap 4 - https://github.com/Laravel-Backpack/Base/pull/380
- [ ] use webfactor/generators instead of backpack/generators and laracasts/generators

Documentation:
- [x] changelog
- [x] upgrade guide
- [ ] how to create a new Backpack theme
- [ ] how to generate CRUDs using Backpack v4
- [ ] how to load assets in Backpack v4

**Comment by pxpm** [comment]
@tabacitu it might worth checking [igaster theme package](https://github.com/igaster/laravel-theme)

It provides theme separation of theme with asset management, in other thread we talked about orchestral/asset, and this package can be extended if used with orchestral. Provides additional @css @js blade directives to replace the Facade::add() call.

**Comment by tabacitu** [comment]
Wow, looks like they've done a great job. Thanks for surfacing this @pxpm . I'll take a harder look at it but so far I have one big concern: that it overwrites the View facade. That means developers will also need to use themes in their front-end, not just back-end (Backpack). This could be problematic, since themes on the front-end don't make sense for a lot of people...

**Comment by pxpm** [comment]
Np, as far as i understood their docs, they have a fallback to default laravel in case of themes not found in theme directory ?

I found this peace of code of theirs, maybe it's what we are looking for:
`if (file_exists($fullPath = public_path($fullUrl))) {
            return $fullUrl . $params;
        }
        // If not found then lookup in parent's theme asset path
        if ($parentTheme = $this->getParent()) {
            return $parentTheme->url($url);
        }
        // No parent theme? Lookup in the public folder.
        else {
            if (file_exists(public_path($baseUrl))) {
                return "/" . $baseUrl . $params;
            }`

**Comment by thomaslemoine** [comment]
> Changes needed in Base:
> 
>     * [ ]  themes
> 
>     * [ ]  asset pipeline in php OR laravel mix file
> 
>     * [ ]  new default theme, that uses Bootstrap 4
> 
>     * [ ]  use webfactor/generators instead of backpack/generators and laracasts/generators
> 
> 
> Documentation:
> 
>     * [ ]  changelog
> 
>     * [ ]  upgrade guide
> 
>     * [ ]  how to create a new Backpack theme
> 
>     * [ ]  how to generate CRUDs using Backpack v4
> 
>     * [ ]  how to load assets in Backpack v4

Add email verification after registration ?

**Comment by tabacitu** [comment]
Might be a good idea. Thank you @thomaslemoine . We'll consider it.

**Comment by tabacitu** [comment]
v4 has been out for a while now, we've even launched v4.1. So let's close this 😄
