### ISSUE TITLE
Exception with empty user name

### ISSUE THREAD

**Issue by hey-red** [Laravel-Backpack/Base#379]
# Bug report

### What I did:
Navigate /admin/dashboard with empty username.
### What I expected to happen:
Succesfully log in into panel.
### What happened:
I got an ErrorException

![1](https://user-images.githubusercontent.com/1738743/58378709-14fb8180-7fa1-11e9-8b82-1136686ba0fa.png)

### What I've already tried to fix it:
I'm trying to specify the method on the User model, but obviously exception throws before custom method/prop will be invoked
https://github.com/Laravel-Backpack/Base/blob/master/src/helpers.php#L58

I think we should check if user name is empty and set default placeholder. Or we can check if custom method is present before make placeholder link.
### Backpack, Laravel, PHP, DB version:
"backpack/crud": "^3.6", php 7.3, mysql  5.7.25

**Comment by tabacitu** [comment]
You're right! Thank you @hey-red for reporting this. Just pushed a fix. A ```composer update``` will fix it for you.

Cheers!
