### ISSUE TITLE
[4.0][Feature][Proposal] Easily enable Vue.JS or React

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#386]
Sometimes people want to use Vue.JS or React inside their Backpack admin panels. Or other javascript libraries. This [was possible in v3 too](https://medium.com/@owenmelbourne/using-backpack-for-laravel-with-vuejs-or-even-react-b6e4ea48caf7), but in v4 we could make it even easier.

What do you think about allowing people to add stuff to an array in ```config/backpack/base.php``` when they want css/js added to all pages? We could have:

```php
    // ---------------
    // CSS & JS ASSETS
    // ---------------
    // CSS & JS files that are loaded in all pages, using Laravel's asset() helper 
    
    'styles' => [
        'packages/backpack/base/css/bundle.css', // includes jQuery, Bootstrap, CoreUI, PNotify, Popper
        'packages/@digitallyhappy/backstrap/css/overlay.css', // default design on top of CoreUI
    ],

    'scripts' => [
        'packages/backpack/base/js/bundle.js', // includes jQuery, Bootstrap, CoreUI, PNotify, Popper
        // examples
        // 'https://unpkg.com/vue@2.4.4/dist/vue.min.js',
        // 'https://unpkg.com/react@16/umd/react.production.min.js',
        // 'https://unpkg.com/react-dom@16/umd/react-dom.production.min.js',
    ],

    // ------------------
    // LARAVEL MIX ASSETS
    // ------------------
    // CSS & JS files that are loaded in all pages, using Laravel's mix() helper 

    'mix_styles' => [
        // 'css/app.css',
    ],

    'mix_scripts' => [
       //  'js/app.js',
    ],

```

We already had something similar with AdminLTE "_overlays_", allowing people to add CSS on top of AdminLTE, to customize the looks. The above would just add the possibility to do the same for JS, and optionally using Laravel Mix.

@OwenMelbz what do you think?

**Comment by tabacitu** [comment]
PR here: https://github.com/Laravel-Backpack/Base/pull/387

**Comment by OwenMelbz** [comment]
It’s an easy idea that will help people out for sure.

The tricky part to decide is the load order. Do these scripts load BEFORE or AFTER the core backpack ones?

If you load them after Backpack then people can’t modify or alter anything first. But if you load them before then people can’t use the other plugins Backpack provides.

Unless ofc all the assets in the header/footer will be loaded via these arrays to give user control of load order?

**Comment by tabacitu** [comment]
> Unless ofc all the assets in the header/footer will be loaded via these arrays to give user control of load order?

Exactly. These arrays contain ALL the assets needed by Backpack/Base. So the user can totally control the order:
- From ```config/backpack/base.php```: notice the ```bundle``` files are also inside these arrays; so people can put things before/after them; or replace the bundle files with individual files from CDN/local/etc; total freedom!
- From views: you can still put stuff in the ```before_scripts```, ```after_scripts```, ```before_styles```, ```after_styles``` blade stacks; Like Backpack/CRUD pushes assets from fields, columns, filters, etc; They'll all be pushed before/after the assets mentioned in these arrays;
- From the controller: you can do ```Config::set('backpack.base.scripts', $yourCustomArray);``` and the change will only happen for that particular controller/action; So you can like, have a ```UsesVueAdminController``` that adds Vue in the constructor;

Glad to hear you also think it's a good solution for using Vue/React to "sprinkle" interactivity on page. Let's move the conversation inside PR https://github.com/Laravel-Backpack/Base/pull/387 .

Cheers!
