### ISSUE TITLE
Allow /admin paths to certain users

### ISSUE THREAD

**Issue by mitsest** [Laravel-Backpack/Base#39]
Hey there, 
thanks for the plugin.

I 've been trying to add an extra middleware to /admin paths, in order to allow access only to users with the backpack-permissions role I have created.
So, if a logged in user does not have the 'admin' role, I want to redirect him back to the login page, when he tries to access /admin paths

Is there a nice way wo do this (e.g. extending your middleware) apart from going inside your \Middleware\Admin::handle and amending the if case like

`if (Auth::guard($guard)->guest() || (!$user->hasRole(config('backpack.base.admin_role')) && $user->id != 1) )`

(This way the first user can log in no matter what, but all the others have to have the "admin" role)

Any tips are very much welcome,
Thanks again for your work

**Comment by tabacitu** [comment]
Hi @mitsest ,

I think the sexiest way would be to create two new middleware (role and permission), [just like spatie/permissions recommends](https://github.com/spatie/laravel-permission#using-a-middleware) and use those in your routes files, basically overwriting the Backpack routes. It would look something like:
```php
Route::group(['middleware' => ['role:admin,access_backend']], function () {
    //
});
```

In order to overwrite the Backpack routes, you need to make sure in your config/app.php file that ```App\Providers\RouteServiceProvider::class,``` is after the Backpack ones.

Those two middleware will soon be included in Backpack/PermissionManager, but right now you can create them yourself. You could submit a pull request with them, if you have the time :-)

Cheers!

**Comment by tabacitu** [comment]
P.S. I myself always like to test for permissions, not roles. But if the app is not very complex, I can see why that would be overkill.

**Comment by mitsest** [comment]
Thanks for the tip + fast reply!
I 'll try it as soon as I have some time. I 'm fairly new to laravel, so forgive me if I skipped this doc part! I 'm pretty buried in documentation. :)

Cheers

**Comment by tabacitu** [comment]
No worries. The Backpack documentation isn't great either - still trying to figure out how to make it clearer and shorter.

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by sijones-uk** [comment]
I had to do the same thing, This is what I ended up with in my routes file (I'd already created a role called "Administrator"):

```
Route::group(['prefix' => config('backpack.base.route_prefix'), 'middleware' => ['web', 'role:Administrator']], function () {
    if (config('backpack.base.setup_dashboard_routes')) {
        Route::get('dashboard', '\Backpack\Base\app\Http\Controllers\AdminController@dashboard');
        Route::get('/', '\Backpack\Base\app\Http\Controllers\AdminController@redirect');
    }
});
```

**Comment by chellmann** [comment]
Just setup a new Middleware that Checks if the Request is within "admin" Route and check for Permission. Include that Middleware in the Kernel and include it in the web group.

Example for the Middleware: 
public function handle($request, Closure $next)
    {   
        if ($request->is('admin/*')) {
            if (! $request->user()->hasRole('admin')) {
                return redirect('404');
            }
        }
        return $next($request);
    }

**Comment by Whyounes** [comment]
Or you can put this in your service provider 

```php
Route::aliasMiddleware('admin', MyMiddleware::class);
```

This will override the default `admin` middleware used by Backpack
