### ISSUE TITLE
When i change the theme skin in config/backpack/base.php nothing happens

### ISSUE THREAD

**Issue by woutervanerp** [Laravel-Backpack/Base#391]
# Bug report
When i change the theme skin in config/backpack/base.php nothing happens

### What I did:
I made changes in the base.php but nothing happend

### What I've already tried to fix it:
Clear cache, npm run production

**Comment by woutervanerp** [comment]
Rookie mistake, just:

php artisan cache:clear

**Comment by tabacitu** [comment]
Glad to hear you solved it @woutervanerp . Cheers!
