### ISSUE TITLE
Small bug in the 'backpack_avatar_url' helper

### ISSUE THREAD

**Issue by TaProhm** [Laravel-Backpack/Base#393]
# Bug report

### What I did: 

Tried to use 'placehold' as 'avatar_type' in config/backpack/base.php

### What I expected to happen: 

Generic image with the first letter of the user name as a user avatar.

### What happened: 

Image always contains the default letter 'A'

### What I've already tried to fix it: 

Replaced 'property_exists' with 'getAttribute' in pull request.

### Backpack, Laravel, PHP, DB version:
Backpack Base:  1.1.5
Laravel: 5.8.31
PHP: 7.3.8

**Comment by tabacitu** [comment]
Thank you for opening this, @TaProhm ! Let's move the conversation inside the PR! 

Cheers!
