### ISSUE TITLE
Can't fake authenticated user to test routes

### ISSUE THREAD

**Issue by jjuenger** [Laravel-Backpack/Base#398]
# Bug report

### What I did:
I wrote a feature test which has to check if a job will be dispatched in a queue when I make a request to a specific route. I created an user with a factory who has the correct permissions and make the get request with "actingAs".

Code:

```
public function testRestartDevice()
    {
        Queue::fake();
        $user = factory(AdminUser::class)->create();
        Auth::login($user);

        $response = $this->actingAs($user)
            ->withSession(['_token' => $user->remember_token])
            ->get('/admin/pbx/restart/35');
        
        Queue::assertPushedOn('backpack', PbxRestart::class);
    }
```

### What I expected to happen:
I expect that a job is dispatched in my faked queue.

### What happened:
I get a response with a redirect to the login page of backpack and no job is dispatched.

### What I've already tried to fix it:
I tried different ways to create or authenticate the user. 

### Backpack, Laravel, PHP, DB version:
Backpack:
     "backpack/base": "^0.9.0",
     "backpack/crud": "^3.4.0", 

Laravel 5.5,
PHP 7.1

Would be awesome if you have a solution or test helper class.

**Comment by tabacitu** [comment]
Hi @jjuenger ,

Maybe it's because you haven't used the same guard that Backpack uses? On boot Backpack adds its own guard, ```backpack```. You could try doing:

```diff
public function testRestartDevice()
    {
        Queue::fake();
        $user = factory(AdminUser::class)->create();
-        Auth::login($user);
+        Auth::guard(config('backpack.base.guard'))->login($user);

        $response = $this->actingAs($user)
            ->withSession(['_token' => $user->remember_token])
            ->get('/admin/pbx/restart/35');
        
        Queue::assertPushedOn('backpack', PbxRestart::class);
    }
```

Other than this, I'm afraid I don't know how to help, sorry. 

Since this isn't really Backpack-related, but something custom you've built, I'm going to close this. We use Github as our to-do-list, so this doesn't fit here. If you can't figure it out, I suggest you try on StackOverflow with the ```laravel``` tag.

Cheers!

**Comment by jjuenger** [comment]
Thanks a lot! That solved the problem!
