### ISSUE TITLE
Menu system

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/base#4]
Needs to be:
- easy to define items & icons
- easy to show items only when user has permission
- easy to change programatically (if x happens change/hide menu item)
- easy to make indentation (infinite-level menu)
- easy to override/overwrite
- easy to understand
- easy to switch from vertical to horizontal menu

Bonus:
- ability to automatically add a menu item when installing a package

**Comment by tabacitu** [comment]
So far, it seems to me like the best option is to just make a view for the menu, which gets published when the package is installed.

PROs:
- easiest to understand
- easiest to customize/override/overwrite
- easiest to switch from vertical to horizontal menu (publish two files: horizontal_menu and vertical_menu and a config option that specifies which one should be visible; default: vertical)

CONs:
- will make the programmer include a little logic inside the view (if condition then show/hide)

Anyone else have any CONs? @Ghitu? @cristiantone?

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/base/commit/b9cb3c7651a09402ac6085b4d837b3aa34a86ebd

**Comment by aaranmcguire** [comment]
@tabacitu Just wondering, would you up for me looking at "ability to automatically add a menu item when installing a package". - I'm thinking I could have it register when packages/developers register the routes.

**Comment by tabacitu** [comment]
@aaranmcguire sounds good, but I'm not sure how we could even achieve this. How would you do it?

Cheers!

**Comment by aaranmcguire** [comment]
Just thinking out loud. Add something like:

```php
AdminMenu::Add('Users & Roles', function($menu){
    $menu->route('Users', 'Backpack::users') //(String for link, route name)
});
``` 
This would be added to boot/register of the package, calling it would add links/routes into an array.
and then there would be something like `AdminMenu::Render()` to render the output.

That me just spending 5 mins to think of it, I'm not 100% if this would work or how good it is.

**Comment by OwenMelbz** [comment]
Ha I thought about this as well!

But then I kept coming back to, it's not as simple or as flexible a simple editing a template :(

Maybe we need another pros/cons?
