### ISSUE TITLE
Registered event missed

### ISSUE THREAD

**Issue by sergunik** [Laravel-Backpack/Base#401]
https://github.com/Laravel-Backpack/Base/blob/8f92b8ec6ab9830b155ce4835908723f83c61cdd/src/app/Http/Controllers/Auth/RegisterController.php#L106

Folk, why did you remove `Registered` event?
You overwrote \Illuminate\Foundation\Auth\RegistersUsers::register() method without event `Registered`. And now I couldn't listen it and trigger my own functionality right after registration new user.

Is it possible to add it?

**Comment by tabacitu** [comment]
Hi @sergunik ,

Hmm... the Register event must have not existed when we overwrote that method. Sure, I've just pushed a fix registering that event. Run ```composer update``` and make sure you're running Base 1.1.8 or later.

Cheers!
