### ISSUE TITLE
Can not intall backpack base 

### ISSUE THREAD

**Issue by gumpon** [Laravel-Backpack/Base#404]
# Bug report

### What happened:
D:\WWW\danwebsite>composer require backpack/base
Using version ^1.1 for backpack/base
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package:  [32mbackpack/base [39m
Discovered Package:  [32mbackpack/crud [39m
Discovered Package:  [32mbackpack/generators [39m
Discovered Package:  [32mbeyondcode/laravel-dump-server [39m
Discovered Package:  [32mcreativeorange/gravatar [39m
Discovered Package:  [32mfideloper/proxy [39m
Discovered Package:  [32mintervention/image [39m
Discovered Package:  [32mlaracasts/generators [39m
Discovered Package:  [32mlaravel/tinker [39m
Discovered Package:  [32mnesbot/carbon [39m
Discovered Package:  [32mnunomaduro/collision [39m
Discovered Package:  [32mprologue/alerts [39m
 [32mPackage manifest generated successfully. [39m

D:\WWW\danwebsite>php artisan backpack:base:install
 0/8 [>---------------------------]   0% Backpack\Base installation started. Please wait...

 1/8 [===>------------------------]  12% Installing backpack/generators

 2/8 [=======>--------------------]  25% Installing laracasts/generators

 3/8 [==========>-----------------]  37% Publishing configs, langs, views and AdminLTE files

   Symfony\Component\Process\Exception\ProcessFailedException  : The command "php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider" --tag=minimum" failed.

Exit Code: 255(Unknown error)

Working directory: D:\WWW\danwebsite

Output:
================
Copied Directory [\vendor\backpack\base\src\config] To [\config]
Copied Directory [\vendor\backpack\base\src\resources\error_views] To [\resources\views\errors]
Copied Directory [\vendor\backpack\base\src\public] To [\public\vendor\backpack]

   Symfony\Component\Debug\Exception\FatalErrorException  : Allowed memory size of 134217728 bytes exhausted (tried to allocate 80011696 bytes)

  at D:\WWW\danwebsite\vendor\league\flysystem\src\Adapter\Local.php:135
    131|     {
    132|         $location = $this->applyPathPrefix($path);
    133|         $this->ensureDirectory(dirname($location));
    134|
  > 135|         if (($size = file_put_contents($location, $contents, $this->writeFlags)) === false) {
    136|             return false;
    137|         }
    138|
    139|         $type = 'file';

  Exception trace:

  1   file_put_contents()
      D:\WWW\danwebsite\vendor\league\flysystem\src\Adapter\Local.php:135

  2   League\Flysystem\Adapter\Local::write()
      D:\WWW\danwebsite\vendor\league\flysystem\src\Filesystem.php:102

  Please use the argument -v to see more details.

   Whoops\Exception\ErrorException  : Allowed memory size of 134217728 bytes exhausted (tried to allocate 80011696 bytes)

  at D:\WWW\danwebsite\vendor\league\flysystem\src\Adapter\Local.php:135
    131|     {
    132|         $location = $this->applyPathPrefix($path);
    133|         $this->ensureDirectory(dirname($location));
    134|
  > 135|         if (($size = file_put_contents($location, $contents, $this->writeFlags)) === false) {
    136|             return false;
    137|         }
    138|
    139|         $type = 'file';

  Exception trace:

  1   Illuminate\Foundation\Console\VendorPublishCommand::handle()
      D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  2   call_user_func_array:{D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32}()
      D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  Please use the argument -v to see more details.

Error Output:
================
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 80011696 bytes) in D:\WWW\danwebsite\vendor\league\flysystem\src\Adapter\Local.php on line 135
PHP Stack trace:
PHP   1. {main}() D:\WWW\danwebsite\artisan:0
PHP   2. App\Console\Kernel->handle() D:\WWW\danwebsite\artisan:37
PHP   3. Illuminate\Console\Application->run() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:133
PHP   4. Illuminate\Console\Application->run() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Console\Application.php:90
PHP   5. Illuminate\Console\Application->doRun() D:\WWW\danwebsite\vendor\symfony\console\Application.php:148
PHP   6. Illuminate\Console\Application->doRunCommand() D:\WWW\danwebsite\vendor\symfony\console\Application.php:272
PHP   7. Illuminate\Foundation\Console\VendorPublishCommand->run() D:\WWW\danwebsite\vendor\symfony\console\Application.php:915
PHP   8. Illuminate\Foundation\Console\VendorPublishCommand->run() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Console\Command.php:170
PHP   9. Illuminate\Foundation\Console\VendorPublishCommand->execute() D:\WWW\danwebsite\vendor\symfony\console\Command\Command.php:255
PHP  10. Illuminate\Foundation\Application->call() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Console\Command.php:183
PHP  11. Illuminate\Container\BoundMethod::call() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Container\Container.php:576
PHP  12. Illuminate\Container\BoundMethod::callBoundMethod() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:34
PHP  13. Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:90
PHP  14. call_user_func_array:{D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32}() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32
PHP  15. Illuminate\Foundation\Console\VendorPublishCommand->handle() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32
PHP  16. Illuminate\Foundation\Console\VendorPublishCommand->publishTag() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Foundation\Console\VendorPublishCommand.php:76
PHP  17. Illuminate\Foundation\Console\VendorPublishCommand->publishItem() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Foundation\Console\VendorPublishCommand.php:161
PHP  18. Illuminate\Foundation\Console\VendorPublishCommand->publishDirectory() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Foundation\Console\VendorPublishCommand.php:190
PHP  19. Illuminate\Foundation\Console\VendorPublishCommand->moveManagedFiles() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Foundation\Console\VendorPublishCommand.php:225
PHP  20. League\Flysystem\MountManager->put() D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Foundation\Console\VendorPublishCommand.php:241
PHP  21. League\Flysystem\Filesystem->put() D:\WWW\danwebsite\vendor\league\flysystem\src\MountManager.php:595
PHP  22. League\Flysystem\Adapter\Local->write() D:\WWW\danwebsite\vendor\league\flysystem\src\Filesystem.php:102
PHP  23. file_put_contents() D:\WWW\danwebsite\vendor\league\flysystem\src\Adapter\Local.php:135

  at D:\WWW\danwebsite\vendor\backpack\base\src\app\Console\Commands\Install.php:100
     96|         });
     97|
     98|         // executes after the command finishes
     99|         if (!$process->isSuccessful()) {
  > 100|             throw new ProcessFailedException($process);
    101|         }
    102|
    103|         if ($this->progressBar) {
    104|             $this->progressBar->advance();

  Exception trace:

  1   Backpack\Base\app\Console\Commands\Install::executeProcess("php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider" --tag=minimum")
      D:\WWW\danwebsite\vendor\backpack\base\src\app\Console\Commands\Install.php:58

  2   Backpack\Base\app\Console\Commands\Install::handle()
      D:\WWW\danwebsite\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  Please use the argument -v to see more details.

### Backpack, Laravel, PHP, DB version:
Laravel 5.8
PHP 7.1.8
MySQL Server version: 5.7.23

**Comment by tabacitu** [comment]
Hi @gumpon ,

It looks like the files don't get published. Can you run ```php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider" --tag=minimum``` manually to see if it works like that? 

If you can't get the automatic installation to work, try the [manual installation process](https://backpackforlaravel.com/docs/3.6/base-how-to#manually-install-backpack-base).

Cheers!

**Comment by tabacitu** [comment]
Done! You should be able to install Backpack v4 on Laravel 6 now. I don't recommend doing this for live projects just yet - there are two more breaking changes we need to do before it's stable:
- [merge Base and CRUD](https://github.com/Laravel-Backpack/CRUD/issues/1960)
- [rewrite all the fields to be able to load them with javascript](https://github.com/Laravel-Backpack/CRUD/pull/1890)

**Comment by gumpon** [comment]
Thankyou for your support.
