### ISSUE TITLE
Cannot redeclare maximumServerUploadSizeInBytes() 

### ISSUE THREAD

**Issue by sklazer** [Laravel-Backpack/Base#409]
# Bug report

### What I did:
Added two or more "image" fields 

### What I expected to happen:
Proper page render

### What happened:
Cannot redeclare maximumServerUploadSizeInBytes() (previously declared in ....

### Backpack, Laravel, PHP, DB version:
Backpack 4, Laravel 6.0.3

**Comment by tabacitu** [comment]
Thank you @sklazer . 

It's been fixed in 4.0.2 - please run a ```composer update```, it should fix it for you. Please note issues like this should be reported in the CRUD repository - Base was used in v3, but is no longer used in v4.

Cheers!

**Comment by tabacitu** [comment]
Duplicate of: https://github.com/Laravel-Backpack/CRUD/issues/2086
