### ISSUE TITLE
Problem while upgrading from 3.6 to 4.0

### ISSUE THREAD

**Issue by jfelixoptimiumnc** [Laravel-Backpack/Base#410]
Hi all,

Got a problem while upgrading from 3.6 to 4.0:

composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for laravel/framework ^6.0 -> satisfiable by laravel/framework[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
- Installation request for backpack/langfilemanager ^1.0 -> satisfiable by backpack/langfilemanager[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 1.0.19, 1.0.2, 1.0.20, 1.0.21, 1.0.22, 1.0.23, 1.0.24, 1.0.25, 1.0.26, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.x-dev].
- Can only install one of: backpack/crud[4.0.0, 3.6.x-dev].
- Can only install one of: backpack/crud[4.0.1, 3.6.x-dev].
- Can only install one of: backpack/crud[4.0.2, 3.6.x-dev].
- Can only install one of: backpack/crud[4.0.3, 3.6.x-dev].
- Can only install one of: backpack/crud[4.0.5, 3.6.x-dev].
- Can only install one of: backpack/crud[4.0.x-dev, 3.6.x-dev].
- Can only install one of: backpack/crud[v4.x-dev, 3.6.x-dev].
- Conclusion: install backpack/crud 3.6.x-dev
- Installation request for backpack/crud ^4.0.0 -> satisfiable by backpack/crud[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.5, 4.0.x-dev, v4.x-dev].

Any help?

Regards

**Comment by tabacitu** [comment]
Hmm... it looks like LangFileManager did not support v4 at the time - we might have forgotten about it. It's a package we rarely use or update. I've just added support now.

Transferred issue to LangFileManager: https://github.com/Laravel-Backpack/LangFileManager/issues/72
