### ISSUE TITLE
[4.0][bug] Sidebar menu is not expanding correctly

### ISSUE THREAD

**Issue by tomsb** [Laravel-Backpack/Base#414]
# Bug report

### What I did:
Install PermissionManager, add sidebar menus.
Open user edit form

### What I expected to happen:
Sidebar menu should expand with "Users" menu item selected.

### What happened:
Menu stays in default state

### What I've already tried to fix it:
Pull Request: https://github.com/Laravel-Backpack/Base/pull/415

**Comment by tabacitu** [comment]
Closing this in favour of the PR.
