### ISSUE TITLE
Jquery is not loaded

### ISSUE THREAD

**Issue by NicolasDepoilly** [Laravel-Backpack/Base#419]
# Bug report
https://stackoverflow.com/questions/58825461/laravel-6-backpack-is-not-finding-jquery
### What I did:
I installed laravel, backpack through composer and npm up after it
in my

config/backpack/base.php

I have this mentionned :

// -------
// SCRIPTS
// -------

// JS files that are loaded in all pages, using Laravel's asset() helper
'scripts' => [
    // Backstrap includes jQuery, Bootstrap, CoreUI, PNotify, Popper
    'packages/backpack/base/js/bundle.js',

    // examples (everything inside the bundle, loaded from CDN)
     'https://code.jquery.com/jquery-3.4.1.min.js',
    // 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js',
     'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js',
    // 'https://unpkg.com/@coreui/coreui/dist/js/coreui.min.js',
    // 'https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js',
    // 'https://unpkg.com/sweetalert/dist/sweetalert.min.js',
    // 'https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js'

    // examples (VueJS or React)
    // 'https://unpkg.com/vue@2.4.4/dist/vue.min.js',
    // 'https://unpkg.com/react@16/umd/react.production.min.js',
    // 'https://unpkg.com/react-dom@16/umd/react-dom.production.min.js',
],

### What I expected to happen:
Having JQuery
### What I've already tried to fix it:

in my

> config/backpack/base.php

I have this mentionned :

```
// -------
// SCRIPTS
// -------

// JS files that are loaded in all pages, using Laravel's asset() helper
'scripts' => [
    // Backstrap includes jQuery, Bootstrap, CoreUI, PNotify, Popper
    'packages/backpack/base/js/bundle.js',

    // examples (everything inside the bundle, loaded from CDN)
     'https://code.jquery.com/jquery-3.4.1.min.js',
    // 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js',
     'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js',
    // 'https://unpkg.com/@coreui/coreui/dist/js/coreui.min.js',
    // 'https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js',
    // 'https://unpkg.com/sweetalert/dist/sweetalert.min.js',
    // 'https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js'

    // examples (VueJS or React)
    // 'https://unpkg.com/vue@2.4.4/dist/vue.min.js',
    // 'https://unpkg.com/react@16/umd/react.production.min.js',
    // 'https://unpkg.com/react-dom@16/umd/react-dom.production.min.js',
],
```
But in fact when I open my login page and log to my server, I have this error

Uncaught ReferenceError: jQuery is not defined
### Backpack, Laravel, PHP, DB version:

```
 php artisan backpack:version
### PHP VERSION:
PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

### LARAVEL VERSION:
laravel/framework                     v6.5.1     The Laravel Framework.

### BACKPACK VERSION:
backpack/base                         1.1.13     Laravel Backpack's base ...
backpack/crud                         4.0.14     Quickly build an admin i...
backpack/generators                   1.2.7      Generate files for larav...
backpack/langfilemanager              2.0.1      An interface to edit lan...
backpack/permissionmanager            5.0.2      Users and permissions ma...
```

**Comment by tabacitu** [comment]
Hi @NicolasDepoilly ,

That's very weird. jQuery should indeed be loaded on all Backpack pages. And my tests show that it is:
![Screenshot 2019-11-15 at 10 12 32](https://user-images.githubusercontent.com/1032474/68927518-9bdf2900-0790-11ea-9a36-ce775e597a2f.png)

The problem for you must be that you have BOTH Backpack\Base and Backpack\CRUD installed. So both packages compete to show you their views. I suspect you're now seeing the views from Backpack\Base, which is an OLD package (only used in Backpack 3 and below), while you're using Backpack\CRUD v4. **Please remove your ```backpack\base``` dependency from your ```composer.json``` .** That should fix it for you. 

Starting with Backpack v4, Backpack\Base is no longer a requirement. Everything inside it has been moved to the Backpack\CRUD repository.

I've seen people run into this problem before a few times but never got to the bottom of it - **how did you end up having ```backpack/base``` in your composer.json? Is this for an older project (2017-2018)?** We might have had instructions to require it at one point, but as far as I know they were removed, in favour of CRUD requiring a particular version of Base. (Again, this is no longer a thing. Backpack\CRUD is now stand-alone). 

Thanks! Cheers! Let me know if this didn't fix it for you, we'll reopen the issue. But I think it will.

**Comment by NicolasDepoilly** [comment]
It is a bit strange because I removed it and it was successful in my composer.json : 

> 
>     "require": {
>         "php": "^7.2",
>         "ext-curl": "*",
>         "ext-gd": "*",
>         "ext-imap": "*",
>         "ext-json": "*",
>         "ext-libXML": "*",
>         "ext-pdo": "*",
>         "ext-simpleXML": "*",
>         "ext-soap": "*",
>         "ext-zip": "*",
>         "backpack/crud": "4.0.*",
>         "backpack/langfilemanager": "^2.0",
>         "backpack/permissionmanager": "^5.0",
>         "barryvdh/laravel-elfinder": "^0.4.3",
>         "dingo/api": "*",
>         "fideloper/proxy": "^4.0",
>         "laravel/framework": "^6.2",
>         "laravel/socialite": "^4.2",
>         "laravel/tinker": "^1.0",
>         "rap2hpoutre/laravel-log-viewer": "*",
>         "s-ichikawa/laravel-sendgrid-driver": "*",
>         "spatie/laravel-permission": "*"
>     },
>     "require-dev": {
>         "backpack/generators": "1.2.*",
>         "facade/ignition": "^1.4",
>         "fzaninotto/faker": "^1.4",
>         "krlove/eloquent-model-generator": "^1.3",
>         "laracasts/generators": "^1.1",
>         "mockery/mockery": "^1.0",
>         "nunomaduro/collision": "^3.0",
>         "phpunit/phpunit": "^8.0"
>     },

Here is my log of terminal, I don't know what I did badly, but backpack/base is still a package discovered in my list.


XXX@XXX-UX530UX:/var/www/XXX$ composer remove backpack/base
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: backpack/base
Discovered Package: backpack/crud
Discovered Package: backpack/generators
Discovered Package: backpack/langfilemanager
Discovered Package: backpack/permissionmanager
Discovered Package: barryvdh/laravel-elfinder
Discovered Package: creativeorange/gravatar
Discovered Package: dingo/api
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: krlove/eloquent-model-generator
Discovered Package: laracasts/generators
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: prologue/alerts
Discovered Package: rap2hpoutre/laravel-log-viewer
Discovered Package: s-ichikawa/laravel-sendgrid-driver
Discovered Package: spatie/laravel-permission
Package manifest generated successfully.
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
XXX@XXX-UX530UX:/var/www/XXX$ php artisan cache:clear
Application cache cleared!
XXX@XXX-UX530UX:/var/www/XXX$ php artisan view:clear
Compiled views cleared!
XXX@XXX-UX530UX:/var/www/XXX$ php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
XXX@XXX-UX530UX:/var/www/XXX$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: backpack/base
Discovered Package: backpack/crud
Discovered Package: backpack/generators
Discovered Package: backpack/langfilemanager
Discovered Package: backpack/permissionmanager
Discovered Package: barryvdh/laravel-elfinder
Discovered Package: creativeorange/gravatar
Discovered Package: dingo/api
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: krlove/eloquent-model-generator
Discovered Package: laracasts/generators
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: prologue/alerts
Discovered Package: rap2hpoutre/laravel-log-viewer
Discovered Package: s-ichikawa/laravel-sendgrid-driver
Discovered Package: spatie/laravel-permission
Package manifest generated successfully.
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
XXX@XXX-UX530UX:/var/www/XXX$ composer dump-autoload
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: backpack/base
Discovered Package: backpack/crud
Discovered Package: backpack/generators
Discovered Package: backpack/langfilemanager
Discovered Package: backpack/permissionmanager
Discovered Package: barryvdh/laravel-elfinder
Discovered Package: creativeorange/gravatar
Discovered Package: dingo/api
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: krlove/eloquent-model-generator
Discovered Package: laracasts/generators
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: prologue/alerts
Discovered Package: rap2hpoutre/laravel-log-viewer
Discovered Package: s-ichikawa/laravel-sendgrid-driver
Discovered Package: spatie/laravel-permission
Package manifest generated successfully.

Just for you to understand, I dumbly thought that "backpack/base" was a requirement of backpack/crud as for me a base is supposed to be here. So I installed it intentionally but it seems that it was a bad idea!

If I have few time, I will reinstall my project in parallel without this require in my composer to check if it runs well, but if you have an idea it would be cool to help me.
We keep both in touch!

Thanks for the answer, I hope we will solve this and I wish you a nice week end.

**Comment by tabacitu** [comment]
@NicolasDepoilly - I think I've got it. I see your composer.json also requires ```"backpack/generators": "1.2.*",```, which is the one used in Backpack 3, and requires Backpack\Base. Change it to ```^2.0``` - I bet then Backpack/Base will not longer be installed.

Cheers!

**Comment by NicolasDepoilly** [comment]
Well done, now you can officially close this topic, it works perfectly.
Thanks for your help and keep doing this wonderful project!
Cheers
Nicolas
