### ISSUE TITLE
Customise Registration Form

### ISSUE THREAD

**Issue by b8ne** [Laravel-Backpack/Base#42]
Hi,
Just wondering what the best way to customise the auth templates would be?
I have added extra fields to my user model, so need them completed on registration - even for admin, so need to add these fields to the view and also Controller.
However because all of these live in /vendor/backpack etc they are outside of the regular version control.
Is there a standard way to handle this type of thing?
Cheers

**Comment by tabacitu** [comment]
Hi @b8ne ,

If you've done [step 3 in the installation process](https://github.com/Laravel-Backpack/Base#install-on-laravel-53) you should also have all Backpack\Base views published in your ```resources/views/vendor/backpack/base```. That's so you can customize them - exactly your use case.

Cheers!

**Comment by b8ne** [comment]
Hi @tabacitu ,
Thanks for the reply. Yep so that sorts views, what about Auth Controllers though?
My /app/Http/Controllers/Auth controllers still resemble the stock laravel controllers, and customising them has no influence on backpack auth, which is suggesting to me that backpack is still referencing the /vendor controllers.
Just FYI - If its the case that backpack is supposed to move its controllers into this folder, on initial setup i did run the stock laravel auth init commands, so perhaps this conflicted with backpack setup?

**Comment by tabacitu** [comment]
Oh, I understand. The AuthController is not published by default. You can extend/overwrite the AuthController by following the [steps here](https://github.com/Laravel-Backpack/Base/issues/25#issuecomment-238011374).

Backpack uses its own files, it won't conflict with the stock Laravel AuthController - that's in case you need separate logins for you users and your admins.

Backpack's AuthController loads views by looking inside ```resources/views/backpack/base```. If it finds the views there, it loads them. If not, it loads the ones from the package.

Cheers!

**Comment by b8ne** [comment]
Awesome, implemented and tested... All works fine.
Thanks for your help @tabacitu

**Comment by b8ne** [comment]
Hey @tabacitu just an FYI, setting 'setup_auth_routes' to false disabled the logout functionality.  I set it to true, and then tinkered with a few of the redirect routes to go to /admin or /admin/dashboard instead of /home, and all is working as expected now.

**Comment by tabacitu** [comment]
Hmm... I think the problem might actually be bad documentation :-) Yes, starting with Laravel 5.3, ```Route::auth()``` only includes a POST route for logout, no GET, which is... unfortunate. 

Maybe the documentation should say something like this:

_After setting ```setup_auth_routes``` to false you should register those routes yourself in your ```web.php``` file, making sure you have all routes you just disabled. Take a look at [the routes registered in BaseServiceProvider](https://github.com/Laravel-Backpack/Base/blob/master/src/BaseServiceProvider.php#L70-L84) to make sure you have all routes you need._

That would be better, right?
