### ISSUE TITLE
[3.6] Active and Inactive Users

### ISSUE THREAD

**Issue by ldelosreyes** [Laravel-Backpack/Base#424]
Hi,
I'm pretty newbie in this laravel backpack.
I still want to use backpack auth however, I also wanted to restrict inactive users to login.
I have a is_active column in my users table.
Please guide me on how to do this.
Thank you.
Cheers,
Leo

**Comment by tabacitu** [comment]
Sure. Backpack distinguished between admins and non-admins using a middleware that got published upon installation into ```app\Http\Middleware\CheckIfAdmin.php```. Change your ```checkIfUserIsAdmin()``` method there to change what you call an "admin". 

For you, it should be as easy as:

```php
    private function checkIfUserIsAdmin($user)
    {
        return ($user->is_active == 1);
    }
```

Hope it helps.
Cheers!

**Comment by ldelosreyes** [comment]
Hi @tabacitu ,

Tried your solution but it did not work as I expected.

Inactive user still able to logged-in with limited access.

What I want is to restrict inactive user to login.

Hope this make sense.

Cheers,

Leo

**Comment by pxpm** [comment]
@ldelosreyes You have to override the login function to accomodate what you want. In the login function check if user is inactive and don't let the login process continue.

**Comment by ldelosreyes** [comment]
Hi @pxpm,

I'm trying to do that in LoginController.

However, it looks like it is not using that file.

I'm using backpack routes and I still want to use it.

Is is still possible to override the login function by that?
