### ISSUE TITLE
[3.6] Override Backpack Auth LoginController

### ISSUE THREAD

**Issue by ldelosreyes** [Laravel-Backpack/Base#426]
Hi,
I'm pretty newbie in this laravel backpack.
I want to override backpack auth login controller to restrict inactive users to login.
Is this possible?
Please guide me on how to do this.
Thank you.
Cheers,
Leo

**Comment by tabacitu** [comment]
@ldelosreyes I think you're better off changing the ```app/Http/Middleware/CheckIfAdmin``` middleware - there's a method there:

```php

    /**
     * Checked that the logged in user is an administrator.
     *
     * --------------
     * VERY IMPORTANT
     * --------------
     * If you have both regular users and admins inside the same table,
     * change the contents of this method to check that the logged in user
     * is an admin, and not a regular user.
     *
     * @param [type] $user [description]
     *
     * @return bool [description]
     */
    private function checkIfUserIsAdmin($user)
    {
        // return ($user->is_active == 1);
        return true;
    }
```

You can check that the user is activate there, the file is already in your project,  no need to overwrite anything.

**Comment by ldelosreyes** [comment]
Hi @tabacitu,

I already tried that but the problem is the user still can login. The session was still created.

I wanted to restrict an inactive user from logging in. I think editing the middleware will just restrict the user in accessing specific pages but it will still let it to login.

I hope it make sense.

Thanks,

Leo

**Comment by pxpm** [comment]
@ldelosreyes Indeed, for what you want you should overwrite the login controller. 

You need to: 
- Create a new controller that extends the backpack auth controller. (or a new controller with same functions)
- Overwrite the login function with your custom code.
- Point the auth routes to your new controller instead of the default.

That way it will allow you to do just that. 

Here is an example of login function with custom code:

```php
public function login(Request $request)
    {
        $this->validateLogin($request);

        // If the class is using the ThrottlesLogins trait, we can automatically throttle
        // the login attempts for this application. We'll key this by the username and
        // the IP address of the client making these requests into this application.
        if ($this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }
        $user = User::where('email',$request->email)->first();
        if(!is_null($user)) {
        if (!$user->can_login) {
            $this->incrementLoginAttempts($request);
            return $this->sendFailedLoginResponse($request);
        }
    }
        if ($this->attemptLogin($request)) {
            return $this->sendLoginResponse($request);
        }

        // If the login attempt was unsuccessful we will increment the number of attempts
        // to login and redirect the user back to the login form. Of course, when this
        // user surpasses their maximum number of attempts they will get locked out.
        $this->incrementLoginAttempts($request);

        return $this->sendFailedLoginResponse($request);
    }
```

Best, 

Pedro
