### ISSUE TITLE
Laravel Reset Password This site can’t be reached / Page Not Found

### ISSUE THREAD

**Issue by bilalhussain77** [Laravel-Backpack/Base#433]
Laravel Error iwant to reset my pasword iam using mailcatcher when i recieve here in mailcatcher the reset link when i click the link it generate in error...
my .env 
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:GFjNDhW8iNDhbVCpnefF4qu8GMg8hZFq5dCLqRl7FIk=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://127.0.0.1:80

<img width="353" alt="Annotation 2020-07-18 151759" src="https://user-images.githubusercontent.com/67407642/87850482-f7f2e200-c909-11ea-936d-bcbbdaa7c27e.png">
<img width="478" alt="Annotation 2020-07-18 151828" src="https://user-images.githubusercontent.com/67407642/87850484-f9240f00-c909-11ea-9ce9-c964a9b4c8d8.png">

version:

**Comment by tabacitu** [comment]
You problem is probably with you `APP_URL` - I see no domain is there. Sorry @bilalhussain77 but I'm going to close this since I tested it and it worked fine on a regular localhost setup.

Cheers!
