### ISSUE TITLE
Noto font?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#47]
Google's noto font should support all language. We should check if using it looks good. If so, we could switch in order to support admin panels translatable to all languages.

https://www.google.com/get/noto

**Comment by tabacitu** [comment]
*languages

**Comment by OwenMelbz** [comment]
We've been looking at this at work, and it does seem a good idea, I don't see why not! 

However.... you still have to manage which don't file to include, like they have an African version, Arabic version, etc. but it's not 1 file suites all unless you make like a 500mb bundle

So i don't see it solving any problems, apart from if you wanted a consistent typeface across languages (even though the user still has to handle this theirself)

**Comment by tabacitu** [comment]
Right. So by default it would include the basic version with latin-ext probably, to cover something like 90% of the usage. But people could change that into arabic if they want to and it would still look good. I think that's a useful feature.

Here are a few screenshots, comparing Noto Sans (left) to Open Sans (right). I don't see much of a difference. Which is both good and bad. I think Noto is a little bit more readable, but that might be just because of the slightly bigger font size. And it's a little bit dull, it doesn't really have a personality, I think. 

![screen shot 2016-10-11 at 15 39 32](https://cloud.githubusercontent.com/assets/1032474/19271025/880107a4-8fcb-11e6-9ddf-f49c1376e216.png)
![screen shot 2016-10-11 at 15 40 33](https://cloud.githubusercontent.com/assets/1032474/19271022/87fbd81a-8fcb-11e6-9296-197f12bc2638.png)
![screen shot 2016-10-11 at 15 42 53](https://cloud.githubusercontent.com/assets/1032474/19271023/87fe159e-8fcb-11e6-9021-ff8125042218.png)
![screen shot 2016-10-11 at 15 38 33](https://cloud.githubusercontent.com/assets/1032474/19271024/87fe9816-8fcb-11e6-8526-ceea0fb41a36.png)

So... I don't know. I don't think it's a priority, but it could be a nice feature. This got me thinking though - **just raising the default font-size on the template _could_ be a major UI improvement**. The font is pretty small, now that I think about it. Buuut... Changing the font to Noto OR changing the default font-size does mean that you have to go through all AdminLTE features and make sure they all still look good.

Maybe we should submit this Noto idea to AdminLTE - if the creator agrees we could submit a PR there and help that project out too.

Otherwise... I'd say let's table this and focus on the remaining core features.

**Comment by OwenMelbz** [comment]
@tabacitu I'm not gonna lie here. But personally I prefer Open Sans xD It has more of a twist to it, and Noto is as you say a bit dull. Yes highly readable, and if you need consistent branding across platforms/languages etc then it's a great idea, but my gut feeling is maybe not for this, unless as you say the AdminLTE team use it.

I recon it is worth dropping them a message suggesting it, and if they like it, then we can use it, however park the idea until maybe v4 as some people using Open Sans might be invested in it and using custom stuff that uses it?

**Comment by tabacitu** [comment]
Yeah, you're totally right. Screw it, let's close this issue and be done with it :-)
