### ISSUE TITLE
Model with thousands of records crashes application?

### ISSUE THREAD

**Issue by gavinhewitt** [Laravel-Backpack/Base#48]
First of all: thanks for this great package! Saves a lot of work :)

So, I have a 'words' model (for a dictionary) that has thousands of results. When trying to access the list page it tries to load, but fails eventually. A quick glance in the Read trait reveals 
```
/**
     * Get all entries from the database.
     *
     * @return [Collection of your model]
     */
    public function getEntries()
    {
        $entries = $this->query->get();

        // add the fake columns for each entry
        foreach ($entries as $key => $entry) {
            $entry->addFakes($this->getFakeColumnsAsArray());
        }

        return $entries;
    }
```
The query gets every record. Instead I was expecting some kind of paginated result set. Am I missing some setting somewhere? I see this:
`$this->crud->setDefaultPageLength(10);` but that doesn't have any effect.

Thanks!

**Comment by gavinhewitt** [comment]
Ah, I think I understand. When I delete most of the records and keep a small set (300 or so) then it works as expected. It looks to be a jquery plugin that handles the pagination. This however is very inconvenient with large result sets. 

Would it be possible to change/make optional to either use a plugin or use the Laravel default pagination?

**Comment by tabacitu** [comment]
Hi @gavinhewitt ,

By default Backpack\CRUD uses standard datatables (loads all entries, then paginates). It sounds to me like you'd benefit from getting the records using AJAX. You can use:
```php
$this->crud->enableAjaxTable(); 
```
for that. Please note [the drawbacks](https://laravel-backpack.readme.io/docs/crud-full-api) though:
```php
// ------ AJAX TABLE VIEW
// Please note the drawbacks of this though: 
// - 1-n and n-n columns are not searchable
// - date and datetime columns won't be sortable anymore
$this->crud->enableAjaxTable(); 
```

I'm afraid the documentation isn't quite up to standard for this feature right now. Sorry for that.

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by imannms** [comment]
this is help me after searching a days in pain..
I didn't know **$this->crud->setDefaultPageLength(10);** require **$this->crud->enableAjaxTable();**  to work.
It should added to documentation.
