### ISSUE TITLE
Bulk deletion of records in list view [enhancement]

### ISSUE THREAD

**Issue by gavinhewitt** [Laravel-Backpack/Base#49]
Personally I would find it very convenient to have checkboxes in front of all the rows and a the option to 'delete selected'. Also a 'check all' toggle would be nice.

**Comment by tabacitu** [comment]
Hi @gavinhewitt ,

Yup, it's on the roadmap, but not in the current sprint. I think we'll have it in a few months though.

There's already [an issue about it in the Backpack\CRUD repsitory](https://github.com/Laravel-Backpack/CRUD/issues/37) so I'm going to close this one.

Cheers!
