### ISSUE TITLE
Show relations on model edit page

### ISSUE THREAD

**Issue by gavinhewitt** [Laravel-Backpack/Base#50]
I'm working on a dictionary. Since each word can have different meanings I have a **Definition** model and a `hasMany` relation called `definitions()` in the **Word** model. I would like to see the list of definitions on the same page as where I edit the word. Ideally it's possible to edit the relation directly from there.

Would this be possible? I see there's an addField that can load a view, but I'm not sure how to retrieve the relations when retrieving the word. 

Help appreciated!

**Comment by gavinhewitt** [comment]
Ok, managed to get the list of definitions on the edit page by creating a custom field. The related model is automatically appended to the field array, not sure why but it seems to work.

**Comment by tabacitu** [comment]
Hi @gavinhewitt ,

Glad you figured it out. Let's document your process for others finding this thread: you've created [a custom field type](https://laravel-backpack.readme.io/v3.0/docs/crud-fields#section-custom-field-types), probably using [the select field](https://laravel-backpack.readme.io/v3.0/docs/crud-fields#select-1-n-relationship) as inspiration. Right?

Cheers!

**Comment by gavinhewitt** [comment]
Yes, that's exactly how I did it :)
