### ISSUE TITLE
Integration in SPARK

### ISSUE THREAD

**Issue by emperorjm** [Laravel-Backpack/Base#51]
Would it be easy to integrate this solution into SPARK? I want to know if I can utilize the other modules as well without having to install this base module.

**Comment by tabacitu** [comment]
Hi @emperorjm ,

I haven't tried Spark since beta, but I see no reason why Backpack would conflict with it. Go ahead and tell us how it goes. You do have to install Base, though. It provides the visual interface for the admin panel, as well as the CRUD package and all extensions. You can skip any steps in the installation process that you don't want, though.

Cheers!

**Comment by emperorjm** [comment]
Thanks for the reply. I got things working. Just go through the normal installation steps for backpack after installing Spark. I tried my best to document what I did to get this working in the following document. Hope it helps someone: https://docs.google.com/document/d/1Pig6L6v0DdVqeHMvGvdU5cKDlapunIJiWoRytj8dNBY/edit?usp=sharing

**Comment by tabacitu** [comment]
That's great! I'm currently building an "Articles" section on the Backpack website (sort of like a blog, but with useful stuff - tutorials, snippets, etc). I intend that we document what special things we build/do with Backpack and others might find useful.

Would you be interested in turning this googledoc into a text tutorial, "How to install Backpack on Laravel Spark"? That way:
- you and your website would get some SEO and publicity boost;
- you would help out anyone googling that;
- you yourself would find that easily anytime you need to do it;

I think it's a win-win. Should I contact you when the "Articles" section is up, so we can coordinate on putting it online?

Thanks, cheers!

**Comment by emperorjm** [comment]
@tabacitu I have no problem with you copying the contents of the document to create an official How To. If you need my help to add additional info to the document you can ask. I give you permission to copy the contents of the document. I just wanted to help the community in some way because I have to seek help from the community constantly as well.

**Comment by tabacitu** [comment]
@emperorjm that's perfect, thanks. Cheers!

**Comment by lmatab** [comment]
@emperorjm What a perfect mix!, Spark and Backpack!, amazing. Since  you are working with this mix have you had any problem with  both packages?

**Comment by emperorjm** [comment]
@Imatab Only issue I have had is with the latest update of laravel and spark in that the "After Saving" option at the end of the add new form doesn't work. Haven't had the time to check it out. Everything else seems to work fine.

**Comment by smetanvir** [comment]
> Thanks for the reply. I got things working. Just go through the normal installation steps for backpack after installing Spark. I tried my best to document what I did to get this working in the following document. Hope it helps someone: https://docs.google.com/document/d/1Pig6L6v0DdVqeHMvGvdU5cKDlapunIJiWoRytj8dNBY/edit?usp=sharing

I have requested an access to this Doc... kindly accept it.

**Comment by emperorjm** [comment]
You are now able to access the document. I am not sure it still applies to the latest version of Spark.

**Comment by smetanvir** [comment]
> You are now able to access the document. I am not sure it still applies to the latest version of Spark.

Thanks man.... (Y) it's really a great help...

**Comment by adoptavia** [comment]
Hi All,
Is there an updated version of this doc anywhere with latest spark/laravel?
