### ISSUE TITLE
CRUD setColumns custom array

### ISSUE THREAD

**Issue by hewok** [Laravel-Backpack/Base#57]
Hi, I'm new in Laravel and Backpack (Great Work!).

I'm trying to customize the columns showed with CRUD Controller, like this:
```
$this->crud->setColumns([
	'description',
	'filename',
	'deadline',
	'status',
	[
		'name' => 'category_id',
		'label' => 'Category',
		'type' => 'model_function',
		'function_name' => 'getCategoryName',
	]
]);
```

but the system return this error:
```
ErrorException in Columns.php line 30:
ucfirst() expects parameter 1 to be string, array given
```

Probably I've found a problem on PHP Columns Class ('/vendor/backpack/crud/src/PanelTraits/Columns.php').
In the public function 'setColumns', on lines 25, the method check if the **first** element on the passed array ($columns) is an Array.
But I've defined, the Array, in the parameter ($columns), in the last position.

I've modified the line (25) like this:
`if (is_array($column)) {`
and now check the single element on the array.

The lines from 21 to 35, now is:
```
// if array, add a column for each of the items
if (is_array($columns) && count($columns)) {
    foreach ($columns as $key => $column) {
        // if label and other details have been defined in the array
        if (is_array($column)) {
            $this->addColumn($column);
        } else {
            $this->addColumn([
                            'name'  => $column,
                            'label' => ucfirst($column),
                            'type'  => 'text',
                        ]);
        }
    }
}
```

Thanks.

**Comment by lloy0076** [comment]
Fixed by https://github.com/Laravel-Backpack/CRUD/commit/ae46bc11b6b4bd17cc46ebd75585345cbbbee38a
