### ISSUE TITLE
Login form doesn't not submit at enter key press

### ISSUE THREAD

**Issue by franciscocorrales** [Laravel-Backpack/Base#61]
Correct me if I'm wrong, but usually we want our forms to be submitted when the user press the enter key.

Currently, this is not happening, why ?

Views without this behavior: login, reset password (send email), reset password form, and every CRUD view.

---

I wanted to have this functionality in the login form, so, here is the code I added in the _auth/login.blade.php_, replace the submit button for this:

```
<input type="submit" class="btn btn-primary" value="{{ trans('backpack::base.login') }}">
<script>
 	document.addEventListener('keydown', function(event) {
        if (event.keyCode == 13) {// enter
        	document.getElementsByTagName("form")[0].submit();
        }
    });
 </script>
```

Is there an easier way ?, do I have to change all the forms ?

**Comment by tabacitu** [comment]
Hmm... I've already gone through all forms a few months ago to make sure they work like that. Just tested again, a fresh installation seems to already do that:
- all auth forms have ```<button type="submit">```, so they submit on Enter;
- the CRUD forms submit both on Enter and on Ctrl+S/Cmd+S;

Are you sure you don't have a browser plugin/javascript error in your layout that's messing with that?

**Comment by MarcosBL** [comment]
Confirmed working in latest

**Comment by tabacitu** [comment]
Thank you, @MarcosBL! Closing it.
