### ISSUE TITLE
Redirect Path on click of logout and password reset in laravel 5.3

### ISSUE THREAD

**Issue by Punith1234** [Laravel-Backpack/Base#62]
I followed the steps in [https://github.com/Laravel-Backpack/Base/issues/24](url) 
But was not able to resolve the redirect issue for logout .. can anyone has update on this

**Comment by tabacitu** [comment]
Hi @Punith1234 ,

Laravel 5.3's ```Route::auth()``` only registers a POST route for logout. If you want a GET route, you'll need to specify that manually in your routes file: ```Route::get('logout', 'Auth\LoginController@logout');```. I assume the button is still calling the default Backpack route, that's why it isn't redirecting where you specified.

Cheers!

**Comment by Punith1234** [comment]
Hi @tabacitu Thanks a lot for response.. If i logout from the admin/user its redirecting the user to login .. not admin/login .. how do i redirect to specific address.. any help?

**Comment by tabacitu** [comment]
Sorry to be so late to reply. You probably already have this figured out by now, but for posterity: you probably pointed the logout route to your Laravel's LoginController, not the one in Backpack, which redirects to admin/login. The correct route would have been:
```php
Route::get('logout', '\Backpack\Base\app\Http\Controllers\Auth\LoginController@logout');
```

My bad for giving bad directions above. Also modified there. Cheers!
