### ISSUE TITLE
Custom Domain with Backpack

### ISSUE THREAD

**Issue by tyteen4a03** [Laravel-Backpack/Base#63]
It would be nice if we can put Backpack routes on custom domains.

**Comment by tabacitu** [comment]
Hmm. Can you elaborate, please? I'm not sure I understand.

**Comment by tyteen4a03** [comment]
I mean registering the routes under another domain with the `domain` setting in `Route::group`. I'm not sure how rare a use case this is, but I do use this.

Granted I could just copy the files over and register them myself but since I don't know how often the controllers are updated this option would be handy.

**Comment by tabacitu** [comment]
Hmm... I think you can already do that. Wouldn't something like this be what you're looking for?

```php
Route::group(['domain' => '{account}.myapp.com', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
    CRUD::resource('tag', 'Admin\TagCrudController');
});
```

**Comment by tyteen4a03** [comment]
I meant the routes registered by BaseServiceProvider.

**Comment by tabacitu** [comment]
You can do that too. Check it out [here](https://laravel-backpack.readme.io/v3.0/docs/frequently-asked-questions#section-customizing-the-routes), I just added it to the FAQ.

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
