### ISSUE TITLE
Enhancement: Optional User Email Validation Feature

### ISSUE THREAD

**Issue by zschuessler** [Laravel-Backpack/Base#64]
FYI, this package integrates flawlessly with Backpack:

https://github.com/jrean/laravel-user-verification

All I had to do after install was add the middleware and Facade to  Base package:

```php
// File: BaseServiceProvider.php
public function setupRoutes(Router $router)
    {
        ...
        <!-- Add this middleware! -->
        $router->middleware('IsVerified', \Jrean\UserVerification\Middleware\IsVerified::class);

 ...

public function register()
    {
        ...

        <!-- Add this service provider! -->
        $this->app->register(\Jrean\UserVerification\UserVerificationServiceProvider::class);

       ...

        <!-- Add this service provider facade! -->
        $loader->alias('UserVerification', \Jrean\UserVerification\Facades\UserVerification::class);
```

And then to allow access to auth pages, but no dashboard pages:

```php
// File: Base\app\Http\Controllers\AdminController
public function __construct()
    {
        $this->middleware('admin');

        <!-- Add this check for your config setting! -->
        if (true == config('backpack.base.dashboard_requires_user_verification')) {
            $this->middleware('IsVerified');
        }
    }
```

I did add an extra config file value, as you can see in the check above, making user verification optional.

I don't think I missed anything, it really was that easy. You'll still need to decide how you want to handle errors and route the response accordingly (eg  users who registered but didn't verify get shown a specific page, instead of seeing the "User not verified" app error)

**Comment by lloy0076** [comment]
@zschuessler 

1. Are you still using this functionality (and is it still working)?
2. Depending on the response(s) below, I wonder if there's an easy PR lying about the place?

@tabacitu 

1. It seems some developers' clients (or themselves) want their users to confirm their e-mail first
    - Whilst it could be argued this is an admin panel only, it's a common enough request
2. Advantage of implementing above solution is that it is claimed to work with current backpack
    - I haven't yet tested it but can verify that the referenced `jrean` package does work on a default Laravel installation
3. Disadvantages include:
    - It brings in another external module
    - Still haven't decided how to handle failures (`jrean` package simply throws a rather horrid looking exception - it's explanatory but one wouldn't want to show it to a client TBH)

I see a few ways:

1. Put it on the back burner
2. Make it a tip, suggestion or tutorial
3. Address the advantages in a backpack manner so that at least the defaults aren't entirely awful and massage a PR out of this

Of course, if we wanted to avoid managing an external package we could implement our own e-mail verification setup but that violates a "don't reinvent the rule" to me.

**Comment by zschuessler** [comment]
jrean package still working wonderfully for me. Easy enough to extend their templates, that's what I did as well!

**Comment by tabacitu** [comment]
Hi guys,

I ran into this myself quite a few times. Email validation is something pretty basic - I wish Laravel did this out of the box. 

I completely agree with the @lloy0076's advantages and disadvantages. 

I don't know... wouldn't this make it more difficult for developers that build apps/admin panels that use "username" to login, not "email"? They wouldn't be able to just follow a standard Laravel tutorial to do that, they'd have to also remove this package and all the code we need to make it work... I'm afraid it would change the paradigm a little bit, from "_build from the ground up_" to "_slash and cut features to get what you need_". What do you guys think?

**Comment by zschuessler** [comment]
Great points to the both of you. My own personal opinion is to keep it out of the Base package (_which may be funny, as I started this issue..._). @tabacitu has had the philosophy of keeping this package as simple & least opinionated as possible, and I believe that's a good thing.

Ultimately email validation is still a custom use case. Perhaps common, but still not applicable to all installs, and should probably be outside of Base package.

When I started this issue I had a configuration option in mind to enable the validation feature (as I implemented in my own package). May be worth discussing a third party package system for this project. Haven't followed Backpack in 3 or so months so I'm not sure what the current philosophies or planned features are, but seems like email validation would be a nice fit for that kind of system. I'd prefer that over configuration bloat. If I recall right, the configuration options & main config file is rather verbose already ;)

**Comment by tabacitu** [comment]
@zschuessler I totally agree. Let's table the discussion for now and consider "email validation" as non-essential. For now. 

But let's also keep this conversation unlocked and let others give their two cents. We've all been wrong before :-)

Cheers!
