### ISSUE TITLE
Enhancement: Multiple active state on menu element

### ISSUE THREAD

**Issue by silentrazgriz** [Laravel-Backpack/Base#66]
Hi, thank you for making this awesome plugins.

I found some problem when i'm using this plugin specifically in the menu element.
If i use 2 link with similar word in front of each links
ex:
/admin/user
/admin/user-role

then when i'm on /admin/user page both of them will be marked as active menu (class="active")
![image](https://cloud.githubusercontent.com/assets/3212141/20926406/b9f15666-bbee-11e6-83f3-24f398b7e042.png)

I created some workaround for that in [resources/views/vendor/backpack/base/layout.blade.php](https://github.com/Laravel-Backpack/Base/blob/63968d31492c4eed0e031921e8c2a0b0e9323267/src/resources/views/layout.blade.php#L128-L131)

```
if ($(this).attr('href').startsWith(current_url) || current_url.startsWith($(this).attr('href')))
{
   $(this).parents('li').addClass('active');
}
```

into

```
if (
   ($(this).attr('href').startsWith(current_url) || current_url.startsWith($(this).attr('href')))
   && (current_url[$(this).attr('href').length] == '/' || current_url.length == $(this).attr('href').length)
) {
   $(this).parents('li').addClass('active');
}
```

i'm adding another validation for the active state so it must be either exactly similar to the url by comparing the length. or the next character must be '/'

so let's say i'm on /admin/user page, when it check on the /admin/user-role menu it won't mark it as false because after the /admin/user in /admin/user-role there is '-' character. but, if i'm moving to /admin/user/create it will set the /admin/user menu state to active

**Comment by zachweix** [comment]
Instead of doing your whole workaround, just switch the `||` to `&&`

**Comment by tabacitu** [comment]
@silentrazgriz this has been fixed since then by another PR, with a sightly different method. Please let me know if this doesn't work for you.

@zachweix I think this is a little trickier that that :-) Just replacing ```||``` with ```&&``` will make it work for the first URL segment, but not for the following. For example, on a CRUD create or EDIT screen, your menu won't be active, and I believe it should.


Cheers!
