### ISSUE TITLE
Add Dynamic Body Classes

### ISSUE THREAD

**Issue by zschuessler** [Laravel-Backpack/Base#68]
Either for Base or CRUD, it would be nice to have certain body classes added dynamically to the layout. Similar to WordPress, a route `/admin/product/52/edit` might add a class to the body of `admin-product-edit`.

This feature would allow frontenders to make changes in CSS alone instead of needing to mess with extensions/modifications of Blade templates.

I have a hacky[ service provider here](https://github.com/zschuessler/laravel-route-to-class) I wrote that is a good start. It will add a unique body class based on the current route. I don't envision this specific package making it into Base or CRUD, since it isn't pliable enough for custom use cases & rule sets, but it's a start for implementation ideas.

**Comment by OwenMelbz** [comment]
Have you tried using "str_slug" to handle all that preg_replace magic?

**Comment by zschuessler** [comment]
@OwenMelbz That was my first implementation in fact! `str_slug` won't remove content in between route parameters. So `/product/{productid}/edit` becomes `product-productid-edit` instead of `product-edit`. That's what initially prompted me to write the SP.

I also imagine the SP would allow users to extend the rule set to account for different use cases. Right now it's very tightly coupled and doesn't support additional rules a user might want, but here are some additional classes that I know I'd use too off top of my head:

1. `entity-{entity_name}` 
2. `{entity_name}-{entity_id}` 
3. `{entity}-{special_parameter}`

So all classes above considered might look like:

```php
<body class="product-software product-software-58 product-software-isDraft"`>
```

**Comment by tabacitu** [comment]
Whoooow. This is a really nice way to approach extreme customizations to the style, if you need that feature. Nice work.

This can be used as-is with Backpack\Base and Backpack\CRUD and it will do its magic, right?

**Comment by zschuessler** [comment]
@tabacitu check it out now, actually reworked the entire package to be usable in a package like Backpack.

You can now set any number of class generators. It's ready & stable as is, and will be adding more features in the 2.0 version as any requests come in!

**Comment by tabacitu** [comment]
@zschuessler , it doesn't look like there's been much support for this feature to be baked into Backpack since last year, so I'm going to close the issue.

Still think you've done great job, just not seeing this as general enough for everybody to use.

Keep up the good work. Cheers!
