### ISSUE TITLE
How can I customize the dashboard?

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/Base#74]
Is there any tutorial to customize the dashboard yet?

**Comment by tabacitu** [comment]
Hi @shinokada ,

No tutorial yet, sorry, but you can follow my instructions here: https://github.com/Laravel-Backpack/Base/issues/37#issuecomment-247524639

Cheers!

**Comment by shinokada** [comment]
Thanks. I had to run `php artisan config:cache`.

**Comment by habibi1981** [comment]
Hi
how i am use Adminlte calander in backpack dashborad page?
