### ISSUE TITLE
submenu not aligned

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/Base#77]
Is it only me that submenu is not aligned? The top of a submenu is 1-2px wider than its parent.

![screen shot 2016-12-28 at 5 59 54 pm](https://cloud.githubusercontent.com/assets/147320/21518128/870ec22a-cd27-11e6-95a7-9e1a9a657b37.png)

**Comment by shinokada** [comment]
I found that you need to overwrite css with this one.

```
body[class^='skin-'] .sidebar-menu>li>a {
  border-left: 3px solid transparent !important;
}

```

![screen shot 2017-01-03 at 5 49 37 pm](https://cloud.githubusercontent.com/assets/147320/21602992/15ed87f6-d1dd-11e6-95f0-f9b015f760b8.png)

**Comment by tabacitu** [comment]
Fixed, thank you!
