### ISSUE TITLE
Default backpack UserCrudController?

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/Base#78]
Hi,
how can i extend or replace default backpack usercrudcontroller?
i need to modify the the columns for the tableview as well as for the add new user fields.
i have added few more fields to my user model.
im using both laravel default auth as well as the backpack auth controller.. as i have different logics for both registration methods.
now when i go to the /admin/user view, i need to be able to modify its crud to reflect the changes.
thanks.

**Comment by OwenMelbz** [comment]
You'd need to just copy the whole controller/request from the vendor folder into you app. Then create a CRUD route for it.

Basically if you want to change it you'll need to do it yourself - the user package is designed to be a simple user management.

If you want anything more advance then you'd need to do it all yourself outside the package.
