### ISSUE TITLE
How to add own lang file

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/Base#80]
Hi I am wondering what the best way to add a lang file. Any suggestions?

**Comment by OwenMelbz** [comment]
Hey,

Lang isnt something specific to Backpack, its just default laravel functionality.

You should refer to the laravel docs https://laravel.com/docs/5.3/localization

**Comment by naghiloo** [comment]
there is no any base.php in this address for me: resources/lang/vendor/backpack/LANGUAGE_CODE/base.php

I just see crud.php here. but some words for example "dashboard" are translated.
I dont know where are they?

**Comment by tabacitu** [comment]
@naghiloo if there's no such file there, go ahead and create it, based on the one in the package. Laravel will pick up _your_ file then.
