### ISSUE TITLE
elfinder file manager route not found on shared host

### ISSUE THREAD

**Issue by rasez** [Laravel-Backpack/Base#83]
Hi 
I elfinder file manager works fine in localhost but in shared host it doesn't work and show 404 Not Found error
my URL in admin panel is "admin/elfinder"
what should i do?

**Comment by tabacitu** [comment]
Hi @rasez  - seems to be this bug https://github.com/Laravel-Backpack/CRUD/issues/311. We're working on it, please follow the process there. Cheers!
