### ISSUE TITLE
User Profile - edit password functionality

### ISSUE THREAD

**Issue by seandowney** [Laravel-Backpack/Base#86]
Is there a plan to include user profile editing including edit password functionality in Base?

Like a cut down version of the User edit form in the PermissionManager but to allow the current user edit their own profile details.

**Comment by OwenMelbz** [comment]
Hey @seandowney 

This does sound like potentially a useful feature actually!

I don't know if @tabacitu has any upcoming plans for something like this, as its pretty simple CRUD to build yourself within 30 mins or so, then could be saved for the future!

You could always create a GIST or GitHub repo with this as a prebuilt crud, then we could list it on the website for users who want to use it?

**Comment by seandowney** [comment]
Yeah I was thinking about creating a little package for it but thought I'd ask first.

I think it would be great to have it in Base though rather than to have to include something else when most people would want it?

//cc @tabacitu

**Comment by OwenMelbz** [comment]
Sure, although one thing to consider is Base doesn't contain CRUD, and CRUD is required for the adding/editing etc.

That would mean it would needed to be included in CRUD potentially, unless it was written as stand-alone. Which could then lead to duplicate code and extra maintenance.  

So would require a fair amount of planning to make sure its executed correctly!

**Comment by seandowney** [comment]
Ah right, I see what you mean.

Would it make more sense to add it to the PermissionManager then?

**Comment by tabacitu** [comment]
Hi @seandowney , @OwenMelbz ,

Totally agree this is a needed feature in Backpack\Base. I'll try to include it in this January release.

I see this more like the login/register/reset-password forms which come with Laravel - basic forms that do 1 thing, so maybe using Backpack\CRUD for this would be overkill. How about we insert two new methods in ```app\Http\Controllers\AdminController.php```:
- ```showMyAccountForm()``` - form with: email, name, password;
- ```saveMyAccountForm()``` - validates, saves, triggeres notification bubble and redirects back;

That should be simple to implement, do the job and preserve the separation of packages. Right?

**Comment by seandowney** [comment]
That sounds perfect. 

⁣

**Comment by OwenMelbz** [comment]
Heres a basic mockup of it https://github.com/Laravel-Backpack/Base/pull/88

**Comment by seandowney** [comment]
Cool looks good. 

Where do you click to get to it? On your name in the top left?

**Comment by OwenMelbz** [comment]
Can let the developer add it wherever they like, to what ever suits their application

It has a route name so you can link to it easy enough. Using something like route('backpack.profile.edit')

**Comment by seandowney** [comment]
Yeah I think it should have a default location though.

Either from the logged in persons name (top left) or as an Edit Profile link above the Logout link?

**Comment by OwenMelbz** [comment]
Sure, could be updated in the future somewhere after tabacitu has planned it if he wants it.

Although we always need to consider users don't want this, forcing it into a default location would require them to use it.

It's also currently a non-breaking change, if you modified one of the views now users would need to republish and migrate their views for it.

I think it would be best as a drop down in the top right. To keep space usage at a minimum, however that would then beg the question what to display as the default view. Would we move the avatar and name into the top right instead to save duplicate content?

Would just need to be planned through

**Comment by seandowney** [comment]
Yes fair enough.  I will leave both of you to decide and thank you both for your work on it.

**Comment by lloy0076** [comment]
As a comment on the side, I fairly much tell users if they want to change their passwords, they should use the "I Forgot My Password" link.

**Comment by tabacitu** [comment]
Working on this now on @OwenMelbz 's PR here - https://github.com/Laravel-Backpack/Base/pull/88 . Let's move the discussion there please.

Cheers!
