### ISSUE TITLE
Add helpers.php with some functions

### ISSUE THREAD

**Issue by vadag** [Laravel-Backpack/Base#89]
This could be handy to have some functions as shortcuts for commonly used tasks. For examples, instead of having 
```config('config('backpack.base.route_prefix', 'admin').'/model'```
we could have something like this in helpers.php:
```php
if ( ! function_exists('backpack_url') ) {
    /**
     * Returns backpack admin url from config appended with some path
     *
     * @param $path
     *
     * @return string
     */
    function backpack_url( $path = null )
    {
        $path = ! $path || (substr($path, 1, 1) == '/') ? $path : '/' . $path;
        return config('backpack.base.route_prefix', 'admin') . $path;
    }

}
```
and use ```backpack_url()``` or ```backpack_url('model')``` instead. (I think the code would become much cleaner).
Of course this is just an example

**Comment by tabacitu** [comment]
I love it! @OwenMelbz , @lloy0076 , @tumf87 , @OliverZiegler , @MarcosBL any ideas for new helpers that would make the code cleaner?

**Comment by MarcosBL** [comment]
Never thought about it, but I love the suggestion! +1 for this

**Comment by OwenMelbz** [comment]
@tabacitu I can't add "grrr" eyes :P

https://github.com/Laravel-Backpack/Base/blob/0bb012172b93899d9e8be751ead939a4c33e906a/src/helpers.php

**Comment by tabacitu** [comment]
:-)) @OwenMelbz - I think that didn't get merged because it had too many features rolled into one PR (mainly the guard, which I hope I get to tackle today too). I don't know what my opinion on helpers was back then, but now they sound like a good improvement to me.

**Comment by tabacitu** [comment]
@vadag , I do think that if we call the helper ```backpack_url()```, it should return a URL, rather than a string, to be a real alternative to ```url()```. Do you agree? As such I would make a small change like so:

```diff
    function backpack_url( $path = null )
    {
        $path = ! $path || (substr($path, 1, 1) == '/') ? $path : '/' . $path;
-       return config('backpack.base.route_prefix', 'admin') . $path;
+       return url(config('backpack.base.route_prefix', 'admin') . $path);
    }
```

That means anywhere inside the app we can use ```url()``` for a regular URL and ```backpack_url()``` whenever we want it prefixed. I think that's more intuitive.

**Comment by tabacitu** [comment]
I'll close this issue as it's been fixed in the ```upgrade``` branch, but please let me know what you think and if you find new helpers that would prettify our code. Cheers!
