### ISSUE TITLE
Multi auth

### ISSUE THREAD

**Issue by manytimes1** [Laravel-Backpack/Base#93]
Hi, need to make separarte login for admin (who can access to all pages and settings of system) and another for standard users. At the moment every user when create his account and log in have access anywhere. Any solution?

**Comment by OwenMelbz** [comment]
Yeah its called the search feature :D

Theres a full feature PR ->
https://github.com/Laravel-Backpack/Base/pull/87

And there's lots of scattered issues with solutions in, specifically you can checkout the permission manager repo.

I don't personally have time right now to go through them (lots of people create new ones each time so its hard to find the ones with good solutions in) but somebody else might

**Comment by manytimes1** [comment]
Hmm very funny (evil)
I check this feature two days ago - didn't work .... And yes i use fantastic feature called "search" before post ;)
