### ISSUE TITLE
Any differences of installing on Laravel 5.4?

### ISSUE THREAD

**Issue by andreich1980** [Laravel-Backpack/Base#94]
Have anyone already tried?

**Comment by OwenMelbz** [comment]
We've been using the master (now 5.4) branch for maybe 2-3 months now, and its completely fine.

Only vanity changes to make

**Comment by andreich1980** [comment]
Thanks for your answer. Cheers!

**Comment by tabacitu** [comment]
Hi guys,

Already working on this and have done the grunt work. I expect an official release to be ready by the end of the week. I'll send you guys [a newsletter](https://laravelbackpack.us13.list-manage.com/subscribe?u=481cc18afdb1e440e3dbfc3a4&id=fc930b1077) when it's out.

The only remaining problem is that a bunch of dependencies do not support Laravel 5.4 yet, so we're waiting for them to update too.

Cheers!

**Comment by andreich1980** [comment]
@OwenMelbz It seems that I have to install the backpack manually because it depends on L5.3?

Or is there any other way to install with composer?

**Comment by OwenMelbz** [comment]
If you wanna mess around you can update your `composer.json` to something like `"laravel/framework": "5.4 as 5.3"` so you can use the new version, everything else will think its 5.3

**Comment by andreich1980** [comment]
@OwenMelbz I tried aliases `"laravel/framework": "5.4.* as 5.3",` and `"laravel/framework": "5.4 as 5.3",`, didn't work :(

**Comment by tabacitu** [comment]
Hi guys,

Just pushed the Laravel 5.4 compatibility. I actually managed to achieve it as a non-breaking change, so it's:
- Backpack\Base 0.7.15
- Backpack\CRUD 3.1.57

No more tricks needed. You can revert your composer.json to its original state and run ```composer update```. It should pull in the correct versions of the packages above, if you're running on L5.4, and everything should work as expected.

**Please tell me if you encounter any issues.**

**Note 1:**
As of 02 Feb 2017, ```laracasts/generators``` is not officially compatible with L5.4. I have submitted the fixes, they've been merged, they work perfectly, but they haven't been officially tagged and published. For now, you can install ```laracasts/generators``` on L5.4 by:
1) manually specifying this in your composer.json file, in the ```require-dev``` section:
        ```"laracasts/generators": "dev-master as 1.1.4",```
2) then running ```composer update```

**Note 2:**
This 5.4 compatibility will also be included in the next Backpack\CRUD release (3.2), of course. That one still needs a bit of polishing and documentation.
