### ISSUE TITLE
update this package with the main package

### ISSUE THREAD

**Issue by sarmenhb** [Laravel-Backpack/Base#95]
the views in this project needs to be updated with the views on this package https://github.com/Laravel-Backpack/Base . the admin routes  are hard-coded whereas the main package it uses the config options. im kinda stoned hope that made sense. thanks.

**Comment by OwenMelbz** [comment]
Can you give us an example please?

**Comment by sarmenhb** [comment]
if you go here, https://github.com/Laravel-Backpack/Demo/blob/master/resources/views/vendor/backpack/base/inc/menu.blade.php

notice how the admin url is hardcoded? ex : "{{ url('admin/login') }}

in the base package this has been updated but not on teh demo repo

thanks

**Comment by OwenMelbz** [comment]
Ah right, thanks for pointing it out :)

Feel free to add a pull request!

It is worth mentioning you should not be using he demo project for anything but viewing as a demo :) which means it doesn't matter too much!

**Comment by tabacitu** [comment]
Fixed!
