### ISSUE TITLE
Do not publish all views in the installation process

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#97]
When this project started, I expected people to modify the base files a lot. After using backpack a lot in the past year, I did NOT find myself modifying anything. So as @OwenMelbz suggested here https://github.com/Laravel-Backpack/CRUD/pull/399, maybe It makes sense to publish only the few files you actually need to update, upon package installation.

Files I think should be published during installation:
- errors
- vendor/backpack/base/inc/menu.blade.php
- vendor/backpack/base/inc/sidebar.blade.php
- vendor/backpack/base/dashboard.blade.php

PROs:
- we could push view file fixes more easily (this has rarely been needed, though);

CONs:
- would make it a little more difficult for first-time users to understand where the files are;
- would make it a little more difficult to make a modification to layout, etc, when you do need it;

Thoughts?

**Comment by OwenMelbz** [comment]
I honestly think the less the better! Makes it easier to consume when first learning.

Then as long as the documentation explains about other files it should be fine :)

Maybe create a list of everything it currently publishes, then create a section that lists how to publish any of the previously published content.

Also I assume your list should contain the configs? :D

**Comment by macecchi** [comment]
I'm with @OwenMelbz that the less the better! 

As long as this is clearly stated in the docs and there are commands to publish the other views, it should be fine.

Another idea would be to add parameters (maybe in config/backpack/base.php) to configure the menu and sidebar items (such as in crud's `addColumns` etc) and the initial dashboard view.
 
This way, no views would have to be published when setting up the project and it would probably fit most people - the only changes I have made were in the files you mentioned and they were only to add items to menu or sidebar, or to change the initial (dashboard) view.

**Comment by leith** [comment]
Looking at making a fresh project and following the instructions today, there are a _lot_ of files that get published back - including a lot of JS/CSS that I know I'm never going to change. So slimming this down would be a great idea, particularly to ensure that any repositories for projects using this aren't bloated with vendor files that won't change, or will only have changes mandated by the version of the vendor library being loaded.

You could also do some kind of conditional including - using a special yield section, or checking for a public blade's existence and loading it if it is (while still retaining the surrounding parts). I like the idea of config-driven menus, but being able to inject my own blade content has its appeal as well, particularly for the dashboard.

**Comment by lloy0076** [comment]
I like the way that `jeroennoten/laravel-adminlte` [here](https://github.com/jeroennoten/Laravel-AdminLTE] configures AdminLTE - not that I'm advocating any changes here.

**Comment by tabacitu** [comment]
Guys, it's been some time now since we've needed to change any Backpack\Base views in a backwards-incompatible way, so I don't think this is such a big problem anymore. 

Sure, a lot of files get published:
<img width="252" alt="screen shot 2017-09-11 at 14 09 47" src="https://user-images.githubusercontent.com/1032474/30271953-e9cd3c50-96fa-11e7-8645-994b03420544.png">

But I no longer think publishing some of them (but not all) is a good solution either:
- we can't NOT publish all CSS and JS files, since they need to be in the ```public``` folder to be available to the HTTP server;
- it would make it soo much more difficult to understand how to overwrite blade files and where things happen;
- it wouldn't actually help that much in terms of maintainability; ```layout.blade.php``` is the only one that historically has seen the most changes, and it's one of the first files people overwrite;

Of course, I might be wrong, please let me know if that's so. I'm the one who raised the issue, after all, so I think opinions do change, and that's ok. But right now I think this is a non-issue and I'll close it.

Cheers, thanks for the great feedback!
