### ISSUE TITLE
Greek language file should be in /el/ directory

### ISSUE THREAD

**Issue by automat64** [Laravel-Backpack/Base#99]
Greek language locale is "el".

Currently it is in the 'gr' directory which is the country code for Greece.

**Comment by automat64** [comment]
There is also a future tense error in the translations. Should I create a pull request?

**Comment by tabacitu** [comment]
Huh. Didn't know the ISO code is "el" for greek. But it makes sense :-)
Yes, a PR would be great, thank you.

**Comment by tabacitu** [comment]
Fixed. Thanks for the PR. Cheers!
